### ISSUE TITLE
Using Dictionary to compress zeros?

### ISSUE THREAD

**Issue by aleksazr** [lz4/lz4#1003]
(I had a post here, but it is deleted now, can't find it)
I was compressing the alpha channel of a mostly opaque bmp, so it was mostly zeros,
and the output file was longer than expected, so I just compressed it twice.

I'm now thinking of using a dictionary to compress such files, is that possible?

I was thinking of creating a run-time memclr() table, and using that as a dictionary,
but first tried to test it with LZ4.exe, and both of these lines produce the same result:

LZ4.exe test.bin
LZ4.exe -D clr.dic test.bin

test.bin is a 1MB file, and clr.dic is a 64kb file, both containing only zeros.
(you can get the files from here http://users.beotel.net/~gwh/lz4/lz4-dict.zip)

(btw, I don't get any report that a dictionary was used or not, that should be changed probably)

**Comment by Cyan4973** [comment]
Yes, for this use case, such result is not too surprising.

The primary limitation of `lz4` when compressing many zeroes is its maximum compression factor, which is ~x250.
So, if you compress 1 MB of zeroes, the compressed size should be ~4KB, and there's nothing else that can be done, because it's a format limitation. 
Compressing a second time works in this case because the compressed stream mostly consist of `0xFF` bytes, each one extended the segment size by 255 bytes.
A dictionary doesn't help much, we still need to represent the 1 MB length using `0xFF` expansion bytes.

This is obviously a corner case. Most data do not consist of that many zeroes, in which case, the maximum compression factor is less of an issue.
