### ISSUE TITLE
Test and issue for `LZ4_MEMORY_USAGE` configurations

### ISSUE THREAD

**Issue by t-mat** [lz4/lz4#1016]
As a consequence of merging of PR #1013, we need test for it.  We also need to determine a valid range of `LZ4_MEMORY_USAGE`.  I describe the deatils below.

**Comment by t-mat** [comment]
I initially proposed to add the following test to `tests/Makefile`.

```Makefile
# tests/Makefile
	.PHONY: test
-	test: test-lz4 test-lz4c test-frametest test-fullbench test-fuzzer test-install test-amalgamation listTest test-decompress-partial
+	test: test-lz4 test-lz4c test-frametest test-fullbench test-fuzzer test-install test-amalgamation listTest test-decompress-partial test-compile-with-lz4-memory-usage

+	test-compile-with-lz4-memory-usage:
+		CFLAGS="-O2 -D'LZ4_MEMORY_USAGE=12'" $(MAKE) clean all	# FAIL
+		CFLAGS="-O2 -D'LZ4_MEMORY_USAGE=13'" $(MAKE) clean all
+		CFLAGS="-O2 -D'LZ4_MEMORY_USAGE=14'" $(MAKE) clean all
+		CFLAGS="-O2 -D'LZ4_MEMORY_USAGE=15'" $(MAKE) clean all
+		CFLAGS="-O2 -D'LZ4_MEMORY_USAGE=16'" $(MAKE) clean all
+		CFLAGS="-O2 -D'LZ4_MEMORY_USAGE=17'" $(MAKE) clean all
+		CFLAGS="-O2 -D'LZ4_MEMORY_USAGE=18'" $(MAKE) clean all
+		CFLAGS="-O2 -D'LZ4_MEMORY_USAGE=19'" $(MAKE) clean all
+		CFLAGS="-O2 -D'LZ4_MEMORY_USAGE=20'" $(MAKE) clean all
```

But `LZ4_MEMORY_USAGE=12` fails to pass `lz4frame tester` so far.

```sh
cd lz4/tests
CFLAGS="-O3 -D'LZ4_MEMORY_USAGE=12'" make clean test-mem	# FAIL (lz4frame tester)
```

```
Starting lz4frame tester (64-bits, 1.9.3)
Seed = 4537
...
LZ4F_compressFrame_usingCDict, with NULL dict : 33821 bytes
LZ4F_compressFrame_usingCDict, with dict : compressed 64512 bytes into 38101 bytes
cSizeWithDict (38101) should have been more compact than cSizeNoDict(33821)
Error detected !
```

**Comment by t-mat** [comment]
I'd like to discuss about the following open questions:

### (1) What is "valid" range of `LZ4_MEMORY_USAGE`?

note: The original version of PR #1013 had a note for valid range of `LZ4_MEMORY_USAGE`.
I mean "valid" as a possible `LZ4_MEMORY_USAGE` values which must be maintained, tested.

personal opinion:  At least it should be [10,20] as documented.  I'm sure it's relatively minor feature.  So we don't need to test extreme value.  But it'd be nice to have some guidelines for valid/acceptable/recommended range of it.

### (2) Smaller `LZ4_MEMORY_USAGE` "degrades" compression ratio.  Should we accept it?
personal opinion: Yes, we (including library user who set small `LZ4_MEMORY_USAGE`) should accept it.  But having notice of it in the document would be nice.

### (3) Should we add special code path to `tests/frametest.c` which determine and care smaller `LZ4_MEMORY_USAGE`?
personal opinion:  If we accept less than `13`, we should care about it.

**Comment by Cyan4973** [comment]
Yes, I agree with the suggestions.

We should allow extended memory usage values, and [10,20] seems like the minimum range I would like to support.

We can support an even larger range, like [8,24] for example,
but there is indeed a point after which it does no longer make sense.
Either compression ratio plummets too drastically, or the increase in memory usage doesn't translate into any sensible gain.
So I'm also fine with the idea of upper / lower limits, 
that would give an official behavior for "extreme" values.

Yes, we should mention the cost in compression ratio when decreasing memory usage.

For tests, while it seems reasonable to add some tests for this feature, typically for "limit" values, we should also pay attention to not increase test duration too much. Longer tests negatively impact code velocity, so this is a kind of diffuse cost, that everybody pays in the future.
We want to keep these tests at a low runtime cost.

**Comment by Cyan4973** [comment]
Regarding the test failure for `LZ4_MEMORY_USAGE<=12`,
I believe it is a _test_ issue, rather than an `LZ4` one.

Sure, we expect that using a dictionary should always improve compression ratio compared to "not using it".
But is that the right expectation ? And even if yes, is the test a correct scenario ?

So I would start by trying to understand how come compression ratio is worse in this case.
There might be some good learnings from this, that could be used to improve `LZ4` performance with dictionary.

**Comment by Cyan4973** [comment]
Testing again this issue (for reference) : 

with `LZ4_MEMORY_USAGE=13` : 
```
LZ4F_compressFrame_usingCDict, with NULL dict : 36509 bytes
LZ4F_compressFrame_usingCDict, with dict : compressed 64512 bytes into 2796 bytes
LZ4F_decompress_usingDict : Regenerated 64512 bytes
```

with `LZ4_MEMORY_USAGE=12` :
```
LZ4F_compressFrame_usingCDict, with NULL dict : 36146 bytes
LZ4F_compressFrame_usingCDict, with dict : compressed 64512 bytes into 44408 bytes
cSizeWithDict (44408) should have been more compact than cSizeNoDict(36146)
``` 

So indeed, on reaching `LZ4_MEMORY_USAGE=12`, compression ratio with dictionary plummets.
Looking at `LZ4_MEMORY_USAGE=13`, compression ratio is really excellent, meaning that the dictionary is extremely efficient in this case. Likely a very close equivalent of content to compress.
The main reason that comes to mind for the failure at 12 is that `lz4` internal hash table gets oversubscribed too much, and starts to lose track of older parts of the dictionary. Therefore it becomes unable to notice that older parts of the dictionary are equivalent to input.
This, however, only explains why the compression ratio is not better, not why it's much _worse_ than without dictionary. That part is still unclear. We could invoke the law of chaos, and state that the match finder is simply unlucky, selecting poor matches instead of better ones when no dictionary is present, but it seems that the performance difference is too large to be "just" due to this effect.

Also, I note that the compressed sizes measured today are different (and much worse) than the ones measured in August. It's also unclear why.
_edit_ : apparently, numbers change at every run, so it just indicates a randomly generated test condition. To stabilize results, stabilize the `seed`.

**Comment by Cyan4973** [comment]
OK, I get where the compression advantage without dictionary comes from.

In presence of small input (< 64 KB), the `lz4` compression engine uses a special "small block" mode, which allows it to use more references than usual. On top of that, it reduces match length to 4 bytes, which tends to help for compression ratio.
In contrast, the "normal" mode has 2x less references, and keep the "default" match length search, which is set to 5 bytes in 64-bit modes. 
As a consequence, on "small" data (< 64 KB), the "default" mode loses in compression ratio.

I guess it gives us a clue to refactor the test to avoid this impact.

**Comment by Cyan4973** [comment]
OK, so I think I've got a proposal that covers all points mentioned in this issue,
save the last one : what to test ?

The current proposal is a `build` test, using all authorized values of `LZ4_MEMORY_USAGE`.
I'm unsure what kind of value it brings ?
If the point is just to ensure that the code compiles properly, we could limit the test to extreme values of `LZ4_MEMORY_USAGE`, and use faster compilation modes. 
But then, if it's just a build test, we wouldn't see the kind of runtime error this issue mentions.

So what would be a correct scope ?

**Comment by t-mat** [comment]
> I'm unsure what kind of value it brings ?

Firstly, since `LZ4_MEMORY_USAGE` is relatively minor, I believe it's 100% okay to just add some warnings to its comment.  For example, 

> > LZ4_MEMORY_USAGE: If you change this value, we strongly recommend 
> > you to run `make test` *on your target platform*.

But if we have test for `LZ4_MEMORY_USAGE` (extensively, in future),
we can safely say `LZ4_MEMORY_USAGE` is a first-class/well-tested functionality of LZ4.

Therefore, users are able to use it without much cautions.


> So what would be a correct scope ?

So far, I think friendliness for contributors is a good introduction of it.
I mean they'll find some failure of tests when they overlook `LZ4_MEMORY_USAGE` (when computing memory size, test regressions, etc).

So, I think `make all` for `LZ4_MEMORY_USAGE_MIN` and `LZ4_MEMORY_USAGE_MAX` are minimum test for them.

```
test-compile-with-lz4-memory-usage:
	CFLAGS="-O2 -D'LZ4_MEMORY_USAGE=LZ4_MEMORY_USAGE_MIN'" $(MAKE) clean all
	CFLAGS="-O2 -D'LZ4_MEMORY_USAGE=LZ4_MEMORY_USAGE_MAX'" $(MAKE) clean all
#	CFLAGS="-O2 -D'LZ4_MEMORY_USAGE=LZ4_MEMORY_USAGE_DEFAULT'" $(MAKE) clean all  # Redundant test.
```

And we can add dedicated entry point in `ci.yml` to speed them up.


Of course we'll think about and find many corner cases.  But we can add them gradually.

**Comment by Cyan4973** [comment]
I think latest update of #1061 answers all points in this issue, including having a minimal test in CI.
As you said, this is a starting point, from which we can evolve in the future as new needs arise.
