### ISSUE TITLE
Cannot install liblz4 on Windows!

### ISSUE THREAD

**Issue by FeriBolour** [lz4/lz4#1021]
I've been trying to install the "flann" library and it gives me the following error:
`No package 'liblz4' found`
When I am trying to follow the instructions to install liblz4 I get some errors that I don't know how to solve. 
After cloning the the github repo I run the `make` command but this is what it gives me:
`
process_begin: CreateProcess(NULL, uname, ...) failed.
Makefile.inc:8: pipe: No error

process_begin: CreateProcess(NULL, uname, ...) failed.
Makefile.inc:12: pipe: No error

process_begin: CreateProcess(NULL, uname, ...) failed.
Makefile.inc:18: pipe: No error

process_begin: CreateProcess(NULL, uname, ...) failed.
Makefile.inc:22: pipe: No error

process_begin: CreateProcess(NULL, uname, ...) failed.
Makefile.inc:26: pipe: No error

process_begin: CreateProcess(NULL, uname, ...) failed.
Makefile.inc:44: pipe: No error

process_begin: CreateProcess(NULL, uname, ...) failed.
Makefile.inc:54: pipe: No error

process_begin: CreateProcess(NULL, uname, ...) failed.
Makefile.inc:65: pipe: No error
process_begin: CreateProcess(NULL, uname, ...) failed.
Makefile.inc:79: pipe: No error

process_begin: CreateProcess(NULL, uname, ...) failed.
Makefile:106: pipe: No error

make[1]: Entering directory 'C:/Program Files/lz4/lib'
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
process_begin: CreateProcess(NULL, uname, ...) failed.
../Makefile.inc:8: pipe: No error
process_begin: CreateProcess(NULL, uname, ...) failed.
../Makefile.inc:12: pipe: No error
process_begin: CreateProcess(NULL, uname, ...) failed.
../Makefile.inc:18: pipe: No error
process_begin: CreateProcess(NULL, uname, ...) failed.
../Makefile.inc:22: pipe: No error
process_begin: CreateProcess(NULL, uname, ...) failed.
../Makefile.inc:26: pipe: No error
process_begin: CreateProcess(NULL, uname, ...) failed.
../Makefile.inc:44: pipe: No error
process_begin: CreateProcess(NULL, uname, ...) failed.
../Makefile.inc:54: pipe: No error
process_begin: CreateProcess(NULL, uname, ...) failed.
../Makefile.inc:65: pipe: No error
process_begin: CreateProcess(NULL, uname, ...) failed.
../Makefile.inc:79: pipe: No error
process_begin: CreateProcess(NULL, uname, ...) failed.
Makefile:62: pipe: No error
process_begin: CreateProcess(NULL, uname, ...) failed.
Makefile:122: pipe: No error
compiling static library
process_begin: CreateProcess(NULL, cc -DXXH_NAMESPACE=LZ4_ -O3 -c lz4.c lz4frame.c lz4hc.c xxhash.c, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: *** [Makefile:90: liblz4.a] Error 2
make[1]: Leaving directory 'C:/Program Files/lz4/lib'
make: *** [Makefile:53: lib-release] Error 2
`

Could anyone help me with this as soon as possible?

System
 - OS: Windows
 - Version :10
 - Compiler: gcc

**Comment by t-mat** [comment]
Hi @FeriBolour, 
Could you provide just a bit more about your environment?  It seems you're using some POSIX flavor shell, but we can't determine what system you're using.

Please run the following commands in your terminal to retrieve further information.  And please post the result if you can.

```sh
uname -ros
cmd.exe /c ver
```

----

> ```
> make[1]: Entering directory 'C:/Program Files/lz4/lib'
> ```

Usually, you need admin or special privilege to create/modify directories or files under `C:\Program Files\`.
Since it tend to cause many issues due to permissions, I recommend you to use your home directory (`~`) instead of `C:\Program Files\` for cloning/building lz4.

For example, you can relatively safely clone and build lz4 with the following commands.

```sh
cd
git clone https://github.com/lz4/lz4.git lz4-issue-1021
cd lz4-issue-1021
make
```

**Comment by FeriBolour** [comment]
> Hi @FeriBolour,
> Could you provide just a bit more about your environment? It seems you're using some POSIX flavor shell, but we can't determine what system you're using.
> 
> Please run the following commands in your terminal to retrieve further information. And please post the result if you can.
> 
> ```shell
> uname -ros
> cmd.exe /c ver
> ```
> 
> > ```
> > make[1]: Entering directory 'C:/Program Files/lz4/lib'
> > ```
> 
> Usually, you need admin or special privilege to create/modify directories or files under `C:\Program Files\`.
> Since it tend to cause many issues due to permissions, I recommend you to use your home directory (`~`) instead of `C:\Program Files\` for cloning/building lz4.
> 
> For example, you can relatively safely clone and build lz4 with the following commands.
> 
> ```shell
> cd
> git clone https://github.com/lz4/lz4.git lz4-issue-1021
> cd lz4-issue-1021
> make
> ```

As far as I know `uname` doesn't exist for windows!
`'uname' is not recognized as an internal or external command,
operable program or batch file.`

but after `cmd.exe /c ver`:
`Microsoft Windows [Version 10.0.19043.1110]`

I tried your suggested commands and I still get the exact same errors.

I see that in the "build" folder of lz4, there's only VS2010 and VS2017; I have VS2019 installed on my PC. Does that matter?
Do you have any other suggestions?

Thank You

**Comment by t-mat** [comment]
> As far as I know uname doesn't exist for windows!
> ```
> 'uname' is not recognized as an internal or external command, operable program or batch file.
> ```

Thanks for the info.  And you're right.  But the following error from the beginning of your log also means "`make` command failed to invoke `uname` as a child process".

> ```
> process_begin: CreateProcess(NULL, uname, ...) failed.
> Makefile.inc:8: pipe: No error
> ```

Invoking `uname` has failed from `make` command and your shell.

So, it seems this issue is caused by setup of your environment.  Because `uname` is one of the fundamental command of Unix-style shell environment.

Please understand that `Makefile` is tailored for POSIX or Unix-like style shell and their standard commands.  You need to setup shell environment if you want to use it properly.

Please also note, we can't help you to setup your own environment.  It is out of our scope.

----

If you're sure that your setup is fine, I'd like to ask the following questions

- What is your shell?  For example, `bash`, `cmd.exe`, etc.
- How did you install `gcc`, `make` and `git`?
- Can you run the following command in your terminal and post the result to this issue?

```cmd
where gcc
where make
where git
```

- Did you try to build "Hello, world" style small project with `gcc` and `make` in your environment?

----

> I see that in the "build" folder of lz4, there's only VS2010 and VS2017; I have VS2019 installed on my PC. Does that matter?

No, it doesn't matter.

----

> Do you have any other suggestions?

If you wan't to use `make` command, I recommend you to understand basics of Unix-style shell, `make` and `Makefile`.

**Comment by vtorri** [comment]
with MSYS2, no problem
