### ISSUE TITLE
Custom memory management functions for malloc and free

### ISSUE THREAD

**Issue by jeevanladhe** [lz4/lz4#1031]
Hi experts,

I am working on a project where I am trying to use LZ4 frame compression for backup. I would like to use custom malloc/free functions just like how gzip and ZSTD allows to use us.

Will it be possible for LZ4 to support this kind of custom alloc/free functions?
This is needed because the code where we are freeing the compression context might not be reachable by application if it error's out half-way. The custom functions would allocate the memory in certain contexts and that way it will be cleared once the context is released. This way we can avoid the memory leak.

Kindly note that I am willing to contribute the patch if we are open for this proposal and I am allowed to do so.

Appreciate your help.

Regards,
Jeevan Ladhe

**Comment by Cyan4973** [comment]
The way this use case is supported in `lz4` is with build macro `LZ4_USER_MEMORY_FUNCTIONS`, documented here : 
https://github.com/lz4/lz4/tree/dev/lib#build-macros

It allows users to define their own functions `LZ4_malloc()`, `LZ4_calloc()` and `LZ4_free()`, that will then be used by the `LZ4` library whenever it needs to allocate something (which is pretty rare).

Note though that it is a build macro, hence essentially usable for static linking scenarios. In general, this kind of capability is required in some embedded environment, where static linking is the norm, so it has proven sufficient so far.
If it's not good enough for your use case, I'm interested in understanding your context and why your scenario requires to define allocation functions at runtime.

**Comment by rhaas-edb** [comment]
Hi,

I'm a colleague of Jeevan Ladhe. In this case, we are writing code for possible inclusion in PostgreSQL, which has its own allocator. We expect PostgreSQL to be installed on systems where liblz4 is already present. We don't think most packagers would be pleased with the idea of compiling a second version of liblz4 specifically for PostgeSQL. Certainly, if many popular open source projects started using LZ4 and all of them needed their own copies of the library, it would become quite awkward, not only because of the additional packaging work but also because of the difficulty of keeping all the copies up to date.

We can (and probably will) work around this problem on the PostgreSQL side. The reason why a custom allocator would be handy here is that, in the event that PostgreSQL throws an error, any memory allocated by LZ4 would automatically be released along with all the other memory that's no longer needed. Without a custom allocator, we'll have to engineer a custom mechanism to make sure that we don't leak memory, which is not the end of the world, but a custom allocator would make things quite a bit simpler.

I hope this makes sense. Thanks.

**Comment by Cyan4973** [comment]
So, if you use PostgreSQL in combination with `liblz4`'s dynamic library, then I presume it is not an embedded environment, and the system is fine using the "default" build settings for `liblz4`.

When using the default settings, chances are that `lz4` doesn't need any heap allocation.

Now, this sentence certainly deserves some double check. It's true when using the "regular" `lz4` functions, like `LZ4_compress_fast()` or `LZ4_decompress_safe()`. But it's not when using "advanced" functions, like `lz4hc` or the streaming variants (which must maintain state between successive calls).
Even for these advanced scenarios, there are solutions to allocate memory using one's own custom allocator, but before going there, it would be useful to know if this is even a case that happens.

**Comment by rhaas-edb** [comment]
Perhaps we're doing something wrong, but the concern was about the memory allocated by LZ4F_createCompressionContext().

**Comment by Cyan4973** [comment]
Ah, so this is the streaming variant, and it does indeed allocate memory.
This memory is needed to maintain a "state" between successive invocations.

This is the more complex scenario, and unfortunately, there is currently no other solution than the one already mentioned above, requiring a version of `liblz4` statically linked and compiled with a specific build flag.

While I could imagine a hackish way to make it work with current interface, I believe a cleaner solution would be to create a new interface for this need. Something like `LZ4F_createCCtx_advanced(mem_functions)` typically.

Let's add that to the backlog.

**Comment by rhaas-edb** [comment]
Cool! Thanks for considering it.

**Comment by Cyan4973** [comment]
In #1115, there is a proposal for a new API supporting custom memory managers.

You are welcome to provide your feedback on the proposed API : 
https://github.com/lz4/lz4/pull/1115/files#diff-7668a0ef7fed03c892a11e60e5ecdc25472b0a801bb2445aefbd61d547937c81R654

**Comment by Cyan4973** [comment]
Proposal merged
