### ISSUE TITLE
LZ4Frame: Use pre-allocated memory

### ISSUE THREAD

**Issue by avrahamshukron** [lz4/lz4#1034]
I'm working on an embedded platform in which I would like to apply FW compression.
I have enough RAM space for the uncompressed image of course, But not much of heap space.
I'd like to do the decompression directly onto the RAM area from which it will be executed.

I tried using the LZ4F API but it fails with `LZ4F_ERROR_allocation_failed`.
As far as I can tell it fails in `dstage_init` stage of `LZ4F_decompress` when it tries to allocate `dctx->maxBlockSize` buffer.
During FW compression I set the the block size to be `64KB` which is the minimum, and no dependency between blocks.
But I don't have 64KB of heap space.

So my question is: Is it possible to use LZ4F with static buffer allocation assuming independent blocks?

**Comment by Cyan4973** [comment]
This use case seems too constrained for `LZ4F`.
It looks like this environment requires you to be completely in charge of memory.

In which case, it seems better to use `lz4.h` directly.
`LZ4_decompress_safe()` will not allocate any memory, just a minimal amount of stack space, and it only writes into a user-specified buffer, which can be any size, including much smaller than 64 KB. Of course, if the amount of data to regenerate is larger than what the buffer can contain, it will safely stop and return with an error code.

The downside is that `lz4.h` doesn't deal with metadata nor the frame format : it only takes care of the raw block compression format. So it needs to be told exactly how much data there is to decompress.

**Comment by avrahamshukron** [comment]
Thanks for the reply @Cyan4973 !
My assumption was that since each LZ4F block is compressed using LZ4, and LZ4 blocks can be decompress without dynamic memory, and there's no dependency between blocks then it should be possible.

Follow-up question - is there a CLI tool that can lz4-compress a file as single block without any metadata?
I don't see myself writing a compressor program just for this purpose.

If I can't utilize standard tools I'll probably use some other embedded-friendly compression library.

**Comment by Cyan4973** [comment]
A "raw" LZ4 compressed block cannot be decompressed without metadata.
The "metadata" is merely about the size of the compressed block, and the maximum possible size once decompressed.
Whatever the way this information is provided, it can then be decompressed by `liblz4`.

Many `liblz4` users have created their own format to deal with metadata.
That's partly because it's relatively easy to do. But the main issue is that they aren't compatible with each other.
That's the main reason why `lz4frame` was created, so that there is a common format that all tools can agree on and share.

However, `lz4frame` was designed for server or workstation environment.
In contrast, your description of your environment seems very constrained.
As you stated, it "should be possible", yes, but then where is the implementation ?

There are ways to instruct `lz4frame` to use less memory by using advanced parameters, such as `stableSrc` and `stableDst`. But it's unclear if this will prove enough for your specific environment.
