### ISSUE TITLE
original data & decompressed data do not match

### ISSUE THREAD

**Issue by SonalD123** [lz4/lz4#1035]
I'm compressing 32 (to be increased once the data matches) bytes of data while streaming over BLE. Then I'm trying to validate it by decompressing, but only 80% of the data matches. I'm using the example code "simple_buffer.c" on ARM based microcontroller. Please guide.

**Comment by t-mat** [comment]
Hi, @SonalD123

In short, we need minimal reproducible example.

----

For now, honestly, we have no idea about this issue.  If this issue is caused by lz4, definitely we need more details of your issue.

I recommend you to investigate to determine which layer of your project causes this issue.

For example, you can test your (de)compression code with different transmission configuration.

- Local SRAM to local SRAM.
- Flash to SRAM and vice versa.
- Transmit via Flash, SPI, I2C, WiFi, LoRa or USB.

If your code works with other transmission method except BLE, it highly possibly suggests something wrong with your BLE stack/code or interface between your code and BLE module/library.

Otherwise, if all configuration causes same issue, it may be causes lz4 itself or interface between your code and lz4.

Anyway, since the following article at community.arm.com shows LZ4 itself works fine with Cortex-M0 and A,

- [LZ4 decompression routine for Cortex-M0 and later - Architectures and Processors blog - Arm Community blogs - Arm Community](
https://community.arm.com/arm-community-blogs/b/architectures-and-processors-blog/posts/lz4-decompression-routine-for-cortex-m0-and-later)

We can only say that lz4 should be working with any Cortex-M or A.
