### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by pitrou** [lz4/lz4#1037]
A bunch of significant issues were fixed since 1.9.3 was released (such as various sanitizer errors), it would be nice if a 1.9.4 version could be released soon.

**Comment by diizzyy** [comment]
https://github.com/lz4/lz4/pull/972 (CVE-2021-3520) is also probably a good reason

**Comment by Cyan4973** [comment]
We currently plan a new LZ4 release (likely `v1.9.4`) in the medium-term future, before the coming Summer.
It's not more precise because we have a lot of short term priorities to deal with currently.
But this action is definitely planned.

**Comment by stefano2734** [comment]
July 2022 is next door.

**Comment by Cyan4973** [comment]
July looks like a good timeframe for this objective

**Comment by Cyan4973** [comment]
I'm considering entering feature freeze to prepare next release,
meaning the `liblz4` code should not change for a while
leaving time for `ossfuzz` and other continuous long-term testers to find out if there is any issue left in `dev`
before making it officially a release.

During this period, documentation updates, and even code changes to the CLI, test programs or build systems can still be made.

**Comment by stefano2734** [comment]
Thanks for your efforts and great work, and hope for more.
The world needs very good compression of data for more sustainable IT with less physical data machines.

**Comment by Docteh** [comment]
Looks like 1.9.4 is released, August 15th 2022 https://github.com/lz4/lz4/releases/tag/v1.9.4

Just mentioning so the issue submitter gets a note about it.

**Comment by romanek-adam-b2c2** [comment]
The CVE-2021-3520 is almost 1 year old and I spent quite some time trying to figure out if it's fixed already and if so, in which release.

@Cyan4973 could you potentially mention fixing CVE-2021-3520 (https://github.com/advisories/GHSA-gmc7-pqv9-966m) in #972 in the release notes for v1.9.4? Additionally creating a security advisory would be great! Let me please know if I can help somehow.

**Comment by t-mat** [comment]
> I spent quite some time trying to figure out if it's fixed already and if so, in which release.

When you know the commit hash of the PR, you can check it with the following commands:

```sh
cd
git clone https://github.com/lz4/lz4.git lz4-issue-972
cd lz4-issue-972
git tag --contains 8301a21  # Commit hash of https://github.com/lz4/lz4/pull/972/commits
# v1.9.4
```

----

Also, if you need improvement of the document/release note, it would be nice to create a new issue instead of reusing closed one.

**Comment by Cyan4973** [comment]
I don't believe that #972 should have been classified as a `CVE`.
The problem was actually a more boring incorrect usage of the interface
meaning the problem happened on the user side (`lz4jsoncat` in this case).

When one looks at #972, what does it do ?
It checks if the `outputSize` **parameter** is negative.

Now, instructing LZ4 decoder to generate a negative-size output is _obviously_ a programming error.
It's a direct violation of its interface contract, and was treated as "UB" up to #972.
As such, it would be detected and reported in debug mode,
and then considered impossible to happen in production.

There are tons of UB stuff that can happen, all the time.
What happens if the library receives a dangling pointer as output buffer ?
Of course, it's not going to end well,
but the problem is not the library,
the problem is providing a dangling pointer in the first place, aka user side.
What happens if the library is told that the output buffer is `large`, but actually the value is completely wrong and the real size of the buffer is smaller than that, resulting in out-of-buffer write ? Once again, the problem is not the library, the problem is providing a wrong size parameter.
So what happens if this size is so wrong that it's provided as a negative number ?
Once again, the user was supposed to provide a correct size value. This is an out-of-contract situation, aka UB.

What #972 does is extend the interface contract, to also cover the specific scenario of a negative size.
We can certainly discuss what can be the appropriate scope of a contract. Btw, I've accepted to extend it, on the ground that this particular UB scenario is easy to detect, so it's not costly to add it and make it defined instead.
But violating an established contract isn't a `CVE` for the provider of the contract,
it's a CVE for the _user_ of the contract.

One-sidedly deciding to classify an incorrect usage of the interface as a _LZ4_ CVE, let alone a "Critical severity" one (who seriously decides that ??) is a bad twist to this story. I'm not inclined to tacitly approve it by giving some publicity to it.

**Comment by romanek-adam-b2c2** [comment]
Thank you for such an in-depth analysis and explaining your point-of-view.

I'm not here to debate whether it's a vulnerability in lz4 or not (although IMO it's a good practice to check input parameters, especially in library APIs).

The thing is, if you don't do anything this CVE will hang forever and more and more people will be confused. It's probably best to acknowledge the issue and mention the fix in the release notes, or reject the CVE with a proper justification.

**Comment by Cyan4973** [comment]
> or reject the CVE with a proper justification.

Is that even possible ? (and plausible)

**Comment by romanek-adam-b2c2** [comment]
As per [CVE Record Lifecycle](https://www.cve.org/About/Process#CVERecordLifecycle) (see point 6 "Publish" and then expand the "CVE Records" section):
> A CVE Record is associated with one of the following states:
> - Reserved: (...)
> - Published: (...)
> - Rejected: If the CVE ID and associated CVE Record should no longer be used, the CVE Record is placed in the Rejected state. A Rejected CVE Record remains on the CVE List so that users can know when it is invalid.

But I have no idea how to reach this state. Also the CVE was originally raised by RedHat so maybe it's for them to mark as "rejected".

**Comment by Cyan4973** [comment]
Thanks @romanek-adam-b2c2 .
I've reached to Red Hat.
We'll see what happens.
