### ISSUE TITLE
why not providing streaming apis disregarding fetching or recording compressed size,  just like zlib ?

### ISSUE THREAD

**Issue by elftech** [lz4/lz4#1047]
**Is your feature request related to a problem? Please describe.**
When I use lz4 to decompress a large bytes streaming from some unstable source, which is producing discontinuous data chunks, chunks segmented differently from the way  these data was compressed,  it seems required to get a compressed block size firstly, and copy some input chunks and re-joint them to  the origin compressed block size and decompress it, repeating those step one by one to get the stream totally decompressed.

Why lz4 steaming api can't be like zlib streaming api,  seamless apis requiring neither consideration for the compressed block sizes fetching or recording, nor the need for rejoint input chunks in the case as previously describes.

**Describe the solution you'd like**
Streaming api like zlib streaming api. No need for recording and fetching compressed block size in the service code.

**Describe alternatives you've considered**

**Additional context**

**Comment by Cyan4973** [comment]
The `LZ4F_decompress()` API is presumed able to do that.
It's supposed capable to receive data in any chunk size, disregarding exact block boundaries.

While `LZ4F_decompress()` doesn't guarantee that it will be able to consume all `src` input, that's primarily because there might not be enough space available within `dst` buffer.
When that happens, just flush `dst` buffer, then present the rest of the input to `LZ4_decompress()`, and it will consumer more of it.

**Comment by elftech** [comment]
@Cyan4973 , any code snippet showing that? 
The frame api example here records compressed 
 blocks size too. https://github.com/lz4/lz4/blob/dev/examples/frameCompress.c

**Comment by elftech** [comment]
It seems that i have misunderstood the example
