### ISSUE TITLE
i think how to use lz4 api like open write read close？

### ISSUE THREAD

**Issue by anjiahao1** [lz4/lz4#1050]
use lz4_open to set attribute
use lz4_write to compress
use lz4_read to decompress

Will it be easier to use?

**Comment by Cyan4973** [comment]
It seems to assume I/O operations

**Comment by anjiahao1** [comment]
> It seems to assume I/O operations

yes

**Comment by Cyan4973** [comment]
I suspect that any user primarily interested in file / pipe operations will find such entry points convenient.

The issue is essentially a pb of scope.
`lz4.{c,h}` is a fairly low-dependency library, making it easy to port, even in freestanding environments.
Adding `<stdio.h>` would be a pretty big blow to this important property.

Therefore, if such a capability is created, it must be "separated", preserving the low dependency footprint of `liblz4`.
But where should it be then ?
There are a few solutions, each with their pros and cons.

It could be its own separate library, `liblz4io` for example. That would be fine if users link to one or another, or a nuisance if they want to link to both.
It could be included into regular `liblz4`, but remain separated in a different unit, with a separate header.
It could be integrated into `/programs`, as an extractable module, that could be extracted and used in other programs.

Well, there are certainly multiple solutions.
The problem is, it takes time, to consider the pros and cons, select a solution and implement it.
And this is a time budget I can barely afford.

**Comment by anjiahao1** [comment]
> 

thx u for u reply，i use lz4 on nuttx， it’s a posix real time system. if add file options,it will be easy to use lz4. I did it. I will upload my code later. I hope you can put forward modification suggestions. But this may need to be after the Spring Festival holiday
