### ISSUE TITLE
Implement LZ4_FREESTANDING

### ISSUE THREAD

**Issue by Cyan4973** [lz4/lz4#1071]
Suggested by @t-mat  in  : 
https://github.com/lz4/lz4/pull/1068#issuecomment-1060814983

**Comment by t-mat** [comment]
I've written simple sample of `-nostdlib` program for Linux.
https://gist.github.com/t-mat/aa78ff79f31ee79c4a709d4def3ee1d7

I think our next steps are

(1) Think about other platforms.  Do we need similar `-nostdlib` program for macos/win32/BSDs/etc?  How about CI tests?

(2) Which standard C function(s) will be needed by the `LZ4_FREESTANDING` test program?
Perhaps we should write our test program first.  And after that we can think about our needs for standard functions easily.

**Comment by Cyan4973** [comment]
Freestanding, i.e. no dependency on any standard C library function, is a real use case, but it's difficult to clearly articulate, because it's more a collection of niche use cases.

I generally don't see the point of Freestanding in a situation where a fully-fledged OS is available, hence wouldn't consider  `macos`, `win32`, `linux`, `BSD`, etc. as valid targets.
It's more for very limited systems with a layer barely worthy of being called an OS, so it's more the territory of "internet of things", from which I already exclude things like smart watches for example, which are already too complex.

I think `liblz4` has a very narrow surface when it comes to C standard lib dependency. Essentially, `malloc`, `free`, and `memcpy`. Probably `memset` and `calloc`. Maybe `realloc`.
*edit* : nope, `realloc` is only for the CLI, not the library.

So that's the API surface that any freestanding environment must provide for a freestanding `liblz4` to work.

Ah, and I should add: in the context of freestanding environment, I would only expect static linking.

**Comment by Cyan4973** [comment]
Question :
should we try to make this topic an item for `v1.9.4` release ?

**Comment by t-mat** [comment]
I think we can simply skip this `LZ4_FREESTANDING` for new release.  Because we don't see any urgent demand for it.
I believe all project maintainers who may like this feature already managed their situation properly.

But we may need to some remark for `LZ4F_*` and its requirement of `<stdio.h>` though.

**Comment by t-mat** [comment]
I wrote new -nostdlib harness for Linux platforms.
https://gist.github.com/t-mat/dbdc4f71ae52f4eca83fd67f683e7452

Now it #includes the following file and can be compiled with `-nostdlib`.

- lz4.c
- lz4hc.c
- lz4frame.c
- xxhash.c

Compilation:

```
cd
git clone https://github.com/lz4/lz4.git lz4-freestanding
cd lz4-freestanding
cd tests
mkdir freestanding
cd    freestanding
curl -JOL https://gist.githubusercontent.com/t-mat/dbdc4f71ae52f4eca83fd67f683e7452/raw/87ed7c95280abfea2f496087b5c4a11c09b86dc8/lz4-freestanding-harness-v0.0.2.c
curl -JOL https://raw.githubusercontent.com/charlesnicholson/nanoprintf/main/nanoprintf.h
gcc -nostdlib lz4-freestanding-harness-v0.0.2.c
./a.out
```

**Comment by t-mat** [comment]
I think next steps are
- Write minimum -nostdlib harness for each library (lz4, lz4hc, lz4frame)
  - lz4-freestanding, lz4hc-freestanding, lz4frame-freestanding
  - It must #define proper "freestanding-ish" options.  E.g. `LZ4_USER_MEMORY_FUNCTIONS`
- Add test code for each library.
  - It should achieve good coverage rate for each library.  But low coverage may be okay for now.

Let me know if you find better approach or missing steps.

**Comment by Cyan4973** [comment]
This plan looks good to me

**Comment by t-mat** [comment]
I'm experimenting in pseudo freestanding environment.  And I think we need the following additional functionality to support them nicely.

## Allow library user to define their own `LZ4_mem*()` macros

The following rules and new macros will allow library user to define their own `LZ4_mem*()` macros.  

  - Always use `LZ4_memcpy()` instead of `memcpy()`.
  - Always use `LZ4_memmove()` instead of `memmove()`.
  - Always use `LZ4_memset()` instead of `memset()`.
  - Define these macros if library user doesn't define them.

With these macro, we can provide truly "freestanding" code.


## Introduce new compile time option which disables LZ4/HC memory allocation functions

Introduce new compile time option symbol `LZ4_STATIC_LINKING_ONLY_DISABLE_MEMORY_ALLOCATION` which disables LZ4/HC memory allocation functions.

  - It disables the following functions which need memory allocation in outside of the stack.

```
LZ4_createStream
LZ4_freeStream
LZ4_createStreamDecode
LZ4_freeStreamDecode
LZ4_create              // legacy

LZ4_createStreamHC(void)
LZ4_freeStreamHC
LZ4_createHC            // legacy
LZ4_freeHC              // legacy
```

  - This functionality may help users who want to use lz4 in small scale freestanding environment (e.g. micro contollers).
  - Yes, `void* LZ4_malloc(size_t s) { return NULL; }` may provide similar result.  But I think it's too rude 😞 
  - Since it breaks (disables) API, we don't provide it as a generic library.

----

If introducing these functionalities are okay, I'll send independent PR for them.

**Comment by t-mat** [comment]
With #1123 and #1124, we will be able to write freestanding code like this:

```C
#define LZ4_HEAPMODE 0
#define LZ4HC_HEAPMODE 0
#define LZ4_STATIC_LINKING_ONLY_DISABLE_MEMORY_ALLOCATION 1 /* #1124 */
#define LZ4_memcpy  MY_ENV_memcpy  /* #1123 */
#define LZ4_memset  MY_ENV_memset  /* #1123 */
#define LZ4_memmove MY_ENV_memmove /* #1123 */

static inline void* MY_ENV_memmove(void *dst, const void *src, size_t n) { ... }
static inline void* MY_ENV_memcpy(void * restrict dst, const void * restrict src, size_t n) { ... }
static inline void* MY_ENV_memset(void *s, int c, size_t n) { ... }

#include "lib/lz4.c"
#include "lib/lz4hc.c"
```

**Comment by t-mat** [comment]
Now, I think we can easily implement `LZ4_FREESTANDING` in `lz4.h`.

```C
/* lz4.h */
#if defined(LZ4_FREESTANDING) && (LZ4_FREESTANDING)
#  define LZ4_HEAPMODE 0
#  define LZ4HC_HEAPMODE 0
#  define LZ4_STATIC_LINKING_ONLY_DISABLE_MEMORY_ALLOCATION 1
#  if !defined(LZ4_memcpy)
#    error LZ4_FREESTANDING requires #define of LZ4_memcpy.
#  endif
#  if !defined(LZ4_memset)
#    error LZ4_FREESTANDING requires #define of LZ4_memset.
#  endif
#  if !defined(LZ4_memmove)
#    error LZ4_FREESTANDING requires #define of LZ4_memmove.
#  endif
#endif /* defined(LZ4_FREESTANDING) && (LZ4_FREESTANDING) */
```

Freestanding app may look like this

```C
/* my-freestanding-app.c */
#define LZ4_FREESTANDING 1
#define LZ4_memcpy  MY_memcpy
#define LZ4_memset  MY_memset
#define LZ4_memmove MY_memmove

static inline void* MY_memmove(void *dst, const void *src, size_t n) {
    uint8_t* d = dst;
    const uint8_t* s = src;

    if(d > s) {
        d += n;
        s += n;
        while(n--) {
            *--d = *--s;
        }
    } else {
        while(n--) {
            *d++ = *s++;
        }
    }
    return dst;
}

static inline void* MY_memcpy(void * restrict dst, const void * restrict src, size_t n) {
    return MY_memmove(dst, src, n);
}

static inline void* MY_memset(void *s, int c, size_t n) {
    uint8_t* p = s;
    while(n--) {
        *p++ = (uint8_t) c;
    }
    return s;
}

#include "path/to/lz4-repo/lib/lz4.c"
#include "path/to/lz4-repo/lib/lz4hc.c"
```

If above definition of `LZ4_FREESTANDING` looks good, I'll send a PR.

After that, I'll send a complete example/test of `LZ4_FREESTANDING` for Linux environment (our standard test).

**Comment by t-mat** [comment]
- [x] TODO : `LZ4_FREESTANDING` and `LZ4_STATIC_LINKING_ONLY_DISABLE_MEMORY_ALLOCATION` should be documented in lz4/lib/README.md
  - https://github.com/lz4/lz4/pull/1129#issuecomment-1207222890

**Comment by Cyan4973** [comment]
This looks good to me!
