### ISSUE TITLE
Is '&' correct here?

### ISSUE THREAD

**Issue by bluenlive** [lz4/lz4#1072]
I think following line should be corrected to 
`(ip>anchor) && (match > lowLimit)`

Is it a code that has other purposes?

https://github.com/lz4/lz4/blob/4c9431e9af596af0556e5da0ae99305bafb2b10b/lib/lz4.c#L1030

**Comment by Cyan4973** [comment]
Yes,
it ensures that there is no branch.

Some compilers may be able to understand that there is no need for a branch here, and could optimize it,
but others may not.

Writing a `&` instead of `&&` forces the evaluation as a binary arithmetic operation.

In this case, both are equivalent, because both sides of the `&` are necessarily 0/1 expressions.
