### ISSUE TITLE
What does `ERROR_GENERIC` mean?

### ISSUE THREAD

**Issue by jmg-duarte** [lz4/lz4#1074]
Hello everyone,

Sorry if this isn't quite an issue but since the repo does not have a discussions page I don't know where else to post.
I'm currently dealing with some files that fail to decompress with ERROR_GENERIC (code 66) and I have no clue what might be causing it or what it means.

Sadly, I cannot share the file, I've been trying to reproduce the issue to no avail either so, the only thing I have left is to ask the experts the reason behind the error.

For more context I'm doing the following:
- From machine X
  - I have a Python virtual environment folder which I package using Python tar module
  - I then compress the file using `python-lz4`
  - Upload it to Azure
- From machine Y
  - Download the file
  - Decompress (fails here)

**Comment by Cyan4973** [comment]
`ERROR_GENERIC` is a place holder to return an error without being specific.
There are only few of them left in the code, and generally deal with situations that should not happen, or are out of control of `lz4frame`.

You may want to update your local version of `lz4` to latest `dev` branch for tests, as there are less `ERROR_GENERIC` there.
What I would expect is that you'll get instead a "decompression failed" error, which is hardly specific, but still more than "generic".

This in turn would point to data corruption, making it impossible to decode.

But, since data was compressed just before by `python-lz4`, it now points at an incompatibility between `python-lz4` and what you use to decompress it. I'll assume it's the `lz4` CLI, but it could so many other ways.

A very classical issue could be  using the `block` format on one side, and expecting the `frame` format on the other one.
But that should have triggered a different error code.
So it's likely more subtle.

**Comment by jmg-duarte** [comment]
> But, since data was compressed just before by python-lz4, it now points at an incompatibility between python-lz4 and what you use to decompress it. I'll assume it's the lz4 CLI, but it could so many other ways.

I've decompressed with `python-lz4`, this prompted https://github.com/python-lz4/python-lz4/issues/247; I used `unlz4` and `lz4 -t` as tests and both issued the error (now with the error code 66).

> A very classical issue could be using the block format on one side, and expecting the frame format on the other one.

I'm using `frame` on both sides, unless `python-lz4` is doing something weird behind the scenes I have no reason to believe it is the cause.

Could it be due to different compression levels? 
I've noticed that https://github.com/lz4/lz4/issues/560 discusses error 66 too, although it has a different message.

**Comment by Cyan4973** [comment]
"Error 66" is specific to `lz4` CLI, and simply means that `LZ4F_decompress()` failed and returned an error code.
Then, `lz4frame` provides its own error code, so that's where it becomes something a bit more specific, displaying `ERROR_GENERIC` or `ERROR_decompressionFailed` or `ERROR_allocation_failed`, etc.

#560 is indeed completely unrelated.

If I understand your statement correctly, `python-lz4` is used to compress, and then, when used to decompress, fails too?

**Comment by jmg-duarte** [comment]
> "Error 66" is specific to lz4 CLI, and simply means that LZ4F_decompress() failed and returned an error code.

Ah ok, thank you for the explanation!

> If I understand your statement correctly, python-lz4 is used to compress, and then, when used to decompress, fails too?

Compression does not yield any errors, when decompressing the file it does, with `ERROR_GENERIC`.
I've tried to replicate the error but I've had no luck.

Is there some diagnose tool I can run over the file to try and get a better understanding of what might be going on?

**Comment by felixhandte** [comment]
Is it possible you are incorrectly serializing the data? If it successfully decompresses in the same python environment, but not after you've written it out to a file, that makes me suspect mishandling of non-ASCII bytes in the output.

**Comment by jmg-duarte** [comment]
> Is it possible you are incorrectly serializing the data? If it successfully decompresses in the same python environment, but not after you've written it out to a file, that makes me suspect mishandling of non-ASCII bytes in the output.

It does not decompress, at all. The flow is as follows:

> - From machine X
>     - I have a Python virtual environment folder which I package using Python tar module
>     - I then compress the file using python-lz4
>     - Upload it to Azure
> - From machine Y
>     - Download the file
>     - Decompress (fails here)

According to Azure Blob Storage Client Python documentation, the default encoding is UTF-8 and I don't change any encoding. 

Here's the code in question:

```py
def _upload_venv(blob_client: BlobClient, venv_path: Path) -> None:
    venv_tar = BytesIO()
    with tarfile.open(fileobj=venv_tar, mode="w") as tar:
        tar.add(venv_path, recursive=True)
    venv_tar_lz4 = compress(venv_tar.getvalue()) # LZ4
    blob_client.upload_blob(venv_tar_lz4, overwrite=True)

def _download_venv(blob_client: BlobClient) -> None:
    venv_tar_lz4 = blob_client.download_blob().readall()
    venv_tar = BytesIO(decompress(venv_tar_lz4)) # LZ4
    with tarfile.open(fileobj=venv_tar) as tar:
        tar.extractall()
```

**Comment by Cyan4973** [comment]
Closing, there is no more any `ERROR_GENERIC` in the "regular" `liblz4` library (`dev` branch).
