### ISSUE TITLE
Add idiomatic lz4frame decompressor to examples

### ISSUE THREAD

**Issue by t-mat** [lz4/lz4#108]
@Cyan4973,
Since there is no example code for LZ4F, I've created initial version of "Idiomatic lz4frame decompressor"
- https://gist.github.com/t-mat/c47868a00c60f93682d8

During writing this code, I have some questions and record these questions as comment which is beginning with `!!!`.  My questions are
- Need some "safe" LZ4F error code value/symbols in `lz4_frame.h`
- Is 64KiB recommended source buffer size ?
- Should we use `LZ4F_getFrameInfo()` to determine "best" destination buffer size, or just always allocate 64KiB ?
  - Need public version of `LZ4F_getBlockSize()` to allocate "best" destination buffer
- Finally, is this sufficiently "idiomatic" ?

@funcodeio, since this PR is somewhat related #106 and you have enough knowledge and experience of all part of LZ4, could you also review this code ?

**Comment by Cyan4973** [comment]
Thanks for this very good suggestion Takayuki.

Answering your points : 

> // !!!  I want to see generic success/fail code in lz4_frame.h.
> // Currently, only lz4frame_static.h has LZ4F_OK_NoError and LZ4F_ERROR_GENERIC.

Fair point. It shall be added.


> // !!!  64KiB is LZ4IO_dBufferSize in programs/lz4io.c.
> // Is this a "recommended" src buffer size ?

Yes, 
there is no obligation, lz4frame will work with any src buffer size,
but it looks a "sane" setting, especially when block size is 64 KB.


>    // !!!  Should I use LZ4F_getFrameInfo() or just a set constant 64KiB
>    // like LZ4IO_createDResources() ?

Answering this one is tricky.
Both methods are supported and work fine.
Which one is better, I'm not sure. It probably depends on local restrictions.
Having a dstSize == blockSize is supposed to reduce memory copy operations (less buffer needed).
But it won't help memory allocation pressure. So, sometimes, it's just best to allocate only 64KB,
and suffer memory copy operations.

> // !!!  Is there any chance to see LZ4F_getBlockSize() in public header ?

I was initially surprised, as `LZ4F_getFrameInfo()` already provide this information.
But it does so using "human readable" enums. It's not a `size_t` field immediately usable for allocation.
So your request is for such a translator. Fair enough.


> // Perhaps, more abstract and coherence interface
> //      size_t LZ4F_getBlockSizeFromFrameInfo(const LZ4F_frameInfo_t*);

Yes.


> Finally, is this sufficiently "idiomatic" ?

I guess so.

Unfortunately, I'm not in best position to judge that point.
I tend to know "too much" from lz4frame internal working.
Consequently, I don't see well enough its shortcomings.
I find it better to judge such property from feedback.
If there are questions, it means something is not clear enough, and must be improved.

**Comment by funcodeio** [comment]
Great work.
It looks good to me except for one thing.

For unfinished stream, it is possible for the code to loop infinitely.
I will send you an example to your email.

**Comment by funcodeio** [comment]
Since I could not find your email address, I uploaded it in dropbox.

Here is the link.
https://www.dropbox.com/s/znwa9tfulq6c43q/no_end_mark.lz4?dl=0

**Comment by t-mat** [comment]
Thanks for reviews !

> Also, could you describe the objective ?

Generic success / error code help to make some kind of defensive coding easier.  Suppose implementating thin LZ4F wrapper in C++

```
LZ4F_errorCode_t my_LZ4F_createDecompressionContext(
    LZ4F_decompressionContext_t* dctxPtr, unsigned version)
{
    LZ4F_errorCode_t result = LZ4F_ERROR_GENERIC;   ///< (A)
    try {
        ...
        result = LZ4F_createCompressionContext2(dctxPtr, version);
        ...
    } catch(std::exception& e) {
        ...
        result = LZ4F_ERROR_GENERIC; ///< (B)
        ...
    }
    return result;
}
```

 - (A) is redundant initial value, but there are some coding rules such as "You must always set initial value" which makes this (defensive) redundant code.
 - (B) is error code of exception.


> Is it to generate some error code compatible with LZ4F_isError() ?

Yes.  But generic error code just reports "something wrong".


> In which case, is it really the better solution, and if yes why ?

Of course, serious project must define its own error code and struct.  Also must not depend on external libraries.  But since LZ4 is relatively simple and small, supporting lightweight solution would be nice.


> Which one is better, I'm not sure. It probably depends on local restrictions.

Okay.  So I add "benchmark is needed" to my TODOs :memo:   I'll benchmark it on Core i7 PC and Raspberry Pi2.  If 64KiB constant buffer size would not suffer anything worse in both platform, I'll choose 64KiB.


> For unfinished stream, it is possible for the code to loop infinitely.

Thanks !  I'll fix it with your data.

BTW, you could see my email address in git commit log by the following command :

```
git log | grep "Author" | sort | uniq
```

**Comment by t-mat** [comment]
I've done [my benchmark](https://gist.github.com/t-mat/b8cf023b29983d511a7d).  Here is a result :

|Platform	|dstBuf=64KiB	|dstBuf=auto	|64K/auto	|
|----		|----		|----		|----		|
|Windows7 (x64)	|0.130		|0.125		|1.037		|
|RaspberryPi2	|0.644		|0.618		|1.043		|
|Ubuntu (x64)	|0.256		|0.242		|1.056		|

Constant 64KiB dstBufSize is 3..6% worse than dynamic buffer size.  Generally, bigger is better as @Cyan4973 said.  Since it's an example code for beginners, I choose constant 64KiB dstBuf size for this example.

I also created new branch [`issue/108`](https://github.com/t-mat/lz4/tree/issue/108) to prepare PR.

@funcodeio , I've added [EOF check](https://github.com/t-mat/lz4/commit/08a2a2d379de59d6c5fb9c2241b64f03bc49c3d5#diff-643b6598f26df64f4f9bddc2a5a0032bR68) to the decompression loop.  Is this enough error checking ?

**Comment by funcodeio** [comment]
I believe your way to check EOF is correct.
Overall code looks good to me.
Although I generated a tons of random inputs, and tested, you program works properly. 

Great work!

**Comment by t-mat** [comment]
Thanks for the review, @funcodeio !

**Comment by Cyan4973** [comment]
Is @t-mat issue/108 branch ready for a pull request ?

**Comment by t-mat** [comment]
I'm late !

I think issue/108 is okayish, it works but it isn't coherent enough with @keszybz's #118 & #122.  I believe such difference will cause confusion for beginners.
Since #122 is already merged, I would like to change my code which will be symmetric with #122.

**Comment by Cyan4973** [comment]
Sure ! No problem, you can take time to make it as you wish

**Comment by t-mat** [comment]
I have some questions about #122.

### Dependency definition in examples/Makefile

There are two kind of dependency definitions.  [Explicit source file](https://github.com/Cyan4973/lz4/blob/r131/examples/Makefile#L53) and [local liblz4](https://github.com/Cyan4973/lz4/blob/r131/examples/Makefile#L68).  Which should I use ?

### Initialisation of `LZ4F_preferences_t`

 #122 employed [static initialisation method](https://github.com/Cyan4973/lz4/blob/r131/examples/frameCompress.c#L15).  And I think another popular initialisation method is dynamic one:

```
void my_func()
{
    LZ4F_preferences_t lz4_preferences;
    memset(&lz4_preferences, 0, sizeof(lz4_preferences));
    lz4_preferences.frameInfo.blockSizeID = LZ4F_max256KB;
    lz4_preferences.frameInfo.blockMode = LZ4F_blockLinked;
    ...
}
```

Static initialisation has

 - Pros
    - Compact.  There are no initialisation code.
    - Safe.  `const` provides additional error checking by complier and OS.
 - Cons
    - Cryptic.  Since members are relatively many and structres are nested, it looks just a bit cryptic.  But additional comment will resolve this problem.
    - Less future compatibility.  Explicit initialisation for `reserved[]` variables may cause some error in the future.  We can avoid this problem by changing some compiler options.

Dynamic initialisation's pros and cons are opposite.  Pros: Less cryptic and more future compatibility.  Cons: Redundant, verbose and less safe.

Which should I use ?


### Compression buffer size calculation

  1. Since `LZ4F_compressBound()` includes `frameEnd` (EndMark and content checksum), it seems [adding `LZ4F_FOOTER_SIZE` to `size`](https://github.com/Cyan4973/lz4/blob/r131/examples/frameCompress.c#L42) is redundant.  Is it right ?
  2. Should we define [`LZ4_HEADER_SIZE`](https://github.com/Cyan4973/lz4/blob/r131/examples/frameCompress.c#L12) in user code and add it to `size` ?
  3. Is `LZ4F_compressFrameBound()` better choice in [this case](https://github.com/Cyan4973/lz4/blob/r131/examples/frameCompress.c#L42) ?

**Comment by keszybz** [comment]
On Tue, Jun 30, 2015 at 07:01:47AM -0700, Takayuki MATSUOKA wrote:
> I have some questions about #122.
> 
> ### Dependency definition in examples/Makefile
> 
> There are two kind of dependency definitions.  [Explicit source file](https://github.com/Cyan4973/lz4/blob/r131/examples/Makefile#L53) and [local liblz4](https://github.com/Cyan4973/lz4/blob/r131/examples/Makefile#L68).  Which should I use ?

One is for files in the same directory, the other for files in a different directory.

> 
> ### Initialisation of `LZ4F_preferences_t`
> 
>  #122 employed [static initialisation method](https://github.com/Cyan4973/lz4/blob/r131/examples/frameCompress.c#L15).  And I think another popular initialisation method is dynamic one:
> 
> ```
> void my_func()
> {
>     LZ4F_preferences_t lz4_preferences;
>     memset(&lz4_preferences, 0, sizeof(lz4_preferences));
>     lz4_preferences.frameInfo.blockSizeID = LZ4F_max256KB;
>     lz4_preferences.frameInfo.blockMode = LZ4F_blockLinked;
>     ...
> }
> ```
> 
> Static initialisation has
> 
>  - Pros
>     - Compact.  There are no initialisation code.
>     - Safe.  `const` provides additional error checking by complier and OS.
>  - Cons
>     - Cryptic.  Since members are relatively many and structres are nested, it looks just a bit cryptic.  But additional comment will resolve this problem.

There's on more cons on the "dynamic" side:
unless the compiler optimizes the call to memset out, there is an extra call.
If the compiler does optimize it out, then debugging is more confusing,
because a call that was there suddently isn't.

Static initialization is better in pretty much every regard,
if named intializers are used:
  .field = value;
I think it would be good to reconsider using them.

>     - Less future compatibility.  Explicit initialisation for `reserved[]` variables may cause some error in the future.  We can avoid this problem by changing some compiler options.
> 
> Dynamic initialisation's pros and cons are opposite.  Pros: Less cryptic and more future compatibility.  Cons: Redundant, verbose and less safe.
> 
> Which should I use ?
> 
> 
> ### Compression buffer size calculation
> 
>   1. Since `LZ4F_compressBound()` includes `frameEnd` (EndMark and content checksum), it seems [adding `LZ4F_FOOTER_SIZE` to `size`](https://github.com/Cyan4973/lz4/blob/r131/examples/frameCompress.c#L42) is redundant.  Is it right ?
Ah, good point.

>   2. Should we define [`LZ4_HEADER_SIZE`](https://github.com/Cyan4973/lz4/blob/r131/examples/frameCompress.c#L12) in user code and add it to `size` ?
It would probably be better to expose this from lz4.h.

>   3. Is `LZ4F_compressFrameBound()` better choice in [this case](https://github.com/Cyan4973/lz4/blob/r131/examples/frameCompress.c#L42) ?

**Comment by Cyan4973** [comment]
@t-mat : just a complement to already fine answer of @keszybz  : 

> Initialisation of LZ4F_preferences_t

I tend to prefer static allocation, because I feel it's easier to read and maintain.
Name initializers are indeed very good for readability.
Unfortunately, I believe this feature is only available on C99+ compilers.

> Cryptic. Since members are relatively many and structres are nested, it looks just a bit cryptic. But additional comment will resolve this problem.

In which case, I'll add necessary comments in the hope to make its usage easier. Please feel free to propose changes if you feel it would be better.

> Less future compatibility. Explicit initialisation for reserved[] variables may cause some error in the future. 

`reserved[]` variables are intended to give some room to add future extensions without breaking ABI. and it has already proven useful...

Regarding initialization to zero : my understanding of the C standard is that as soon as one member of the structure is initialized, all others are initialized to zero by default (if not mentioned). That's why a `{0}` is equivalent to a full init to zero. I believe this is good enough to trust the C standard.
In order to *not* have `reserved[]` fields to zero, one has to either provide a completely uninitialized `LZ4F_preferences_t` structure, or to explicitly initialize some `reserved[]` fields to something else than `0`. Both cases are blatant API misusage. 

> Is LZ4F_compressFrameBound() better choice in this case ?

Yes, for this case, I believe this would be the better choice.
`LZ4F_compressFrameBound()` specifically includes footer and header sizes.

> Since LZ4F_compressBound() includes frameEnd (EndMark and content checksum), it seems adding LZ4F_FOOTER_SIZE to size is redundant. Is it right ?

Currently `LZ4F_compressBound()` includes "footer" size (end of frame fields). I believe that's because in case of a final flush with `LZ4F_compressEnd()`, it's possible to output both a compressed block _and_ the frame endmark.

Since the objective of `LZ4F_compressBound()` is to help the user program to allocate the right amount of memory for destination buffer, I thought that it would be a pity to allocate a buffer which could potentially trigger a memory overflow during this final call.

While the use case for `LZ4F_compressBound()` seems clear, the downside is that what it contains (the frame endMark, but not the frame header) seems unclear.

I'm now wondering if another function `LZ4F_compressBlockBound()` would help. It would be more explicit that it only handles maximum compressed size of one block, hence excluding frame header and footer.

**Comment by markos** [comment]
hi all, I'm sorry if this is the wrong place to ask this question, but this is the most relevant discussion to that I have found online to what I'm looking for. Basically, I'm trying to use LZ4F_getFrameInfo() *before* LZ4F_decompress() to know the LZ4F_frameInfo_t.contentSize so that I can preallocate the decompression buffer. Is this actually possible or do I have to actually decompress first?

**Comment by markos** [comment]
actually nevermind, I found that using --content-size in the lz4 cmd line tool it does exactly what I want without calling LZ4F_decompress()! Thanks!

**Comment by Cyan4973** [comment]
Hi Markos

Yes. `LZ4F_getFrameInfo()` is supposed to answer this information.
It still needs sufficient `src` data to decode the entire header.
The maximum size of frame header being 15 bytes, you could start with that.

Regards
