### ISSUE TITLE
implement LZ4F_resetCompressionContext

### ISSUE THREAD

**Issue by xiaoyong-z** [lz4/lz4#1091]
I am currently reusing the `LZ4F_compressionContext_t` and `LZ4F_decompressionContext_t` for many times compressions and decompressions. 

And I find that, in lz4, there is a `LZ4F_resetDecompressionContext` api which can allows me to easily reuse the `LZ4F_decompressionContext_t` decompression context. 

But there is no `LZ4F_resetCompressionContext` for `LZ4F_compressionContext_t` compression context. 
I would like to know why `LZ4F_resetCompressionContext`  is not available. Is it necessary to add this api ?

**Comment by Cyan4973** [comment]
I don't remember exactly.
What I'm certain of is that, after completing compression with a `LZ4F_compressionContext_t` object, 
the object can be re-used to make another streaming compression.
Hence there is no need to "reset", it's implicitly valid.

However, I don't think that the object is currently able to recover from a failed state.
So if anything "wrong" happens during compression, or if previous compression is not completed, the only valid method is to de-allocate and re-allocate a new compressionContext object.

In order to add a `reset` capability, it would be necessary to ensure that it can be done safely even after a compression failure. *any* compression failure.

This is likely doable, but requires time, testing, etc.. And time is unfortunately the most scarce resource there is.

**Comment by xiaoyong-z** [comment]
I get it, thanks for the answer!
