### ISSUE TITLE
Improve licensing terms/contributions/contributors informations

### ISSUE THREAD

**Issue by tokiclover** [lz4/lz4#115]
Following PR #114 and @t-mat suggestion on opening an issue ticket for a suggestion to improve licensing terms/contributions/contributors clarity, and simplify sub/same-license per contribution.

Please consider this suggestion to use a simple approach, meaning using `COPYING.{BSD-2-clause,GPLv2}` (or simplly `COPYING.BSD-2`) files addition and usage of dedicated header in files for authors/contributors and addition of `AUTHORS` file for the main/noticeable/regular contributors per contribution e.g.

**AUTHORS:**

```
Copyright (c) 2012-2015 Yann Collet <email@address.email>
Copyright (c) 2015 Takayuki MATSUOKA <email@adress.email> for contrib/examples
[....]
```

**HEADER (per file):**

```
/*
 * Copyright (c) 2012-2015 Yann Collet <email@address.email>
 * Distributed under the 2-clause BSD license.
 */
```

Or a more verbose header variant...

**Comment by tokiclover** [comment]
As a side note, github has already those license template... so tricking a web-ui new file addition would create a nice license template for custom usage!

**Comment by t-mat** [comment]
First of all, I would like to point out minor issue.  Since there are "no license" files (e.g. cmake_unofficial/CMakeLists.txt, Visual Studio solution files, etc), we need more detailed license section in README or somewhere.  For example, [Snappy's COPYING](https://github.com/google/snappy/blob/master/COPYING) and [xz's COPYING](http://git.tukaani.org/?p=xz.git;a=blob;f=COPYING;hb=HEAD) file has detailed description of each part of the code and its license.

Next, I'm still not sure either long nor short one is better.  So, I've quick look at other projects.  It seems long license statement is popular, but there are no project which has license file in each directory.

 - Long header : The following projects' each source code has "usual" license statement
   - LZO (GPLv2)
   - Snappy (New BSD) : [snappy.cc](https://github.com/google/snappy/blob/master/snappy.cc)
   - gzip (GPLv3) : [gzip.c](http://git.savannah.gnu.org/cgit/gzip.git/tree/gzip.c)
   - xz (Public Domain/LGPLv2/GPLv2,v3) : [xz.c](http://git.tukaani.org/?p=xz.git;a=blob;f=src/xz/main.c;hb=HEAD)
      - xz's [COPYING](http://git.tukaani.org/?p=xz.git;a=blob;f=COPYING;hb=HEAD) file has detailed description of each part of the code and its license.
 - Short header
   - zlib library (zlib).  But zlib's contrib/ directory has various license statements and styles.

Also, since LZ4 is highly embeddable, long license description per file would be nice to allow direct copying only "lz4.c/h" for the other project such as [Linux kernel's lib/lz4/](https://github.com/torvalds/linux/tree/master/lib/lz4).
But some part of LZ4 already has short description such as files in examples/ and these simplicities are good for its purpose.

So I would like to decouple core part (lib/ and programs/) and others.  While leave core part for now, I'd continue discussing latter part.

> Many projects use this approach to ease life on the licensing terms and maintain AUTHORS file and headers instead.

@tokiclover, could you show us an example project ?

**Comment by tokiclover** [comment]
I was going to re-check [FFmpeg][1] repository... but this project is very big with numerous cumbersome licensing terms; the maintainers file is already quite rich. See this for an easy starting point [EDI][2] (EFL based IDE currently in development.)

Actually [Enlightenment][3] (repository over [there][4]) DE is almost licensed under 2-clause BSD with a few [L]GPLv[23] exceptions. The AUTHORS file use often a single line when necessary terminated with *and others* which refer to the contributors who had their name in headers. Peculiar/odd terms can be found in sub-directories with the source files when necessary(/required in this case.) (I cannot remember in which (sub-)project of E I saw this.)

[2]: https://github.com/ajwillia-ms/edi
[1]: https://git.videolan.org/?p=ffmpeg.git;a=summary
[3]: https://www.enlightenment.org/
[4]: https://git.enlightenment.org/

**Comment by t-mat** [comment]
Thanks @tokiclover.  I understand AUTHORS and COPYING.* files.

But, I'm not sure about your "HEADER" style.  There are no files which uses your short HEADER description in your referece projects.  Could you show us any project which uses your HEADER style ?

Since [@Cyan4973 concerns about confusions](https://github.com/Cyan4973/lz4/pull/114#issuecomment-106779785), I hope we'll collect enough information (style, popularity, etc.) and discuss about your proposal.

**Comment by tokiclover** [comment]
You're welcome @t-mat. Really, it's nothing.

As you already pretty said it yourself previously, *short* or *long* header is up to the authors and their liking.
It's more common to encounter short variant with small projects, bigger projects tend to use long variant. And this is understandable with the numerous contributors (authorship, maintainership, and small contribution commited by the maintainer with the name of the contributors only mentioned on the commit message.)

Small projects tend to use a short variant because the main contributor is often... the author with small contribution coming from here and there. So, the AUTHORS almost list all the contributors.

Still it's difficult to draw a clean line here... So, I guess it's up to the preferences of the authors/contributors.
And the long variant header is everywhere from (Linux) kernel to... tiny projects (which can be reduced to tiny scripts.)

[Reference][1] for a short header variant. Look at `sh/` directory for a quick glance. I do not remember the header style of `*.{c,h}` files.

[1]: https://github.com/OpenRC/openrc

**Comment by Cyan4973** [comment]
Latest update in `dev` branch tries to provide some more license information, 
in the hope to improve clarity.
