### ISSUE TITLE
[performance](lz4f) why LZ4F_compressEnd set maxBufferSize=0 

### ISSUE THREAD

**Issue by yixiutt** [lz4/lz4#1157]
I use a global LZ4F_cctx  and i found that LZ4F_compressEnd set maxBufferSize=0 so in LZ4F_compressBegin, tmpBuffer buffer will be free and calloc a new memory。
Why tmpBuffer cannot be reused in LZ4F_cctx?

**Comment by Cyan4973** [comment]
Indeed,

this change was made in https://github.com/lz4/lz4/pull/236,
in order to fix https://github.com/lz4/lz4/issues/232,
an unspecified bug in the fuzzer.

I must admit that I don't quite follow the relation.
The original intention was to re-use the buffer,
but somehow, forcing `maxBufferSize=0` seems to have fixed _something_,
though I have difficulties to link the problem and the solution.

Anyway, worth an investigation...

**Comment by yixiutt** [comment]
OK, I will delete `maxBufferSize=0` and test in my case. I'll let you know if I make some progress

**Comment by Cyan4973** [comment]
I also don't quite understand why `calloc()` is used for `tmpBuffer`,
given the use case for this buffer, I would have expected `malloc()` to be sufficient.

Conjecture : it may have been a case of silencing `msan`. 
In which case, I don't think it was the right fix ...

**Comment by yixiutt** [comment]
I agree with u

**Comment by yixiutt** [comment]
tmpBuffer may not need to load into physical memory cause tmp buffer always bigger than actual use, so calloc here would cause a lot page fault than expected

**Comment by Cyan4973** [comment]
Fixed in #1158
