### ISSUE TITLE
--test failure

### ISSUE THREAD

**Issue by patch-work** [lz4/lz4#1164]
The option "--test" fails when applied to multiple input files (command: lz4 -m -t *.lz4 ): instead of testing the integrity of compressed .lz4 files in RAM, it decompresses them on disk.

Addenda

```
> dnf info lz4
Last metadata expiration check: 0:00:50 ago on Wed Sep 14 16:57:33 2022.
Installed Packages
Name         : lz4
Version      : 1.9.3
Release      : 4.fc36
Architecture : x86_64
Size         : 113 k
Source       : lz4-1.9.3-4.fc36.src.rpm
Repository   : @System
From repo    : fedora
Summary      : Extremely fast compression algorithm
URL          : https://lz4.github.io/lz4/
License      : GPLv2+ and BSD
Description  : LZ4 is an extremely fast loss-less compression algorithm, providing compression
: speed at 400 MB/s per core, scalable with multi-core CPU. It also features
: an extremely fast decoder, with speed in multiple GB/s per core, typically
: reaching RAM speed limits on multi-core systems.
```

Addenda:

I removed the package from Fedora and compiled the latest version from source. The problem disappeared. There is a bug somewhere in Fedora's distributed package.

**Comment by Cyan4973** [comment]
I just tried it on `dev` branch, and did not reproduce the issue.
All `*.lz4` files were successfully tested, and no decompressed file was written to disk.

Which version are you testing ?

**Comment by t-mat** [comment]
Hi @patch-work , thank you for the report.
But I also had failed to reproduce your issue with the following commands:

```
cd
git clone https://github.com/lz4/lz4.git lz4-issue-1164
cd lz4-issue-1164
make
./lz4 ./README.md ./out.lz4
./lz4 --test ./out.lz4
ls -l out*
```

Please let us know how you've encountered this issue.

**Comment by patch-work** [comment]
```
dnf info lz4
Last metadata expiration check: 0:00:50 ago on Wed Sep 14 16:57:33 2022.
Installed Packages
Name         : lz4
Version      : 1.9.3
Release      : 4.fc36
Architecture : x86_64
Size         : 113 k
Source       : lz4-1.9.3-4.fc36.src.rpm
Repository   : @System
From repo    : fedora
Summary      : Extremely fast compression algorithm
URL          : https://lz4.github.io/lz4/
License      : GPLv2+ and BSD
Description  : LZ4 is an extremely fast loss-less compression algorithm, providing compression
: speed at 400 MB/s per core, scalable with multi-core CPU. It also features
: an extremely fast decoder, with speed in multiple GB/s per core, typically
: reaching RAM speed limits on multi-core systems.
```

**Comment by Cyan4973** [comment]
When using `--test -m files*.lz4`, the problem described here can be reproduced using `1.9.3`, with a bunch of `files*` created. They are all empty files, but still, they are created (likely `fopen()`).
The issue doesn't happen with just `--test singleFile.lz4`, it requires `-m`.
It also doesn't happen on `v1.9.4` or later.

This is not an issue that was reported back then,
and none of the patches added to `v1.9.4` specifically mentions fixing it,
so it might have been fixed "accidentally", as a side effect of another refactor
(as an example, I remember refactoring some file opening/closing logic in `lz4io.c`, just because it felt unduly complex).

It also means that there was no test in CI to detect such issue.
So a follow up action could be to add such a test.
