### ISSUE TITLE
Compression Example in Java using ByteBuffers with LZ4_compress_default

### ISSUE THREAD

**Issue by PotatoPeeler3000** [lz4/lz4#1180]
I see a lot of examples for implementing LZ4 1.9 in C but is it possible to implement in Java as well? I'm trying to have `ByteBuffer src` compress into `ByteBuffer dest` but can't get it working. When working with previous versions like LZ4 1.8 the compress method takes in ByteBuffers as parameters but LZ4 1.9 expects a string or char pointer. Is there any examples you could point me to that implement LZ4 1.9 in java?

**Comment by t-mat** [comment]
Hi @Nkitchel2000 ,
Unfortunately, I think we don't and won't maintain any Java example/source code in this repository.
Because this repository is dedicated for reference LZ4 algorithm and frame format implementation in C90 and modern C/C++.

>  Is there any examples you could point me to that implement LZ4 1.9 in java?

Though I don't know they have a example which matches your demand, but please refer https://lz4.github.io/lz4/ to find Java implementation and bindings.

**Comment by PotatoPeeler3000** [comment]
Hmmm alright, ya I've looked at https://lz4.github.io/lz4/ and they have great examples for LZ4 1.8 but nothing for LZ4 1.9. And since the compression methods for LZ4 1.9 only work with string parameters I'm not sure its possible to implement in Java. Do you know if its possible to implement LZ4 1.9 in Java or is it only used for C/C++?

**Comment by PotatoPeeler3000** [comment]
Need to go here for Java Implementation: https://github.com/bytedeco/javacpp-presets/tree/master/lz4
