### ISSUE TITLE
Add copying `lz4file.h` to `make install`

### ISSUE THREAD

**Issue by vsolontsov-volant** [lz4/lz4#1189]
Hello, many thinks for the fantastic work!

It seems to be a minor but annoying thing -- the recent `lz4file.h` is not included into the `make install` copy list.
NB Seems like those who use `Meson` don't have this issue.

Would you consider fixing or, as it's in experimental status, you don't want to simplify the deployment yet?

**Comment by t-mat** [comment]
Hi @vsolontsov-volant, thanks for the report.

> It seems to be a minor but annoying thing -- the recent lz4file.h is not included into the make install copy list.

You're right.  `lz4file.h` should be included in the following sections:

- `lz4/lib/Makefile`
  - Within target `install:`, `ifeq ($(BUILD_STATIC),yes)` clause
  - Within target `uninstall:`
- `examples/Makefile`
  - Dependency of the target `$(LZ4DIR)/liblz4.a:`

> NB Seems like those who use Meson don't have this issue.

I'm not sure about convention of the Meson ecosystem.
But as for `lz4/contrib/meson/meson/lib/meson.build`, I think `lib/lz4file.h` should be inside of `if get_option('default_library') != 'shared'`.  Because all function of `lz4file.h` are `LZ4FLIB_STATIC_API` == static-only.

@tristan957, could you check above condition in 198e532300f253ada3acac3ab5428ed991adb085 ?

> Would you consider fixing or, as it's in experimental status, you don't want to simplify the deployment yet?

For now, I think `lz4file.h` (static-only, experimental APIs) should be installed when `lz4frame_static.h` (same. static-only, experimental APIs) is installed.

As you know we'll eventually promote them as a stable (regular, shared, `LZ4FLIB_API`) API though.

**Comment by vsolontsov-volant** [comment]
Hi @t-mat,

Thanks you prompt confirmation.
I've just pushed a PR for this one but mainly for const source pointer in the `LZ4F_write()` if you'd prefer to take it -- it's trivial.

**Comment by t-mat** [comment]
Thanks for sending PR @vsolontsov-volant,
If you can, please split your PR #1190 into two PRs.  I mean:

- (PR-no.1): Fixed const-ness of src data pointer in lz4file and install lz4file.h
- (PR-no.2): Add copying lz4file.h to make install

This "send one PR for one issue" rule is one of the most common convention in many projects.
Because it clarifies the intention of PR and commits.  And the important point is that it may help (a lot of) future contributors who want to understand your change.

**Comment by vsolontsov-volant** [comment]
That's a fair point (yet, I haven't found a contribution -- would be good to have).
Anyway, pushed both PRs.

**Comment by tristan957** [comment]
@t-mat see my Meson PR for what I believe is the fix for this issue.

**Comment by Cyan4973** [comment]
If I'm not mistaken, this issue was already fixed by @vsolontsov-volant,in #1191 and #1192, so let's close it.
