### ISSUE TITLE
Documentation on compression level?

### ISSUE THREAD

**Issue by Acetylator** [lz4/lz4#119]
Hello,
I can't seem to find any structured info on compression level used in LZ4. From the source code it seems that values from 0 to 16 should be used, and it seem that from level 9 and above HC compression will be used. However, I am not sure if I am correct on it. So I would be nice if devs provide some clear info about compression levels and how they relate to each other. How does computational complexity raise with raising compression level? Is it linear? Logarithmic? Are there any "standard" compression levels that should be used in benchmarks? Well, I think you got the idea.
Thank you!

**Comment by Cyan4973** [comment]
I suspect your question relates to the command line utility.
In which case, LZ4 HC is used for compression levels 3 and beyond.

It's very difficult to give a simple idea of how compression time increases with compression level. Let's say it follows a classical curve of diminishing returns. Your mileage will vary depending on source data to compress and CPU type.

I typically recommend using 2 modes (-1 for fast, -9 for HC), but this is mostly a simplification. Your use case may imply using intermediate or higher values, that's why they are available.

Regards

**Comment by Cyan4973** [comment]
Latest update in `dev` branch provides more detailed instructions in `man lz4` regarding how the compression levels work.
