### ISSUE TITLE
is it possible to have lz4 as a zip archive?

### ISSUE THREAD

**Issue by alexmannen** [lz4/lz4#1202]
i couldnt find a reddit sub so im asking dumb questions here.
im wondering if u can store compressed files in folders formats so games can access files and stream them on demand.
for example if u had 500 mods for kerbal space program and instead of loading all of it into ram.
store all mods in a compressed archive efficiencly and only stream assets into the game when needed.
so u dont need to unpack the entire archive but just bits of it.

**Comment by Cyan4973** [comment]
What you are looking for would be well-served by a read-only compressed file system,
like SquashFS for example.
SquashFS supports `lz4` compression.

**Comment by anjiahao1** [comment]
this is a good idea, It would be nice if lz4 could be made an internal standard usage in zip, like lzma. In this way, everyone can use lz4 to compress zip files and decompress them anywhere, instead of using special programs.

**Comment by levicki** [comment]
@alexmannen 

1. All modern game engines already use heavily compressed assets using specialized compression formats for textures and audio, and general compression formats (usually LZMA) for geometry and other data.
2. All modern game engines already stream assets because video RAM is limited.
3. Modifying games that aren't streaming assets would be a colossal undertaking especially without source code access.

@anjiahao1 

No it's not a good idea. Using LZ4 over other compression formats has absolutely no benefit for games. LZ4 has worse compression ratio, it is not supported by any graphics or audio APIs, and current games are huge. For example:

![image](https://github.com/lz4/lz4/assets/16415478/7cb74eb1-f45b-4220-9503-649641cc6c7c)

So having those heavily compressed 90 GB repacked with LZ4 would likely result in 120-150 GB (if not more) both for download and for storage on your disk with no visible benefit over current implementation.

As for ZIP supporting LZ4 compression as a method, that's something authors of ZIP archive format would have to implement. Again, the speed tradeoff is not worth it &mdash; if you want fast archiving you can always make a ZIP file without compression (i.e. use store method) which will always be faster than even the fastest LZ4 and given that most file formats are already compressed (yes, even `.docx`, `.xlsx`, and `.pdf` are compressed with ZIP and Zlib respectively) it is more efficient to just use store method anyway.
