### ISSUE TITLE
Tracker for "linking to liblz4.so" change in meson build config

### ISSUE THREAD

**Issue by travier** [lz4/lz4#1205]
See https://github.com/lz4/lz4/commit/6c1a39e701b274c47538258c6d6e3e60dddc704a#r82851900.

This is an issue to track this work.

**Comment by tristan957** [comment]
I will look at this today.

**Comment by tristan957** [comment]
Ok, so I have taken a look and it seems that the executable uses symbols that are only exposed if `-Dunstable=true`, so that `LZ4_PUBLISH_STATIC_FUNCTIONS` is defined. I don't see a solution to this problem.

**Comment by tristan957** [comment]
Can I ask what issues you might be running into without a fix for this @travier

**Comment by travier** [comment]
@stewartsmith might have more context. I don't think we have hit a specific issue. It was more about wondering if this was intentional.

Thanks

**Comment by travier** [comment]
Going to close it for now and we can revisit if something is needed here.

**Comment by stewartsmith** [comment]
It’s something I noticed when updating the packaging for Fedora/Amazon Linux. Prior to this change, the command line utility linked with the shared library, but after this change, it does not.I would generally expect that the command line utility would be a small wrapper around the shared library, and not include a copy of all of its code.However, I’m no expert in lz4 internals, and thus wasn’t sure if this was intentional for some reason, such as starting to build code with different options depending on if it’s in the library or command line utility. If it is intentional for this reason, then there isn’t a reason.But if it’s unintentional and it really should just use the shared library, then it’s a bug :)Sent from my iPhoneOn Jan 11, 2023, at 1:45 AM, Timothée Ravier ***@***.***> wrote:﻿
@stewartsmith might have more context. I don't think we have hit a specific issue. It was more about wondering if this was intentional.
Thanks

**Comment by tristan957** [comment]
@Cyan4973 @t-mat would y'all potentially be able to provide some context around the intended behavior here? Thanks :)

**Comment by t-mat** [comment]
As for static linking, the `lz4` cli is intentionally static-linked since the beginning of this project.
Because it uses `LZ4_STATIC_LINKING_ONLY` features.  Please take a look the following part of the code

https://github.com/lz4/lz4/blob/v1.9.4/programs/bench.c#L50-L54

**Comment by tristan957** [comment]
Thanks for the clarification :).
