### ISSUE TITLE
Document x32 ABI usage

### ISSUE THREAD

**Issue by svenha** [lz4/lz4#1213]
Thanks to the very portable code base, one can easily compile lz4 for the x32 ABI:

    CC="gcc -mx32" make
    CC="gcc -mx32" make test

The speed numbers reported by fullbench improve by 5 % to 10 % compared to x86-64 (gcc (Ubuntu 12.2.0-3ubuntu1) 12.2.0).

I don't know much about the project, so I can only suggest to add to the documentation: how to build for the x32 ABI
and that you can expect a speedup :-)

**Comment by Cyan4973** [comment]
A "proper" way to set `x32` ABI is to set it via `CFLAGS`, aka :
```
CFLAGS="-mx32 -O3" make
CFLAGS="-mx32 -O3" make test
```
so that the underlying compiler can still be whatever the local system requires.

`x32` is so niche that I would have expected anyone interested or even just aware of `x32` to also know how to compile for this target. But that might have been too optimistic...

**Comment by svenha** [comment]
Agreed that interested people should know how to compile for x32. The gained speedup was a pleasant surprise.

**Comment by svenha** [comment]
I published some comparison results: https://openbenchmarking.org/result/2401169-NE-SEMDD12RY16,2401160-NE-SEMDD12RY26
