### ISSUE TITLE
Memory leak in lz4/lib/lz4file.c？

### ISSUE THREAD

**Issue by BojackMa** [lz4/lz4#1249]
We perfom a fuzz on lz4/examples/fileCompress.c. 
```   
  19   │ ==27993==ERROR: LeakSanitizer: detected memory leaks
  20   │ 
  21   │ Direct leak of 288 byte(s) in 1 object(s) allocated from:
  22   │     #0 0x5555555f65f8 in __interceptor_calloc (/lz4_0710_fix2/examples/fileCompress+0xa25f8) (BuildId: 914385810b9fb551
       │ 3ca8ae41b3736d9a4008e407)
  23   │     #1 0x555555635232 in LZ4F_createDecompressionContext (/lz4_0710_fix2/examples/fileCompress+0xe1232) (BuildId: 91438
       │ 5810b9fb5513ca8ae41b3736d9a4008e407)
  24   │ 
  25   │ SUMMARY: AddressSanitizer: 288 byte(s) leaked in 1 allocation(s).
  26   │ 
```
It shows a memory leak in `LZ4F_createDecompressionContext`. The probable cause could be the missing calls to `LZ4F_freeDecompressionContext((*lz4fRead)->dctxPtr);` at lines 74 and 81.
https://github.com/lz4/lz4/blob/839edadd09bd653b7e9237a2fbf405d9e8bfc14e/lib/lz4file.c#L73-L77
https://github.com/lz4/lz4/blob/839edadd09bd653b7e9237a2fbf405d9e8bfc14e/lib/lz4file.c#L81-L84

**Comment by t-mat** [comment]
Hi @BojackMa,
Thanks for the report.

## Line 81..84 of lz4file.c

As for line 81..84, you're right.  
We missed to put `LZ4F_freeDecompressionContext((*lz4fRead)->dctxPtr);`.  This bug should be fixed.


## Line 74..77 of lz4file.c

As for line 74..77, I think we can leave it as is.

https://github.com/lz4/lz4/blob/839edadd09bd653b7e9237a2fbf405d9e8bfc14e/lib/lz4file.c#L68-L77

Since we've called `calloc()`, at the beginning of line 73, before calling `LZ4F_createDecompressionContext()`, we're sure

- `*lz4fRead != NULL`
- `(*lz4fRead)->dctxPtr == NULL`
- `&(*lz4fRead)->dctxPtr != NULL`

As for `LZ4F_createDecompressionContext()` and `LZ4F_createDecompressionContext_advanced()`,

https://github.com/lz4/lz4/blob/839edadd09bd653b7e9237a2fbf405d9e8bfc14e/lib/lz4frame.c#L1244-L1255

https://github.com/lz4/lz4/blob/839edadd09bd653b7e9237a2fbf405d9e8bfc14e/lib/lz4frame.c#L1228-L1236

We always pass line 1248 since `&(*lz4fRead)->dctxPtr != NULL`, `LZ4F_decompressionContextPtr != NULL`.

When line 1252 returns error, `*LZ4F_decompressionContextPtr == NULL`.  It means `LZ4F_createDecompressionContext_advanced()` failed to call `LZ4F_calloc()`.
It also means it doesn't allocate any memory for it.

So, when `LZ4F_createDecompressionContext()` returns error, `(*lz4fRead)->dctxPtr == NULL`.

Therefore, we should not touch `(*lz4fRead)->dctxPtr` at the line 74..75 of `lz4file.c`.  
`LZ4F_freeDecompressionContext()` works with `NULL` though.
