### ISSUE TITLE
[Question] Is LZ4F_decompressionOptions::stableDst referring to an absolute memory address or data relative to dstBuffer, aka std::span{dstBuffer-64KB, 64KB}?

### ISSUE THREAD

**Issue by borbmizzet** [lz4/lz4#1266]
After reading https://github.com/lz4/lz4/issues/350, I am still unclear on `LZ4F_decompressionOptions::stableDst`. Is it referring to the absolute memory address the previous call to LZ4F_decompress() decoded to or data relative to the current call's `dstBuffer`, aka `std::span{dstBuffer-64KB, 64KB}`?
Essentially, if I have to reallocate `dstBuffer` with increased size because it was too small, and the data in `dstBuffer[0..64KB]` is the same data if I call `LZ4F_decompress(decompressionContext,  dstBuffer+64KB, ...)`, is that still a valid use case for `stableDst = 1`?

**Comment by Cyan4973** [comment]
#350 is pretty old, so things might have changed since.

From what I can tell from reading the source code,
`stableDst` only requires that the caller ensures that previous 64 KB of decompressed data
is present right before the passed `dstBuffer` pointer.

And that's about it.

Therefore, addresses could change between invocations, it wouldn't matter as long as these 64 KB are there.

I suspect that, initially, the implementation would be more rigid, and require (and check) that the addresses remain exactly identical between invocations, as a way to "ensure" that everything was still in place. Hence the name of the parameter `stableDst`. This probably changed at some point, but the parameter name and its comment remain.
The comment probably requires an update.

**Comment by Cyan4973** [comment]
code documentation updated in #1267
