### ISSUE TITLE
Any way to improve compression/decompression speed in dict scenario?

### ISSUE THREAD

**Issue by linyli001** [lz4/lz4#1319]
Hi, I'm applying the dict mode to compress some small blocks data (about 35KB per data). From the benchmark, I found the compression ratio has improved a bit (from 1.174 to 1.528). But the compress speed and decompress speed has regression. I understand that speed should not really be a reason to be using a dictionary, since the purpose should be primarily focused on compression ratio increases on small data. But I really care about both compression ratio and speed.

From https://github.com/lz4/lz4/issues/559 I saw there is a trick to speed up decompression by placing the output buffer contiguously follows the dictionary buffer. Can I do the similar thing to improve the compress speed? Any instruction could you please give me?

Here is the details for my test:

1. Generate 64KB dict by "zstd --train-fastcover k=512,d=8,f=28" option on 1000 train samples (35KB each sample). The data is in binary format.
2. Benchmark for with dict and no dict on other 1000 test samples. Per test file size is almost 35KB and test files are independent.
**No Dict:**
lz4.exe -b1 -e7 -r d:\tmp\lz4_dict\sample\test
Benchmarking levels from 1 to 7
1# 1142 files       :  **25857779 ->  22034134 (1.174),1286.0 MB/s, 4378.6 MB/s**
2# 1142 files       :  25857779 ->  22034134 (1.174),1207.7 MB/s, 4562.3 MB/s
3# 1142 files       :  25857779 ->  21382929 (1.209),  93.6 MB/s, 3906.0 MB/s
4# 1142 files       :  25857779 ->  21374332 (1.210),  91.4 MB/s, 4006.3 MB/s
5# 1142 files       :  25857779 ->  21369639 (1.210),  93.2 MB/s, 4189.3 MB/s
6# 1142 files       :  25857779 ->  21367195 (1.210),  90.3 MB/s, 4094.4 MB/s
7# 1142 files       :  25857779 ->  21366246 (1.210),  90.8 MB/s, 4136.3 MB/s

**WithDict:**
lz4.exe -b1 -e7 -r d:\tmp\lz4_dict\sample\test -D d:\tmp\lz4_dict\sample\0.dict
Benchmarking levels from 1 to 7
1# 1142 files       :  **25857779 ->  16923358 (1.528), 377.9 MB/s, 3454.2 MB/s**
2# 1142 files       :  25857779 ->  16923358 (1.528), 388.6 MB/s, 3333.8 MB/s
3# 1142 files       :  25857779 ->  14212693 (1.819),  65.6 MB/s, 1724.5 MB/s
4# 1142 files       :  25857779 ->  14154290 (1.827),  59.0 MB/s, 1740.2 MB/s
5# 1142 files       :  25857779 ->  14140178 (1.829),  59.6 MB/s, 1729.2 MB/s
6# 1142 files       :  25857779 ->  14134697 (1.829),  55.5 MB/s, 1664.7 MB/s
7# 1142 files       :  25857779 ->  14132152 (1.830),  55.2 MB/s, 1653.9 MB/s
 
The compression speed regress a lot from 1286.0MB/s to 377.9 MB/s on level 1, which seems a performance bottleneck for me since the compression is used in RPC scenario and speed impacts a lot for network latency.

**Comment by Cyan4973** [comment]
Yes,
positioning the dictionary content right before the content to compress will improve compression speed too.

The downside of this method is that the dictionary buffer cannot be shared across multiple concurrent threads. Each thread must have its own copy of the dictionary buffer, so that it can write right after it.

Note that I was expecting the impact on decompression speed to be larger, and the impact on compression speed to be smaller. This is reversed in your use case, so it is interesting.
Let us know what kind of speed up you achieve by using this technique on the compression side.
This could prove interesting to document.

**Comment by linyli001** [comment]
Thanks @Cyan4973 quick response. And I have tried this trick to compress/decompress the test data. The conclusion is that both speeds has improved a lot, but compression speed still has obvious regression compared with no dict mode.

Here is my experiment. There are 4 test examples, from this we can see after applying the trick decompression speed is almost the same with no dict cases, but compression speed still has big gap with the baseline (nearly 50% less).

**No dict:**
test_data1.bin: 18660 -> 16101 (1.159), 2535.7 MB/s, 7726.7 MB/s
test_data2.bin: 36066 -> 30242 (1.193),1135.4 MB/s, 7756.1 MB/s
test_data3.bin: 23564 -> 20942 (1.125),2325.5 MB/s, 12395.6 MB/s
test_data4.bin: 18768 -> 14300 (1.312),1884.1 MB/s, 7552.5 MB/s

**With dict before trick:**
test_data1.bin: 18660 -> 12739 (1.465), 447.9 MB/s, 6031.0 MB/s
test_data2.bin: 36066 -> 27088 (1.331), 460.5 MB/s, 7464.0 MB/s
test_data3.bin: 23564 -> 15711 (1.500), 508.1 MB/s, 8028.6 MB/s
test_data4.bin: 18768 -> 8945 (2.098), 559.1 MB/s, 5642.8 MB/s

**With dict after trick:**
test_data1.bin: 18660 -> 12739 (1.465), 961.7 MB/s, 8152.0 MB/s
test_data2.bin: 36066 -> 27088 (1.331), 847.6 MB/s, 8859.2 MB/s
test_data3.bin: 23564 -> 15711 (1.500),1084.7 MB/s, 10696.3 MB/s
test_data4.bin: 18768 -> 8945 (2.098),1090.0 MB/s, 7314.1 MB/s

@Cyan4973 Do you think this is all we can do to optimize speed? I have tried other ways to tune the training parameters such as "k" or "step" but no substantial changes on speed. 
BTW, this trick has extra cost in multiple data source cases. I have to copy the dictionary buffer to a contiguous area with the data source buffer and call lz4_loadDict() for every independent source file. This cost may neutralize the benefits of the trick. Note that this problem exists in even single thread. Any suggestion could you please provide on this downside?

**Comment by Cyan4973** [comment]
> @Cyan4973 Do you think this is all we can do to optimize speed?

Yeah, pretty much.
The next step is to rewrite the compression algorithm, and specialize the search strategy for this scenario.
That's a tall order.

> Any suggestion could you please provide on this downside?

It is the downside of this trick.
There is no escape.

I think it works well in single-thread mode, because you can now use the buffer with guarantee of no concurrency.
There is still some additional `memcpy` involved, but that's typically (way) faster, so usually it's favorable.

The situation is way worse in concurrent scenarios, though one could implement a pool of buffers.
Still, it's much less convenient, and now it's an open question if one prefers to pay the speed cost for the convenience of a less complex source code.
