### ISSUE TITLE
PoC: Use MSVC without project files

### ISSUE THREAD

**Issue by t-mat** [lz4/lz4#1386]
MSVC project files (.sln and friends) have been our burden.  Because their format, structure and convention have been (will be) changed randomly.

To ease this problem, I made a simple batch script which invokes `cl.exe` (MSVC compiler/linker driver) and `rc.exe` directly.

It's cumbersome, but its core is the following one line:

```
cl.exe %COMPILER_OPTIONS% %SRCS% /link %LINKER_OPTIONS% lz4.res
```

It passes compiler options, source files, linker options and resource file.

**Comment by t-mat** [comment]
[gist](https://gist.github.com/t-mat/de819af37d3dd399147a75f9af1b034e)

Procedure:

```
cmd.exe
cd /d "%USERPROFILE%\Documents"
md lz4-issue-1386
cd lz4-issue-1386
git clone https://github.com/lz4/lz4.git
cd lz4

md build\visual_studio\lz4
cd build\visual_studio\lz4

copy ..\..\VS2022\lz4\lz4.rc .

curl -JOL https://gist.githubusercontent.com/t-mat/de819af37d3dd399147a75f9af1b034e/raw/build-vs2022.cmd
type build-vs2022.cmd | find "" /V > build-vs2022.cmd.bat
.\build-vs2022.cmd

.\lz4.exe --version
```

**Comment by Cyan4973** [comment]
Yes, this is a good idea.

**Comment by Cyan4973** [comment]
#1440  uses a somewhat different method to generate the Visual Studio solution, by leveraging `cmake` directly.

But this approach requires `cmake` to be installed and accessible on the local computer.

If this condition is deemed too limitative, one potential mitigation could be to provide at least one pre-generated solution within the repository.

Note that the  manually-defined `VS2022` solution is still present within `build/`, in part because it's used by some tests, and in another part because its content differs from the Solutions built from `cmake`, so existing users could be surprised by this difference. But this is a temporary situation, manually-defined solutions are set to be removed in a future version.

**Comment by t-mat** [comment]
Since Visual Studio and its installer [supports `cmake`](https://learn.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-170#installation), I think requirement of `cmake` is 100% okay for them who can install Visual Studio.

I believe [`vsTests`](https://github.com/lz4/lz4/tree/vsTests) made our situation far better.  And it surpassed this PoC.

Therefore, I close this issue.  In future, perhaps we may need something other than `cmake`.  But it should be another issue.
