### ISSUE TITLE
Licence GPL 2.0 only or GPL 2.0 or later

### ISSUE THREAD

**Issue by Adeline-Toader** [lz4/lz4#1412]
Hello,
Is the licence for some of the files in the repository GPL 2.0 only or GPL 2.0 or later? Many thanks!

**Comment by t-mat** [comment]
As for license, please refer the [`LICENSE`](https://github.com/lz4/lz4/blob/dev/LICENSE) file.
Since it clearly states "all other files use a GPLv2 license", these files are licensed under [`GPL-2.0-only`](https://spdx.org/licenses/GPL-2.0-only.html).

**Comment by Adeline-Toader** [comment]
Dear t-mat,
Thank you for your reply,
My colleagues in the European Commission are using lz4 in a project which will be distributed under the GPL 3.0 licence (due to the use of many other components under the GPL 2.0 or later or GPL 3.0). However, GPL 2.0 only is not considered compatible with GPL 3.0 and in these conditions we could not use your project. For this reason we wanted to ask you whether you will consider upgrading the current licence to GPL 2.0 or later or licensing it to us under the GPL 2.0 or later so that we do not have to make modifications to the code.
Thank you very much in advance,
Adeline

**Comment by Cyan4973** [comment]
The library itself `liblz4` is BSD licensed, which should be compatible with GPL 3.0.

It's the CLI and the test portions which are GPL.

GPL 2.0 was selected for Linux compatibility.

Now, on the topic of "GPL 2 _only_" vs "GPL 2 _or later_" , I've never given much thoughts, because it has not been brought up as a topic so far. This changes today.
I presume GPL 2 _or later_ would remain compatible with Linux, which is the main objective.
In which case, I would see no problem updating the license to "GPL 2 _or later_".

**Comment by t-mat** [comment]
@Cyan4973, I'm 100% sure that migrating "GPL 2 or later" is legal (as a GPL conformance, since licensee is able to choose GPLv2 or later).

But we may need to ping someone who manages [SPDX style](https://spdx.org/licenses/GPL-2.0-or-later.html) licenses for package managers.

vcpkg team: @autoantwort, @EddyPronk : ping for potential [license](https://github.com/microsoft/vcpkg/blob/master/ports/lz4/vcpkg.json#L7) update.

**Comment by autoantwort** [comment]
Is there a new release with the new license?

**Comment by t-mat** [comment]
@Cyan4973 I added this issue (license update) to `v1.9.5`.  But please feel free to change it.
@autoantwort, thanks for the reply. AFAIK, `v1.9.5` - the next release will ship in the year of 2024.

**Comment by autoantwort** [comment]
Ok iiuc the lib is `BSD-2-Clause` and since the vcpkg port only builds the lib and no test and cli tools the current expression could already changed to `BSD-2-Clause` only

**Comment by t-mat** [comment]
> Ok iiuc the lib is BSD-2-Clause and since the vcpkg port only builds the lib and no test and cli tools the current 
> expression could already changed to BSD-2-Clause only

Sounds reasonable.  Since vcpkg team is just focusing code as a library.
@Cyan4973 let us know if you have an opnion that how "`lz4` as a library" should be treated (as a verbatim code and static/shared library)
It seems `BSD-2-clause only` is the best license for "lz4 as a library".  If vcpkg doesn't build `lz4-cli`.

**Comment by Cyan4973** [comment]
I just realised that the text at the top of each gpl source file already states :
```
either version 2 of the License, or (at your option) any later version.
```

So `lz4` is already employing a `GPL 2.0 or later` license.

Problem is, this is not expressed clearly enough, so it can be interpreted as `2.0-only` when looking just at the top license files. I guess this could be fixed pretty quickly.

**Comment by dg0yt** [comment]
I usually look at Debian copyright files to get a detailed list:
https://tracker.debian.org/media/packages/l/lz4/copyright-1.9.4-2

Many thanks to Debian :heart:

**Comment by Cyan4973** [comment]
> > Ok iiuc the lib is BSD-2-Clause and since the vcpkg port only builds the lib and no test and cli tools the current
> > expression could already changed to BSD-2-Clause only
> 
> Sounds reasonable. Since vcpkg team is just focusing code as a library. @Cyan4973 let us know if you have an opnion that how "`lz4` as a library" should be treated (as a verbatim code and static/shared library) It seems `BSD-2-clause only` is the best license for "lz4 as a library". If vcpkg doesn't build `lz4-cli`.

I'm totally fine with keeping `BSD-2-clause` for the `liblz4` library.
As far as I can tell, it's fully compatible with `gpl-2+`.
