### ISSUE TITLE
Performance regression from 1.9.3 to 1.9.4

### ISSUE THREAD

**Issue by murphyatwork** [lz4/lz4#1441]
**Describe the bug**
I tried to upgrade the lz4 version of StarRocks database from 1.9.3 to 1.9.4, but just encountered the performance degradation. So I did more benchmark to verify it, then find these results.

My benchmark is based on the SSB dataset, I cut a whole CSV file into separated files for each column, to simulate a 'columnar storage'. Each column in SSB has different data distribution so they can be used to test the compression of lz4 algorithm. 

As a result, for most columns the compression speed degrades around 2%, in total 1.1%.

**The result of of different compression level:**
<img width="572" alt="image" src="https://github.com/user-attachments/assets/74717018-3fb2-4abd-9757-925f5a796170">

**The result of different files:**
<img width="994" alt="image" src="https://github.com/user-attachments/assets/91d9361e-4204-4bdf-af8d-ecd5c18bc4ce">

**Expected behavior**
Please describe what you expected to happen.

**To Reproduce**

1. Generate the SSB dataset 
2. Cut the CSV files into separated columns 
3. Run LZ4 benchmark: `lz4 -b1 -e9 column2.txt`. 

**System (please complete the following information):**
 - OS: 5.15.0-46-generic #49-Ubuntu
 - Version 1.9.3 & 1.9.4
 - Compiler: GCC 12.3.0
 - Build System Makefile
 - Other hardware specs: Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz

**Additional context**

**Comment by Cyan4973** [comment]
Unfortunately, at this level of difference, there are too many possible contributors, so it's a hard investigation.
This can be, for example, a random impact of instruction alignment, which changes for any random reason,
is decided by the compiler and is uncontrollable from `C` source code.

Presuming you are compiling the source code yourself (since `gcc` is mentioned),
you could check that by trying and comparing multiple versions of the same compiler, or different compilers (like `clang`).
Results will be different, but also not preserve the observed difference reported here.
Differences may be increased, or decreased, or ranking may be flipped.

**Comment by murphyatwork** [comment]
good point. At first i was also suspecting that the difference is introduced by the compiler, so I built the lz4 from source code with same version of GCC.

I can do more tests with different versions of compiler, to rule out the affect of compiler

**Comment by murphyatwork** [comment]
<img width="774" alt="image" src="https://github.com/user-attachments/assets/547086e7-f9c3-4a65-bf5e-54b4e8a4c10e">

The result is interesting:
- With clang 15 & 16, there's no so much performance regression
- With gcc 12, the regression is relative larger
