### ISSUE TITLE
Static single binary of lz4 with  '-T' multi-thread

### ISSUE THREAD

**Issue by vrangesync** [lz4/lz4#1480]
lz4 multi-thread edition - static single binary and include many other static binary files - download for free.
https://github.com/vrangesync/vrangesync_officialbox

A small bug to report
when you do a '--help' & '--version', it still show as single thread while the '-T' (multi-thread) is officially included.
It happen to the static binary version of lz4 which i compile on alpinelinux using musl.

*** lz4 v1.10.0 64-bit single-thread, by Yann Collet ***
Usage : 
      lz4 [arg] [input] [output] 

input   : a filename 
          with no FILE, or when FILE is - or stdin, read standard input
Arguments : 
 -1     : fast compression (default) 
 -12    : slowest compression level 
 -T#    : use # threads for compression (default:0==auto)

**Comment by vrangesync** [comment]
-j# (multi-thread) feature mention in 'INSTALL' file should be updated to use '-T'(multi-thread)

**Comment by Cyan4973** [comment]
`-j#` is using multithreading for the build process via `make`.

**Comment by Cyan4973** [comment]
Note that, in order for the `lz4` CLI to be built with multithreading support, the build variable `LZ4IO_MULTITHREAD` must be set, as documented here: https://github.com/lz4/lz4/tree/dev/programs#c-preprocessor-build-variables .
This is automatically done when building with the provided `Makefile`, but when using your own build system, it would have to know about this variable.

I can update the `--help` command so that it only documents `-T#` when multithreading is effectively enabled.

**Comment by vrangesync** [comment]
need tip on how to include that if i use 'cmake' to do compile

**Comment by Cyan4973** [comment]
`cmake -DCMAKE_C_FLAGS="-DLZ4IO_MULTITHREAD=1 -pthread -static"  ..`
