### ISSUE TITLE
Adding an `offset` selection option

### ISSUE THREAD

**Issue by ortosol** [lz4/lz4#1511]
Hi, Is it possible to add `offset` option for lz4 utility

 - Problem:
   I know that current `offset` can be changed with `LZ4_DISTANCE_MAX` flag,
   but it's quite annoying to make a new build every time I need to change offset
   paramenter.

 - Possible Solution:
   I would like to have an option like this:
   ```
   lz4 --offset=4096 file
   lz4 --offset=16384 file
   ...
   ```

- Question:
  Can you add such an option or would you accept such option if I
  prepare a patch. I would also like to know if such functionality is incompatible.

Any assistance would be greatly appreciated. Thank you!

**Comment by Cyan4973** [comment]
It is technically possible to do so,
but beyond the increased complexity and its associated maintenance cost,
I'm also concerned about the potential impact on performance (at least for the fast variant),
because it would change a compile-time constant into a runtime variable.
This will necessarily increase register pressure and maybe binary size,
though it could be by a negligible amount.
The only way to know would be to measure the impact such a change.

Custom `LZ4_DISTANCE_MAX` is a fairly niche setting,
so while I'm sympathetic to the idea of making it simpler,
it shouldn't come at the expense of the general use case, which never touches this value.

**Comment by ortosol** [comment]
Thanks a lot for your answer. I suppose issue can be closed for now
