### ISSUE TITLE
Incorrect hash sequence calculation on 64-bit big endian platforms

### ISSUE THREAD

**Issue by yuri-per** [lz4/lz4#169]
``` diff
--- lz4.c.orig  2015-10-21 14:15:30.918002700 +0300
+++ lz4.c   2015-12-04 12:12:00.340226200 +0300
@@ -391,6 +391,7 @@
 static U32 LZ4_hashSequence64(size_t sequence, tableType_t const tableType)
 {
     const U32 hashLog = (tableType == byU16) ? LZ4_HASHLOG+1 : LZ4_HASHLOG;
     const U32 hashMask = (1<<hashLog) - 1;
+    if (!LZ4_isLittleEndian()) sequence >>= (64 - 40);
     return ((sequence * prime5bytes) >> (40 - hashLog)) & hashMask;
 }
```

**Comment by Cyan4973** [comment]
That's a very good point @yuri-per.

Indeed, big-endian 64-bits platform will have a poor match rate with this bug.
Minor issue : I have no big-endian 64-bits platform to test it (not a blocker, since the fix looks simple enough).

Note to self : 
pb here is that big endian tests are manual, hence not automated, and only done on 32-bits anyway ...
Would be great to find a way to automate big-endian tests.

**Comment by kirillx** [comment]
Actually, Yuri patch seems to be wrong.
Instead you should swap bytes in sequence, i.e. add smth cross-platform like:
+ sequence = bswap_64(sequence);
I've checked that SPARC64 generates same content on compression as x86_64.

For SPARC-32 similar change in LZ4_hashSequence() is required as well:
+ sequence = bswap_32(sequence);

After that both SPARC32/64 generate the same content as x86/x64.

Is it expected though that 32 and 64 bit systems generate different compressed results? Decompression seem to work though.

**Comment by Cyan4973** [comment]
Big endian and Little endian platforms generate different compressed files
But they are both valid (ie they respect the LZ4 compression format), so they can be decoded properly.
Their performance are similar too (not "identical", just equivalent).

So does 32-bits and 64-bits ones : 64-bits match finder performs faster on 64-bits platforms, but slower on 32-bits ones. It also tends to compress a bit better, although that's marginal, and there are counter examples, so let's call them "equivalent" too.

I never considered that a problem. After all, every compression level generates a different compressed file. As long as the compressed file respects the LZ4 compression format, it's decodable, hence perfectly fine.

Your patch, @kirillx, would make big endian platforms generate same compressed file as little endian ones (in fast compression mode). Is that an important benefit ? I don't think so. Is that a problem ? No, certainly not.

So what could help us select the better solution ?
I believe that speed is a good argument here.
Since both methods are equivalent, whichever method works faster gets the win.

**Comment by Cyan4973** [comment]
Latest update in `dev` branch uses a new hash branch decision and algorithm, which should make it both more efficient on small input, and more efficient on 64-bits big-endian machines.
