### ISSUE TITLE
No compressed file produced when stdout is redirected to /dev/null

### ISSUE THREAD

**Issue by sudokode** [lz4/lz4#186]
It looks like lz4 is using stdout to write to the output file.

`lz4 foo &>/dev/null` produces no output, but also no compressed file

`lz4 foo 2>/dev/null` works as expected

`lz4 foo >bar 2>baz` shows what's going on here. lz4 is sending the compressed data through stdout instead of opening the file (I guess)

`lz4 foo foo.lz4 >bar 2>baz` makes me think this is how it was designed, but I have no idea

**Comment by Cyan4973** [comment]
Hi @sudokode 

`lz4` started its life with the following principle : 
`lz4 inputFilename outputFilename`

Even today, it works as intended. But since then, many other modes have been added, at popular request to look more like gzip. So it can be a bit confusing at times.

`lz4 inputFilename` introduces the notion of _default outputFilename_, which in this case will be `inputFilename.lz4`.

But there is more to it : anytime `stdout` is anything else than console, _it becomes the default output_.

So `lz4 inputFilename > outFile` will send the result into `outFile`.

It's only default though. So if a destination is provided, it's still used : 
`lz4 srcFile dstFile > stdOutFile`  will still produce result into `dstFile`, and `stdOutFile` will end up empty.

And there are some more difficulties. A few more options have been added, in an attempt to bring familiarity with `gzip`. 

So for example, `-c` send to `stdout`, hence : 
`lz4 -c srcFile > outFile` will send result into outFile. It's completely equivalent to `lz4 srcFile > outFile`.
`-` means `stdin` if it is first, `stdout` if it is second.
So `lz4 srcFile - > outFile`  will also send result to `outFile`.
And any attempt to do `lz4 -c srcFile dstFile` will be flagged as an error, since `lz4` is instructed both to output into `stdout` and `dstFile`.

Well, we can play with a lot of strange combinations. The basic ideas are : 

- `lz4` has been created to be used like this : `lz4 srcFile dstFile`.
- `stdout` is default output if none provided, except if it is the console (as it would likely break the console with binary characters).
  + in which case, default output becomes `srcFile.lz4`.


I believe the binary works as intended. But the intention can be difficult to grasp.
Not sure how to improve this situation. Better doc maybe ...

**Comment by sudokode** [comment]
Ah, I figured it had a history, as it also ended up in `zstd`. I just wanted to point out that it's unexpected behavior (at least to me), as something like `gzip -k foo &>/dev/null` will result in `foo` and `foo.gz`. Of course if you use `gzip -kc`, then that output would go away, but without the operator, `stdout` is (generally always) used for actual program output.

Not a problem, just wanted to make sure it was either known or part of the design. So far, that has been my only complaint about `lz4` and I'm liking `zstd` too, so thanks for the work you do.

As far as docs go, the manpage does differ a bit from the `-h` output (e.g. <output-file> is mandatory in the manpage, but [output] is optional in `-h`). There is a note about `stdin`, but perhaps a note about `stdout` would be helpful. I was scratching my head for a bit :D

**Comment by Cyan4973** [comment]
:+1: 
Definitely, doc should be updated to make these points clearer.

**Comment by Cyan4973** [comment]
man page has been updated in `dev` branch to reflect this discussion,
list of differences with `gzip` is more complete and precise
