### ISSUE TITLE
A problem with LZ4F_compressFrameBound

### ISSUE THREAD

**Issue by nbozhinov** [lz4/lz4#223]
Hello,
I am using LZ4 to compress data before sending it over the network, using frames for compatibility. The case is that I have an array, part of which I want to send. The part however is not continuous, so I compress it on small chunks, one by one, using LZ4F_compressBegin, LZ4F_compressUpdate and LZ4F_compressEnd, calling LZ4F_compressUpdate multiple times. I use LZ4F_compressFrameBound to calculate the size of the buffer I need. It work OK in the beginning, but when the data becomes less suitable for compression and the compression ratio approaches 1 (or even worse), the library starts giving "**ERROR_dstMaxSize_tooSmall**". I thought this has something to do with the autoFlush option being turned on by default, but setting it to 0 didn't help.
Doubling the size of the buffer solved that, but it is a waste of memory. More importantly this means that the compression actually increases the size of the data by much, even though it happens rarely.

**Comment by t-mat** [comment]
Hi, @nbozhinov
Did you follow basic structure of [examples/frameCompress.c](https://github.com/Cyan4973/lz4/blob/master/examples/frameCompress.c)?
In your case, it seems you should use `LZ4F_compressBound()` instead of `LZ4F_compressFrameBound()`.  Because `LZ4F_compressFrameBound()` is dedicated calculation function for `LZ4F_compressFrame()`.
Please see ["Simple compression function"](https://github.com/Cyan4973/lz4/blob/d86dc916771c126afb797637dda9f6421c0cb998/lib/lz4frame.h#L128) section in lz4frame.h.

**Comment by nbozhinov** [comment]
Hi, @t-mat 
So LZ4F_compressFrameBound() should be used only in the case of compressing a single continuous memory block into a frame? Because from looking at the code I thought that LZ4F_compressFrameBound() calculates the same thing as LZ4F_compressBound() and the adds the frame header size, as it internally calls LZ4F_compressBound().
In my case should I use LZ4F_compressBound() and add to its result the header and footer sizes as it is done in  [examples/frameCompress.c](https://github.com/Cyan4973/lz4/blob/master/examples/frameCompress.c)? In the example those values are hard-coded. In [lz4frame.c](https://github.com/Cyan4973/lz4/blob/d86dc916771c126afb797637dda9f6421c0cb998/lib/lz4frame.c) I see a constant "maxFHSize" and the comments for LZ4F_compressBound() it is said that it "includes frame termination cost" (but not frame header size). So what I need for the buffer size is `LZ4F_compressBound() + maxFHSize`, am I correct?
If so I think that this should be better described in the comments, a right now the difference between the two functions is not very clear.

**Comment by Cyan4973** [comment]
Hi @nbozhinov 

@t-mat is right that the destination buffer should be sized with `LZ4F_compressBound()`,
but it could also be that there is a bug in this function
which makes it return a too short length in some edge cases.

Another possibility is that there might be an error in the compression process which makes it produce frames of much larger size than expected.

So there's probably something to investigate, using poorly compressible input.

To be fair, I'm surprised it only shows up today. It's supposed to be already tested quite extensively in `frametest`.

**Comment by t-mat** [comment]
> So LZ4F_compressFrameBound() should be used only in the case of compressing a single continuous memory block into a frame?

Yes.  It's the intention of the function.

> Because from looking at the code I thought that LZ4F_compressFrameBound() calculates the same thing as LZ4F_compressBound() and the adds the frame header size, as it internally calls LZ4F_compressBound().

Since `LZ4F_compressFrameBound()` overrides `LZ4F_preferences_t.frameInfo.blockSizeID` and `.autoFlush` as you see, it would be nice to treat these functions are designed for different purpose.

> In my case should I use LZ4F_compressBound() and add to its result the header and footer sizes as it is done in examples/frameCompress.c?
> So what I need for the buffer size is LZ4F_compressBound() + maxFHSize, am I correct?

You are right.

If you'd like to follow examples/frameCompress.c, since it combines header and first block to decrease number of I/O function call, you should add `15` (`maxFHSize`, maximum frame header size).
Although function's comment says [there is `LZ4F_MAXHEADERFRAME_SIZE`](https://github.com/Cyan4973/lz4/blob/d86dc916771c126afb797637dda9f6421c0cb998/lib/lz4frame.c#L388) but currently it has been overlooked :(

Technically, if you can flush the buffer after calling of `LZ4F_compressBegin()`, there is no needs to addition of these header and footer sizes.  See usage of [`LZ4F_compressBegin()` in lz4io.c](https://github.com/Cyan4973/lz4/blob/d86dc916771c126afb797637dda9f6421c0cb998/programs/lz4io.c#L519).

Personally, if you can pay some computational cost for I/O function call, I recommend latter one.  Because lz4io use same method and it must be safe in future version of LZ4.  Also I'm 100% sure possible smallest block size must be greater than `maxFHSize` :)

> If so I think that this should be better described in the comments, a right now the difference between the two functions is not very clear.

Good point.  We have many comments in the source, but there is no higher document structure.
If we have sections for "Single block frame compression" and "Multiple block frame compression", it'll be more clear.

**Comment by Cyan4973** [comment]
>  More importantly this means that the compression actually increases the size of the data by much, even though it happens rarely.

In worst case situations, data can increase by 0.4% during compression.
But this is only during compression.
On presenting the result, `LZ4F_` has some logic to discard such compressed block and send them uncompressed instead (+ some headers).

Another issue with `LZ4F_` is that it will buffer input data up to reaching block size, and flush an entire block when it's done. Block size != Input size (except when `autoflush` is selected).
So what can happen is that the compressed result can be way larger than input, because it also contains compressed data from previous invocations (up to one full block).

**Comment by Cyan4973** [comment]
I'm trying to reproduce the issue.
No luck so far.
Any sample code to start from ?

**Comment by Cyan4973** [comment]
I've finally been able to reproduce the issue.
Now onto correction ...

**Comment by Cyan4973** [comment]
OK, I have to retract my statement.
I did not reproduce the issue, I made a bad test.

But somehow, it's quite informative, and it may describe the issue you met.

I made a one-time buffer allocation, using `LZ4F_compressFrameBound()`,
but then, instead of compressing using `LZ4F_compressFrame()`,
I made multiple smaller incremental compressions, using `LZ4F_compressUpdate()` instead, and shaking the flow with a few random `LZ4F_flush()` here and there.

The problem is, `LZ4F_compressFrameBound()` is really made to work with `LZ4F_compressFrame()` only, because it uses the strong assumption that all blocks are going to be full up to the last one.
When using `LZ4F_flush()`, this condition is no longer respected. It introduces more blocks than expected, and with them more block headers. So the total of all these partially-filled blocks can effectively be more than `LZ4F_compressFrameBound()`.

`LZ4F_compressUpdate() / LZ4F_flush()` are meant to work in tandem with `LZ4_compressBound()`, which will only tell how much memory is required for the _current_ operation to work. There is no "global guarantee".

Note that the main idea behind the `flush()` function is to deliver all buffered data right now in order to send them immediately. That is to say, the destination buffer is supposed to become free after sending its content. If you use `flush()` without having such need, you leave some compression ratio on the table, due to increased fragmentation. I would rather recommend to _never_ `flush()`, _except_ when there is a need to transmit data immediately.

If you absolutely need to continue storing compressed data after a `flush()` and need to allocate a large enough buffer before-hand for all possible `flush()`, you may use `LZ4F_compressFrameBound()` as an indication, but then you need to add some margin to make up to the additional flushes (about +4 bytes per potential `flush()`).

> I thought this has something to do with the autoFlush option being turned on by default, but setting it to 0 didn't help.

This part contradict fuzzer tests.
Provided that compressed data is _never_ flushed, neither manually nor automatically, `LZ4F_compressFrameBound()` is a good indication to size the output buffer.
At least, in current refactored `frametests` within latest `dev` branch update, this use case is now tested, and has not failed once so far.
