### ISSUE TITLE
Clarify which BSD license is intended

### ISSUE THREAD

**Issue by mbrukman** [lz4/lz4#244]
Per the [README](https://github.com/lz4/lz4/blob/dev/README.md):

> LZ4 library is provided as open-source software using BSD license.

However, there are [several different BSD-style licenses](https://en.wikipedia.org/wiki/BSD_licenses), and it's not clear which one is intended here:
- 2-clause BSD license ("Simplified BSD License" or "FreeBSD License") – [OSI](https://opensource.org/licenses/BSD-2-Clause), [Wikipedia](https://en.wikipedia.org/wiki/BSD_licenses)
- 3-clause BSD license ("Revised BSD License", "New BSD License", or "Modified BSD License") – [OSI](https://opensource.org/licenses/BSD-3-Clause), [Wikipedia](https://en.wikipedia.org/wiki/BSD_licenses)
- 4-clause BSD license ("original BSD license") – [Wikipedia](https://en.wikipedia.org/wiki/BSD_licenses)

Could you please add a `LICENSE.txt` file to the repo containing the specific BSD license that is intended to apply to the code? 

Thanks!

**Comment by t-mat** [comment]
Good point, @mbrukman !  Also this issue is somewhat related to issue #115.  And actually we've discussed about same kind of license question/objection when Yann has hosted lz4 at Google code.

(1) For `README.md`, it's good to show more specific license name

```
-   LZ4 library is provided as open-source software using BSD license.
+   LZ4 library is provided as open-source software using BSD 2-clause license.
```

(2) For `LICENSE.txt`, I'm still not sure what license indication is the best for all of us.  Because technically, each part of LZ4 has been distributed under different licenses:

- (A) Codes in `lib/` (LZ4 library) are licensed under "BSD 2-Clause".  Please refer [`lib/LICENSE`](https://github.com/lz4/lz4/tree/master/lib/LICENSE) and each codes header part.
- (B) Codes in `programs/` (LZ4 command line utility) are licensed under "GPL Version 2".  Please refer [`programs/LICENSE`](https://github.com/lz4/lz4/tree/master/programs/COPYING) and each codes header part.
- (C) Codes in `contrib/djgpp/` are licensed under "BSD 2-Clause".  Please refer [`contrib/djgpp/LICENSE`](https://github.com/lz4/lz4/tree/master/contrib/djgpp/LICENSE).
- (D) Some directories and files are not licensed explicitly.

Personally it's okay to add root `LICENSE.txt` which just contains BSD 2-clause.  But I think usually people expects that `LICENSE.txt` affects all files in the repository.  So such root `LICENSE.txt` may cause confusion to the people who expects all files are distributed under same license.

Therefore, if we put `LICENSE.txt`, it may be complex one something like [xz's COPYING](http://git.tukaani.org/?p=xz.git;a=blob;f=COPYING;hb=HEAD) or [Snappy's](https://github.com/google/snappy/blob/master/COPYING).  For example,

```
(BSD 2-clause)

===

Content in programs/ directory is licensed differently.  See programs/COPYING for more information.
```

**Comment by mbrukman** [comment]
Here's a proposal:

* put the 2-clause BSD license (if that's what you intended) into `LICENSE.txt`
* add a `NOTICE.txt` file that lists all the other software in the repo and points to their respective license files for them
* update `README` to point to both `LICENSE.txt` and `NOTICE.txt` and provide high-level context, e.g.,

> LZ4 library is open-source and provided under the [BSD 2-clause license](LICENSE.txt); other software in this repository may have other licenses, please see [`NOTICE.txt`](NOTICE.txt) for more info.

Would this work?

For example, see how the [Apache Software Foundation uses `NOTICE` files](http://www.apache.org/dev/licensing-howto.html#overview-of-files) in addition to `LICENSE.txt`.

One issue with putting lots of license text into `LICENSE.txt` is that it prevents tools from automatically determining what license software is under and just makes it more confusing for users.

**Comment by Cyan4973** [comment]
I like the idea of an explicit license file per main directory, which is basically the current state.
Maybe we need a root file explaining this principle.

**Comment by Cyan4973** [comment]
Latest update in `dev` branch tries to provide some more license information, 
in the hope to improve clarity.

**Comment by heathermeeker** [comment]
Please reopen this issue and fix the license files.  By not fixing the license files you are confusing potential adopters. Please use full LICENSE.TXT files.  A BSD license needs the full text and a copyright notice.  You can find the 2-clause template here: https://opensource.org/licenses/BSD-2-Clause.  If you mix licenses in one repository, you should put the LICENSE.TXT file in the folder to which it applies.  Also, because you are mixing GPL code into a BSD repository, it would help to explain why that is OK.  Is it because the libraries are BSD and the GPL files are standalone processes? This entire repository got flagged by compliance tools as being GPL.

**Comment by sandeep-edb** [comment]
Also, the files in lib/ are BSD licensed but there is no mention of license in build/ which includes the VCXPROJ file. As per the top level license file: 
_This repository uses 2 different licenses :
- all files in the `lib` directory use a BSD 2-Clause license
- all other files use a GPLv2 license, unless explicitly stated otherwise_

**Comment by sandeep-edb** [comment]
Can someone please clarify if building and bundling the DLLs, include(from lib/ directory) on "Windows" also carry BSD license?

**Comment by Cyan4973** [comment]
> Can someone please clarify if building and bundling the DLLs, include(from lib/ directory) on "Windows" also carry BSD license?

Yes it does
