### ISSUE TITLE
How to correctly set LZ4F_preferences for high compression

### ISSUE THREAD

**Issue by scherepanov** [lz4/lz4#273]
Hi,
I am trying to do high compression with frame API LZ4F_compressFrame.
It require to pass LZ4F preferences to do higher compression than default.
I cannot find any docs how to set fields in LZ4F_preferences. I traces cli code and come with following, but it is not working.
Can you point to some docs where LZ4F_preferences setting is described, or can you look and tell what fields I am setting wrong.
As of now, I am passing nullptr for preferences, it is doing default compression and works just fine.
Thank you

/* High compression - not working! TODO
  LZ4F_preferences_t prefs;
  prefs.autoFlush = static_cast<blockMode_t>(1);
  prefs.compressionLevel = 3;

  //prefs.frameInfo.blockMode = blockIndependence;
  prefs.frameInfo.blockMode = static_cast<blockMode_t>(1);
  //prefs.frameInfo.blockSizeID = globalBlockSizeId;
  prefs.frameInfo.blockSizeID = static_cast<blockSizeID_t>(7);
  //prefs.frameInfo.contentChecksumFlag = streamChecksum;
  prefs.frameInfo.contentChecksumFlag = static_cast<contentChecksum_t>(1);
*/
  LZ4F_errorCode_t errorCode = LZ4F_compressFrame(comp_buf, max_compressed_size, source_buf, source_size, nullptr);

**Comment by Cyan4973** [comment]
The basic idea is that an `LZ4F_preferences` can be init with a `memset()`.
And then, it's possible to selectively init just a few fields, the ones that matter.
There should be no requirement to set them all.

So, if I do remember correctly, in your case, you could do : 

```
LZ4F_preferences_t prefs;
memset(&prefs, 0, sizeof(prefs));
prefs.compressionLevel = 3;
```

and I would expect it to work (albeit with all other settings set to "default").

I'm not sure why you selected the `static_cast` method rather than provided enums.
It shouldn't be a problem, but still.

There is an example in the [`examples`](https://github.com/lz4/lz4/blob/master/examples/) directory :  https://github.com/lz4/lz4/blob/dev/examples/frameCompress.c

It works, though it's not be focused on setting preferences.

**Comment by Cyan4973** [comment]
I've used this opportunity to add some comments in `lz4frame.h`,
in the hope that it helps reducing confusion.

**Comment by scherepanov** [comment]
Thanks for clarification!

**Comment by metaroxx** [comment]
Related to this, I'm not sure I understand what the role is of the blocksize as I couldn't find any documentation on this in relation to the actual size of the input i.e. what is the best / general recommendation on this parameter. Same goes for block mode and frame type.

Thanks

**Comment by Cyan4973** [comment]
In general, larger block compress better, but also consume more memory, for buffers.
So it's a trade-off.

Linked blocks compress better than independent block, so they are always recommended, _except if_ the target decoder only supports independent blocks. It's not uncommon : while the reference decoder supports both, many 3rd party decoders only support independent blocks.

Frame type should be irrelevant : it's only useful during decompression, in the case of mixed frames in a stream. It's a fairly advanced scenario, that should not matter in most circumstances.

Comments within `lz4frame.h` have been updated to reflect your question.
