### ISSUE TITLE
v1.7.4 build issue on Fedora

### ISSUE THREAD

**Issue by totaam** [lz4/lz4#274]
I'm using the lz4 specfile that we've used for a while now, which you can find here:
[lz4.spec](http://xpra.org/trac/browser/xpra/trunk/rpmbuild/lz4.spec)

And simply bumping from v1.7.3 to v1.7.4 now causes this failure:

    (...)
    compiling static library
    cc -O3 -I../lib -DXXH_NAMESPACE=LZ4_  -c -o datagen.o datagen.c
    compiling dynamic library 1.7.4
    cc -O3 -I../lib -DXXH_NAMESPACE=LZ4_ -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ../lib/lz4.o ../lib/lz4hc.o ../lib/lz4frame.o ../lib/xxhash.o bench.o lz4io.o lz4cli.o datagen.o -o lz4
    /usr/bin/ld: ../lib/lz4frame.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
    ../lib/lz4frame.o: error adding symbols: Bad value

Dumping the environment before calling make, I see that the Fedora rpmbuild calls make with:

    CXXFLAGS="-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic"
    LDFLAGS="-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld" FFLAGS="-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -I/usr/lib64/gfortran/modules"
    CFLAGS="-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic"

**Comment by Cyan4973** [comment]
I'm a bit surprised by the traces.
Though maybe that's because there is a race condition, though the lines do not appear in the expected order (in particular, `datagen.o` is not part of `lib`).

The linker stage complains about the absence of `-fPIC`. The strange part is that it never was part of `CFLAGS`, neither in the `Makefile`, nor in the Fedora environment variable, at least not in its visible part (maybe its implicit in another option).

I believe the problem probably comes from the new "release" mode, which is implicit when `make` is invoked without argument. I'll look into that.

**Comment by Cyan4973** [comment]
Latest update in `dev` branch should fix the mentioned issue

**Comment by Cyan4973** [comment]
I'll make a new released for this `Makefile` fix.

There is no source code change, only `Makefile`.

I wondered a bit about the better way to distribute this fix.
Keeping `v1.7.4`, replacing previous one ?
Creating `1.7.5` even though there is no source code change, hence requiring to bump `lz4.h` version number ?
Creating `v1.7.4.2`, introducing a 4th digit (that some scripts may not be prepared to see) ?

In the end, I guess I'll go for the 3rd solution.
The 1st one was tempting too, since `v1.7.4` has been live for only a few hours,
but it doesn't look "clean", and since you already downloaded it, maybe others did too.

**Comment by totaam** [comment]
Thanks for the fix, tested and working.
I would have gone for 1.7.5 myself, but 1.7.4.1 (why .2?) will do just as well.
Never change a source file in place, causes all sorts of problems with automated tools (checksums, etc)

**Comment by t-mat** [comment]
Personally, I :+1: for `1.7.5`.  There're some reasons

- It's good for consistency of presentation and meaning of version number (`MAJOR.MINOR.RELEASE` or `MAJOR.MINOR.PATCH`)
- "Version" has multiple meaning.  It means "version" of: The core library, CLI utils, Documents, Build/Test system, etc.
- "Release" also has multiple meaning.  It means "release" of blah blah...

Usually, small change of `Makefile` doesn't worth to release.  But since this issue and change is important, I think we should increment release/patch version.

**Comment by Cyan4973** [comment]
Added a comment regarding library version as suggested by @t-mat

**Comment by totaam** [comment]
Here's one of the problems of tagging on the "-2" at the end, look at the damage this does to the RPM spec file:
http://xpra.org/trac/changeset/14471/xpra
damage which will need to be undone when 1.7.5 comes out.

**Comment by Cyan4973** [comment]
good point @totaam.
I'm not sure to follow all the implications, but does that sound possible to define `{version}` as `1.7.4.2` instead of `1.7.4` ?
It seems it would have avoided adding these `.2` later in the spec file ?

**Comment by totaam** [comment]
@Cyan4973 I guess that would have worked - I didn't do that because I was trying to keep the package numbering scheme identical to the release string you had posted here:
https://github.com/lz4/lz4/releases/tag/v1.7.4.2
So "1.7.4-2" rather than "1.7.4.2".
But since the tar files already have dots in them, I guess I could have done the same!
