### ISSUE TITLE
When invoked without a terminal compressed sent to stdout

### ISSUE THREAD

**Issue by rgolde** [lz4/lz4#278]
On RHEL 6.3, when invoked via ssh 

> ssh root@vmkuku /usr/local/bin/lz4 /etc/passwd

compressed file sent to stdout.

Temp workaround

> ssh root@vmkuku /usr/local/bin/lz4 -m /etc/passwd

**Comment by Cyan4973** [comment]
According to `man lz4`, this is indeed an expected behavior : 
https://github.com/lz4/lz4/blob/dev/programs/lz4.1.md#difference-between-lz4-and-gzip

> _When no destination name is provided_, __if stdout is not the console__, it becomes the output

This is supposed to be useful in scenarios like this one : 

`lz4 file | consumer`

note that `lz4` also supports the `gzip`-like command `-c`, so this one also works : 

`lz4 -c file | consumer`

I suspect that in your use case (`ssh`), `stdout` is not considered to be a console, and that's how this behavior is triggered.

`lz4 -m` is not a "temporary" work around, it's the recommended method to trigger a command grammar closer to `gzip`. The last remaining difference is that source files are preserved by default, which can also be overriden with command `--rm`.

As a consequence, `lz4 -m --rm` shall behave the same as `gzip`.

**Comment by Cyan4973** [comment]
I've updated man page with the intention to make above points clearer : 

https://github.com/lz4/lz4/blob/dev/programs/lz4.1.md#difference-between-lz4-and-gzip

**Comment by rgolde** [comment]
:+1:

**Comment by Cyan4973** [comment]
man page updated in latest release
