### ISSUE TITLE
RFE: Add facility for finding the maximum size of a destination buffer for compressEnd and Flush

### ISSUE THREAD

**Issue by jonathanunderwood** [lz4/lz4#280]
With the frame protocol, if you disable autoFlush, and so enable buffering, when compressEnd is called, it's difficult to size the destination buffer appropriately, since you don't know how much data is buffered and so will be flushed on calling compressEnd. Therefore, having facility to find out how much data is currently buffered would be really helpful.

**Comment by jonathanunderwood** [comment]
Actually, a simpler solution would be to expose the maximum block size in the API. In other words, expose the logic in `LZ4F_getBlockSize` via the API. Then, when calling compressEnd, one could ensure that the destination buffer size was equal to something like `LZ4F_getBlockSize + 8` (where 8 is the max footer size).

**Comment by Cyan4973** [comment]
Regarding the last request, block size was expected to be known by the calling process, since it's set as part of compression settings. But when no preference is provided, default ones take over, and the caller may not know it.
(hint : it's 64 KB).

Regarding the original request, to know how much data can be flushed when calling `compressEnd` : 
this is supposed to be the goal by `LZ4F_compressBound()`. It includes "end of frame cost".
If you don't want to manually set preferences to tell there is going to be a flush (which `compressEnd` implies), you can fake a `srcSize` of `1`. This will be enough to provide a worst case evaluation of one full block.

**Comment by jonathanunderwood** [comment]
> Regarding the last request, block size was expected to be known by the calling process, since it's a member of compression settings. However, when no preference is provided, default ones take over, and you're right the caller may not know it. (hint : it's 64 KB).

Yep, I realize that it would be possible to basically reproduce the logic of `LZ4F_getBlockSize` in code consuming LZ4. But, the nice thing about exposing that thru' the LZ4 API is that it makes a guarantee for the future if the implementation changes, and so help prevent breakage. I really think it would be a nice addition to the API.

> Regarding the original request, to know how much data can be flushed when calling compressEnd :
this is supposed to be the goal by LZ4F_compressBound(). It includes "end of frame cost".
If you don't want to manually change preferences to tell there is going to be a flush (which compressEnd implies), you can fake a srcSize of 1. This will be enough to provide a worst case evaluation of one full block.

Perfect! This gets me exactly what I want - I had missed the possibility of faking srcSize. Might be good to add this to the documentation.

**Comment by Cyan4973** [comment]
A stated in #290 , latest update in `dev` branch makes it possible to request `LZ4F_compressBound()` with a `srcSize` of `0`. In which case, it provides the upper bound of `*flush()` or `*End()` operations.

**Comment by jonathanunderwood** [comment]
I think that with the change in #290 we can close this.
