### ISSUE TITLE
Where to stop if I don't know where the input limit is?

### ISSUE THREAD

**Issue by imgtec** [lz4/lz4#281]
Hi, I am making a decoder which prototype same with memcpy, so I can replace
the memcpy with the decoder in my projects. this decoder decode one single block.
       void *memcpy(void *dest, const void *src, size_t n);
@ src the block data start address, (no frame)
@ dest output
@ n output size, (block size)
I can know the output size (blocksize) but I have no idea about the input size.
The document says, 
>1. The last 5 bytes are always literals
>2. The last match must start at least 12 bytes before end of block

according to above, the (2.) is useless for me. the (1.).
should if test like below after match copy or somewhere else?
if(j+5>blocksize) {   // j is output index
 copy (blocksize-j) bytes to output.
 decode done.
}

**Comment by Cyan4973** [comment]
It seems you have a use case which could benefit from [`LZ4_decompress_fast()`](https://github.com/lz4/lz4/blob/dev/lib/lz4.h#L199)

`LZ4_decompress_fast()` only needs the decompressed size.
It doesn't need the input size.
In fact, it will guess it, and provide it as return value.

Note however that `LZ4_decompress_fast()` is not protected against erroneous or malicious input.
Precisely because it doesn't know the input size, it may read an unknown amount of byte.
