### ISSUE TITLE
LZ4F_compressBound result too small (autoFlush=0)

### ISSUE THREAD

**Issue by vtermanis** [lz4/lz4#290]
In [r131](https://github.com/lz4/lz4/releases/tag/r131), `LZ4F_compressBound(0, prefs)` returns a size which allows un-flushed (with `autoFlush=0`) data + "end" to be written. In [v1.7.4](https://github.com/lz4/lz4/releases/tag/v1.7.4)  `LZ4F_compressBound(0, prefs)` returns just __4__ if `autoFlush` is disabled and a single partial block exists. Subsequently calling `LZ4F_compressEnd` with a buffer of size 4 produces a `ERROR_dstMaxSize_tooSmall`, as expected.

With [this example](https://gist.github.com/vtermanis/70cf54aad096e8c870eedf59efad228e) (see line 50), using r131 I get:
```
update output length: 65544
end output length: 65544
```
.. and with v1.7.4:
```
update output length: 65544
end output length: 4
LZ4 error [-11] ERROR_dstMaxSize_tooSmall
```

I'm guessing the slightly changed logic in `LZ4F_compressBound_internal` might have something to do with this or am I doing something silly (which used to somehow work previously)?

**Comment by Cyan4973** [comment]
This is a good description of what is happening @vtermanis .

I believe we have a problem of definition regarding `LZ4F_compressBound()`.

Initially, it is designed as a way to provide the maximum output size of `LZ4F_compressUpdate()`.
As far as I know, for this objective, it works correctly.

However, there is also a need to know maximum output size when invoking `LZ4F_compressEnd()`, or `LZ4F_flush()`.
But there is no dedicated method for these use cases, so it's natural to turn to `LZ4F_compressBound()`. Problem is, this function was not designed for this scenario.

For `LZ4F_compressBound()` to give a correct answer for `*End()` and `flush()` scenarios, one needs to tell that `autoflush` is enabled. In which case, the worst case estimation should be correct.

Alas, most people don't change compression parameters before invoking `LZ4F_compressBound()`, so the result they get is not valid for `*End()` or `*flush()`.

There is another way to make `LZ4F_compressBound()` useful for flush or end scenarios : pretend that `srcSize` is `1`. In which case, it will consider the worst case scenario, which is this 1 byte triggers a full block flush.
But this method is quite "hackish", it does not feel natural.

So I guess something is missing.

We have multiple possibilities to try to solve this situation : 
- Educate users, make it clear that in order to get the correct `LZ4F_compressBound()` for `*End()` of `*flush()`, one needs to set compression parameter `autoflush` to 1.
- Always use `autoflush==1` within `LZ4F_compressBound()` even if stated otherwise, making it compatible with `*End()` and `*flush()`, but also providing larger than necessary buffer sizes for other cases (`LZ4F_compressUpdate()`).
- Ensure `LZ4F_compressBound()` always answer with a minimum of one full block, since it's the maximum possible size that `*End()` and `*flush()` can possibly trigger.
- Create a new `*compressBound()` function dedicated to `*End()` and `*flush()`.

For discussion

**Comment by vtermanis** [comment]
Thank you @Cyan4973 for the quick response! A few questions/observations and one more suggestion:

1. **educate**
  This one would require existing code relying on `LZ4F_compressBound`'s old behaviour to be updated (e.g. I assumed I was doing the right thing [like another user](https://github.com/darkdragn/lz4tools/blob/4b13390c5d8d2f8d70c262b5e63b2491f4d662b5/src/python-lz4f.c#L221)) - maybe a non-minor version bump would be required, so existing code does not start to misbehave.
2. **always pretend autoflush==1**
  Is this the closest to the old behaviour (r131)? Or is that (3)?
3. **always minimum of one block**
  I assume this, like (2) overestimates how much is needed in most cases.
4. **new end size method**
  I'm guessing this is similar to (1), in that users would have to realise behaviour has changed and they should be using a new method. (I assume there's no nice compile-time way to warn/error to indicate such a change or is there maybe?)
5. **pretend autoflush==1 but only if supplied length is zero** (or is this stupid?)
  This would behave the same as before in all other cases and I'm guessing would only result in too much being allocated if someone has logic which results in compressBound + update call with zero length input
6. **supplied length of zero indicates want size for (end + remaining) only**
  Similar to (5) but won't over-estimate needed buffer size. I assume this would still work even if users called update instead of end afterwards. (Or is this exactly the same as 5?)

Peronally I'm happy with (1) or (4) but just wondering whether other projects might prefer something backwards compatible.

**Comment by vtermanis** [comment]
Ah sorry, didn't realise #280 was related - should have posted this in there probably.

**Comment by Cyan4973** [comment]
I like your suggestion 5.
It could be easily documented (in code comments).

**Comment by Cyan4973** [comment]
Just pushed to `dev` branch a new version of `LZ4F_compressBound()` which implements suggestion 5

**Comment by vtermanis** [comment]
This seems to work well: I've only made [a small change to my code](https://github.com/Iotic-Labs/py-lz4framed/commit/5190461b8248dadb7d9040cf60b6a4d229a15e08#diff-9f36d381d1a0203e3840dd665fdd2a39) to use the new `LZ4F_HEADER_SIZE_MAX` constant.
However, I've noticed a performance change in my unit tests for high compression levels (10+). I'll post a comparison of 70526a1 VS r131 in a bit.

**Comment by vtermanis** [comment]
One last thing: Any idea when the next release (v1.7.5 I'm guessing) might be made? (Just so I have a vague idea when to come back to update py-lz4framed with your new version.)

**Comment by Cyan4973** [comment]
Let's try early January 2017
