### ISSUE TITLE
decompressing/recompressing only a portion of data

### ISSUE THREAD

**Issue by DavidBrenner3** [lz4/lz4#325]
My application is storing its data as animation frames - individually compressed with LZ4.
But usually there is little difference between frames. So, if I compress them as a hole, it requires 2x..6x times less memory storage space (!)
But this way is difficult to read and very difficult to write each frame when it has to be modified.
It would be very useful to have specially designed functions for decompressing/recompressing only a portion of data. Just like Winrar/Winzip can read/write a file into a multifile archive.
I know, it would be a speed and memory usage penalty (hope not that severe), but sometimes it's worth it. Like 2x..6x times worth xD

Is it possible to implement?

Regards,
David

**Comment by Cyan4973** [comment]
Somehow...

[LZ4 frame format specification](https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md) allows frames formed of independent blocks.
Independent blocks can be decompressed individually, so that sounds pretty close to your request.
Blocks can have any size up to a maximum, specified in the frame header (64 KB, 256 KB, 1 MB or 4 MB). Blocks don't need to be full, but as a rule of thumb, the larger they are, the better the compression ratio.
By default, the CLI uses 4 MB independent blocks, and it's possible to change block size on command line (see command `-B#`).
The API does it the other way round : by default, blocks are linked and have a maximum size of 64 KB. But there also it's possible to change these settings by selecting appropriate options.

So the theoretical capability is there ... but the code isn't.
One would need to create new functions designed to take advantage of these capabilities.

Now, another solution is to cut input into multiple independent frames, and add some metadata to manage that. This is exactly what a splittable format like @CarloMedas' [4MC](https://github.com/carlomedas/4mc) is proposing. The format is documented, and API are provided. Though the reference implementation uses Java.
