### ISSUE TITLE
High compression time for specific data

### ISSUE THREAD

**Issue by c-morgenstern** [lz4/lz4#339]
Usually LZ4(HC) compresses small data chunks within a few milliseconds, even with LZ4HC_CLEVEL_MAX.
The attached 100kb file takes around 4 seconds though. It's extracted from a 3 MB file which takes 60 seconds. On LZ4HC_CLEVEL_OPT_MIN and below even the 3 MB file just takes a few milliseconds as expected. Is this a fixable edge-case?
I'm using the 1.7.5 64 bit release and LZ4_compress_HC with properly set buffer size.

[dump.txt](https://github.com/lz4/lz4/files/867217/dump.txt)
(Not a text file, but I got an error when trying to upload it zipped and/or with other extensions)

**Comment by Cyan4973** [comment]
The new compression levels 11 and 12 use a new algorithm, called "optimal parser", which is supposed to bring the result closer to "maximum possible" using lz4 format.
As a consequence, the code is different from previous levels <= 10.
Degenerated corner cases can be different too.

The situation is not static though, and we can modify the algorithm to better cope with their degenerated cases. Sometimes at the cost of a bit of compression ratio.

Thanks for the sample. I used it in benchmark mode to spot behavior differences : 

```
 9#dump.txt          :     98304 ->     10537 (9.329),  32.0 MB/s ,9830.4 MB/s
10#dump.txt          :     98304 ->     10537 (9.329),   1.0 MB/s ,9830.4 MB/s
11#dump.txt          :     98304 ->     10561 (9.308), 179.4 MB/s ,10922.7 MB/s
12#dump.txt          :     98304 ->     10520 (9.344),   0.0 MB/s ,10922.7 MB/s
```

Both levels 10 and 12 take a strong hit. Level 12 takes an extreme one.
Levels 9 and 11, in contrast, behave pretty well, with the side effect that level 11 ends up compressing less than levels 9 and 10.

My guess is that the sample file contains a lot of repetitive data, short segments a few bytes long.
This makes the search for the "better match" cost forever, as the number of candidates is very high.
This is only stopped thanks to quick heuristics which stop the process when it seems to cost too much.
Levels 10 and 12 are special versions of, respectively, levels 9 and 11, which basically throw away these protections.

Levels 10 could be refactored to include something equivalent, even if it costs "a bit of compression". After all, it's now an "intermediate level" (it used to be the former max level 16...).

For levels 12, it's more difficult, because we want to keep it as a "maximum ratio mode", close to or reaching the best possible ratio for lz4. So sacrificing even a few bytes is a tough call for this mode.
But who knows, maybe with more tests and new ideas, it will be possible to cost less than today without sacrificing ratio.

That level 11 compresses less than levels 8 and 9 is a bit of a bummer.
I'll see if it's possible to adapt heuristics to limit such possibilities, though we want to keep it an "intermediate mode", which, on "normal" files, produce a speed intermediate between 10 and 12 (therefore, not too close from 12).

Lots of things here, now onto work to see what could be improved ...

**Comment by c-morgenstern** [comment]
Thanks for these insights. "Maximum possible with the lz4 format" is indeed not what I want for my use-case, if it can cause performance hits like in this example. I'll avoid those two levels then.

**Comment by Cyan4973** [comment]
Latest update in `dev` branch
features compression speed improvements for High Compression mode.

The impact is especially dramatic for the [pathological sample](https://github.com/lz4/lz4/files/867217/dump.txt) provided in this thread.
If you remember [previous performance numbers](https://github.com/lz4/lz4/issues/339#issuecomment-289105199), here are the results with the new version : 

```
 9#dump.txt         :     98304 ->     10537 (9.329), 144.8 MB/s ,10922.7 MB/s
10#dump.txt         :     98304 ->     10537 (9.329), 146.9 MB/s ,10922.7 MB/s
11#dump.txt         :     98304 ->     10533 (9.333), 221.9 MB/s ,12288.0 MB/s
12#dump.txt         :     98304 ->     10520 (9.344),  17.9 MB/s ,12288.0 MB/s
```

The fix will solve any other file featuring some kind of short repetitive pattern.

It will be part of next release.
