### ISSUE TITLE
Unclear what stableSrc in LZ4F_decompressOptions_t actually does

### ISSUE THREAD

**Issue by jonathanunderwood** [lz4/lz4#350]
In lz4frame.h the `stableDst` member of the `LZ4F_decompressOptions_t` struct has the following comment:

```
/* guarantee that decompressed data will still be there on next function calls (avoid storage into tmp buffers) */
```

But the comments for `LZ4F_decompress` state:

```
 * `dstBuffer` content is expected to be flushed between each invocation, as its content will be overwritten.
 * `dstBuffer` can be changed at will between each consecutive function invocation.
```
These seem to me to be entirely contradictory statements. It's therefore entirely unclear to me what `stableDst` is actually signifying. I've stared at the code, particularly around [these lines](https://github.com/lz4/lz4/blob/dev/lib/lz4frame.c#L1408) but can't fathom it. 

Could you clarify? If I can get to the bottom of it, I'll submit a patch which fixes up the comments so they're clearer.

**Comment by Cyan4973** [comment]
That's a good point.
Indeed, the normal mode is that `dstBuffer` is expected to be flushed between each invocation.

When setting `stableDst` to `1` (note that it's _not_ `stableSrc`),
it changes the expected behavior.
Now, data previously decoded into `dstBuffer` is presumed to be still there,
at least for the last 64 KB decoded.

So it's basically one behavior or the other.
Comments can probably be improved to explain this behavior more properly.

**Comment by jonathanunderwood** [comment]
But, looking at the code in lz4frame.c, if `stableDst` is set to 1, and you pass in `dstBuffer` pointing to the start of the 64kB of previous data, it will be overwritten, I think. Is that the intention?

**Comment by Cyan4973** [comment]
When `stableDst` is set to `1`, the API expects to find previously decoded data still present at the position where it was decoded, unmodified.
It doesn't test if the `dstBuffer` pointer passed in argument respects this condition. Respecting the contract is part of user responsibility.

So if `dstBuffer` points at the start of the 64 Kb of previous data, decompression will likely fail, if there are long matches, due to overwrites. 

At the very least, consider providing a small margin, like "64 KB + 64 bytes". It might even work with 16 bytes of margin.

**Comment by Cyan4973** [comment]
I've modified a bit `lz4frame.h` api comments, in the hope to clarify points raised by your question.

**Comment by borbmizzet** [comment]
When the comment for stableDst says "last 64 KB", does this mean dstBuffer-64KB or the absolute memory address the previous 64KB was decompressed to?
