### ISSUE TITLE
r126 and r127 point to the same commit

### ISSUE THREAD

**Issue by MarkusTeufelberger** [lz4/lz4#365]
Is this an error or is this intentional? What has changed from r126 to r127?

**Comment by Cyan4973** [comment]
That's a good question @MarkusTeufelberger .
I don't remember _at all_.

r126 and r127 are indeed exactly the same, both in code and release comment.
This has to be some sort of error, although which one exactly, I don't know.

_Edit_ : [NEWS](https://github.com/lz4/lz4/blob/dev/NEWS#L93) gives the solution.
This used to be back in the time where the code was available on both Google Code using svn, and github using git. And I probably recently changed the source of truth, so github became the reference, and Google Code the mirror (used to be the reverse some time before that).

In the duplication into Google Code, one file got missing, making the r126 release faulty.
And since `lz4` started its life on Google Code, many people (and distros) would get it from there.

So the svn repo was fixed, and in doing so, it automatically bumped the release number to r127. And now there was an issue with r127 on Google Code not existing on github ...

Well, anyway, old story, and it can't happen anymore.

Besides, I recommend anyone to switch directly to latest release, v1.7.5, and just forget about these old ones.

**Comment by MarkusTeufelberger** [comment]
I guess there's nothing more to do here then, thanks for the information.
