### ISSUE TITLE
lz4/dev r131 -BD DOESNOT help improving compression ratio

### ISSUE THREAD

**Issue by lorenmeng** [lz4/lz4#366]
In r131 version, when use lz4 CLI and enable blocklink mode(-BD), it does not improve compression ratio.
my payload is cantrbry. which you can download http://corpus.canterbury.ac.nz/descriptions/

following is how I use it:
    ./lz4 -B4 -BD alice29.txt
    Compressed filename will be : alice29.txt.lz4 
    Compressed 152089 bytes into 88746 bytes ==> 58.35%  

    ./lz4 -B4  alice29.txt
    Compressed filename will be : alice29.txt.lz4 
    Compressed 152089 bytes into 87023 bytes ==> 57.22%
can anyone explain this.

**Comment by lorenmeng** [comment]
I just pull newest code(tag v1.7.5), still have this problem

**Comment by Cyan4973** [comment]
I made a few tests regarding `-BD` mode, and it seems to work as intended.

The effect you observe is related to "small block" special optimizations.

When LZ4 must compress a block of data <= 64 KB, it gets into "small block" mode, providing it with a small boost to compression ratio and speed.
This is what happens when selecting `-B4`, aka "independent blocks of size 64 KB".

Blocklink mode `-BD` breaks the guarantee that data to compress will necessarily be < 64 KB.
Total amount to compress can now be any size, it's no longer limited to block size alone.
So now LZ4 uses "normal" compression tables, no more "small block" boost.

So which one is better then ? `-B4` or `-B4 -BD` ?
Well, it will depend on source file.
On average, the larger the source file, the more `-BD` will prevail.
And conversely, on "smaller" files, `-B4` alone may prevail.
Ultimately, it really depends on data source itself. It's always possible to craft a contrived use case which favor either `-B4` or `-BD`.

Note that this effect is only possible with `-B4`.
On any other block size, `-BD` is always a win for compression ratio.
