### ISSUE TITLE
Problem trying to wrap LZ4 streaming API into C#

### ISSUE THREAD

**Issue by dimzon** [lz4/lz4#388]
1) I'm splitting input data by 4kb chunks (4kb or less)
2) I allocate 128 kb for dictionary 
3) after each LZ4_compress_fast_continue I invoke LZ4_saveDict
```
            public override void Write(byte[] buffer, int offset, int count)
            {
                var alloc1 = GCHandle.Alloc(_outBuffer, GCHandleType.Pinned);
                var alloc2 = GCHandle.Alloc(buffer, GCHandleType.Pinned);
                try
                {
                    while (count>0)
                    {
                        var size = Math.Min(BufferSize, count);
                        var bytes= LZ4_compress_fast_continue(_str, Marshal.UnsafeAddrOfPinnedArrayElement(buffer, offset),
                            Marshal.UnsafeAddrOfPinnedArrayElement(_outBuffer, 0), size, _outBuffer.Length, 1);
                        var lz4SaveDict = LZ4_saveDict(_str, _dict, DictSize);
                        Debug.Assert(lz4SaveDict!=0);
                        count -= size;
                        offset += size;
                        _outStream.Write(_outBuffer,0,bytes);
                    }
                }
                finally
                {
                    alloc2.Free();
                    alloc1.Free();
                }
            }

```

1) Resulting file is much bigger than lz4.exe compression result
2) lz4.exe can't decode resulting stream

what I'm doing wrong?

**Comment by Cyan4973** [comment]
`LZ4_compress_fast_continue()` produces "raw" lz4 blocks, as defined in [lz4 block specification](https://github.com/lz4/lz4/blob/dev/doc/lz4_Block_format.md). It doesn't produce any metadata (typically the compressed size of each produced block). These metadata are required to properly decode.
This design is on purpose : it allows each program to create its own metadata scheme. Since usage varies, optimal scheme vary too.

If you want compliance with [lz4 frame specification](https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md), which is used by the cli, you can either delegate this work to `lz4frame` API, or do it manually by following the specification.
