### ISSUE TITLE
Need more ratio friendly benchmarks

### ISSUE THREAD

**Issue by svnpenn** [lz4/lz4#395]
http://github.com/lz4/lz4#benchmarks

I get that LZ4 is all about speed, but ratio is important when considering a
compressor. For example, the highest ratio on the list now is zlib, whereas
several old and new compressors and easily beat this. Using this file
(10,712,375 bytes):

http://cygwin.mirror.constant.com/x86_64/setup.ini

Here is "lizard -40" (ratio 3.324):

~~~
$ lizard -40 -f setup.ini
Compressed 10712375 bytes into 3222221 bytes ==> 30.08%
~~~

Here is "xz -0" (ratio 3.513):

~~~
$ xz -0 setup.ini; ls -l setup.ini.xz
-rw-r--r-- 1 Steven None 3049080 Sep  4 07:13 setup.ini.xz
~~~

**Comment by Cyan4973** [comment]
Right, homepage's benchmark table is a bit old and could be updated.

Indeed, LZ4 is primarily about speed.
It's pretty clear that several other algorithms can compress more, given enough time.
But it's not the point, and I don't want to confuse users with an overwhelming list of figures.
Also don't confuse LZ4 homepage with a thorough comparison exercise. It's not, it's just a concise presentation of LZ4 strengths, which never intended to be a full analysis. Other websites can do such exercise much better, preferably when run by 3rd parties deemed "neutral" in the comparison.

I get it that `lz4hc` is listed, but it's not for its compression speed. The only reason to use `lz4hc` is for its decompression speed, typically in asymmetric scenarios (compress once, decompress many) such as read-only assets. Stronger algorithms can have fast settings competitive with `lz4hc` compression speed, but such setting is simply not the right fit for the implied scenario, since in such case compression time does not matter. The only important data points are compression ratio and decompression speed. Here also, it's not valuable to displays alternatives which are 30x slower. It's just a different category (and there is nothing wrong with strong compressors).

`xz` is not in the list I intend to show up anyday on LZ4 homepage. `xz -0`, the fastest setting, is about 30 MB/s on my laptop, that's definitely too slow to be considered "fast". Not mentioning the decompression speed < 100 MB/s. 

`lizard` can be a much better fit. This one might be added in the future, and just needs to mature a bit.
