### ISSUE TITLE
Clang 3.9.0 -Wcomma warning in lz4.c

### ISSUE THREAD

**Issue by rvandermeulen** [lz4/lz4#398]
Trying to build lz4 1.8.0 with clang 3.9.0 and -Werror enabled, I'm getting a failure on the below line:
https://github.com/lz4/lz4/blob/dev/lib/lz4.c#L619
`while (matchCode >= 4*255) op+=4, LZ4_write32(op, 0xFFFFFFFF), matchCode -= 4*255;`
> lz4.c:619:49: error: possible misuse of comma operator here [-Werror,-Wcomma]
> lz4.c:619:78: error: possible misuse of comma operator here [-Werror,-Wcomma]

**Comment by Cyan4973** [comment]
Thanks for notification @rvandermeulen .

The code is not wrong here, just `gcc -Wcomma` doesn't like it.
`Wcomma` is a compilation flag I've not used so far.
I would need to know at which `gcc` version it was added to consider it.

**Comment by rvandermeulen** [comment]
Sorry, I misfiled it against gcc originally. It was actually against clang 3.9.0. I haven't tested against newer versions to see if it still reproduces, but I would assume so.

**Comment by Cyan4973** [comment]
OK, clear, indeed the new title is more accurate.
I tested this flag with a bunch of `gcc` compilers, none of them would accept it.
For `clang`, it's only recognised starting v3.9.0, older versions don't know it.

So it's quite recent, and it's an issue, because it's not possible to use this flag in the standard build system, since it would fail on too many configs.

But, as I do have locally a compiler which accepts this flag, I can fix it using this version.
To reduce probability that such issue appear again in a future update, I would need a CI test supporting this flag, hence using `clang` >= v3.9.0.
Travis CI might support such setting.
That would be great, as this specific flag could then be tested regularly.

**Comment by Cyan4973** [comment]
`clang` tests on TravisCI work : 
https://travis-ci.org/lz4/lz4/jobs/273954990#L591

**Comment by Cyan4973** [comment]
I've updated the source code in `dev` branch to silence those warnings.

I'm not completely sure if this is really useful (not _all_ warnings add value).
But since the transformation was straightforward, and the new code does not feel worse than its predecessor, since it's also possible to validate the flag on travis CI, I'm fine with it.

**Comment by rvandermeulen** [comment]
That was obscenely fast. Thanks for the quick work!
