### ISSUE TITLE
ERROR: ??  cppcheck tool finds possible error

### ISSUE THREAD

**Issue by aj664** [lz4/lz4#404]
cppcheck reports:    ERROR:   Shifting 32-bit value by 32 bits is undefined behaviour.

line 316  of  lz4.c              if (!(val>>32)) { r=4; } else { r=0; val>>=32; }

in func:  static unsigned LZ4_NbCommonBytes( reg_t val)

my version notes indicate:  https://github.com/lz4/lz4/releases/tag/v1.7.4.2 

can anyone confirm/deny this is a problem?

(also, LOL, wouldn't it be funny, given the issue number for this post, if it was Not Found).

**Comment by t-mat** [comment]
Thank you for the report!
But since [`sizeof(val) == 8`](https://github.com/lz4/lz4/blob/v1.7.4.2/lib/lz4.c#L319), number of bits of `val` is 64bit.  See also [6.5.7 [Bitwise shift operators] in N1570 (C11 standard)](http://iso-9899.info/n1570.html#6.5.7) for the details.
Therefore, your tool's report is false positive.  Please report it to the author of the tool.

**Comment by Cyan4973** [comment]
@t-mat answer is correct : 
while shifting by 32 on a 32-bits value is indeed undefined behaviour,
this code can only be triggered in 64-bits mode, so `val` is necessarily 64-bits.

I'm not too surprised that some static analyser cannot infer this information from the code,
though to give another example, `scan-build`, `clang`'s static analyser, do not have this problem.

Anyway, to please any static analyser with same limitation, I've rewritten the shift in latest `dev` branch update, f6b31bf0d082315103d2fb5fc8f2094be567bb63, so that now it pretends to shift by 16 on a 32-bits value (which doesn't matter since this code is not even generated in 32-bits mode).
Note that I have not been able to test `cppcheck` on the new code, as it only runs on Windows and I don't have one around right now. You might want to check it on your system.

While it fixes the issue for `cppcheck` on `lz4`, it's a good idea to report the issue to `cppcheck` maintainer. The [project webpage](http://cppcheck.sourceforge.net/) prominently advertises a "zero false positives" policy, and this a false positive. Moreover, `scan-build` example proves it is possible to avoid it.
