### ISSUE TITLE
Simple pathological worst case compression

### ISSUE THREAD

**Issue by fmadio** [lz4/lz4#413]
Found a surprisingly simple pathological worst case compression sequence. Which is a simple incrementing 32bit integer worth of data. Even with HC MAX its unable to compress the data at all. Example attached.

Guess the minimum match size is 4 Bytes, I changed MINMATCH  to 2 bytes to try get some compression but the compressor segfaults. Is there any other tuning suggestions? As Im compressing an in-memory data structures there`s alot of unique 16bit and 32bit integers that are sparsely populated (e.g. only a few bits set out of 32).

[block.zip](https://github.com/lz4/lz4/files/1427317/block.zip)

**Comment by Cyan4973** [comment]
Indeed, such use case is enough to ensure data will not be compressed by LZ4 alone.
As you suspected, that's because LZ4 only compresses exact matches of at least 4 bytes. An increasing list of 32-bits numbers evades this property.

It's not possible to change `MINMATCH`. LZ4 is hard-coded for 4-bytes matches.

If you know that you are going to compress a list of 32-bits values, there are a few things you can do to improve compression ratio : 
- For a monotonically increasing list : make each value a delta from previous one. A simple incrementing 32-bits integer will become a bunch of `0x00000001`, which will be trivially compressed.
- For less "obvious" cases, which means most of them, consider using [blosc](https://github.com/Blosc/c-blosc) as a pre-filter for tabular data. This is cumulative with previous suggestion.

**Comment by fmadio** [comment]
Thank you for the information. Ended up adding an optional 16B transpose operation to gather LSB entropy and optional delta encoder. However on real data it rarely beats the stock encoder. Quite surprised actually, my assumptions about the patterns in the data were wrong. Thank you for an amazing library.
