### ISSUE TITLE
return code of LZ4_decompress_safe doesn't understand

### ISSUE THREAD

**Issue by pahome** [lz4/lz4#421]
I use LZ4_decompress_safe to decompress and don't understand the return code even if I read the doc of lz4.h.
I compressed many data and put them all in ibp(input buffer) and decompress them and put to obp(output buffer)
here is my partial code:
```
//ibp->data is a buffer and length=36864
//obp->data is a empty buffer and length=40960
//insize is 36864
//outsz = 40960
rc = LZ4_decompress_safe(ibp->data, obp->data, insize, outsz);
print rc;//rc = -36860 why?
```

I don't know why is -36860?
I need know the compressed block size(the boundary)?

**Comment by Cyan4973** [comment]
According to doc : 
>     return : the number of bytes decompressed into destination buffer (necessarily <= maxDecompressedSize)
>              If destination buffer is not large enough, decoding will stop and output an error code (<0).
 >              If the source stream is detected malformed, the function will stop decoding and return a negative result.

This is an error code.
It just tells that decompression stopped due to an error, though it doesn't tell which one. Data could be corrupted, or output buffer could be too small for example.
The value is a hint at where the error probably happened. In this case, it seems to be close to the end of input.

Try enlarging the output buffer. It might be a little too small.

**Comment by pahome** [comment]
how to determine the best size of output buffer?

**Comment by Cyan4973** [comment]
> how to determine the best size of output buffer?

It's not possible using LZ4 block format directly.
It's part of metadata that must be sent alongside the block by the application, should it matter.

For example, some applications rely on the fact that all blocks are going to be < 16 KB, so they can safely allocate a 16 KB `dst` buffer, knowing in advance that it's enough for any properly formed data (and if it's not, data is presumed corrupted).
Other applications send the size of data with each block in a custom header.

For this specific case, if you know that decompressed object is 40960 bytes, then `maxDecompressedSize = 40960 bytes` should work.

Since the error happened near the end of the compressed block, I would suggest to enlarge the `dst` buffer a little bit, as a test, to see if it's enough to decompress data. `LZ4_decompress_safe ()` result will tell you how many bytes were decompressed, so it will be possible to check if the result is 40960.
`maxDecompressedSize` just needs to be `>= decompressedSize`, so it does not have to be precise.

**Comment by danielhrisca** [comment]
Hello, I'm also getting an error code -4 when I try to decompress an LZ4 block. 

The block starts with the following bytes

`04 22 4d 18 40 40 c0 fa 8e 00 00 f1 03 00 60 9a 3e b7 d4 a2 ...`

I'm using the dev branch code from this commit https://github.com/lz4/lz4/commit/a018abc07a3018371625a265f195c4fafbf1f99d as a submodule in my repo https://github.com/danielhrisca/asammdf/tree/lz4_c specifically [here](https://github.com/danielhrisca/asammdf/blob/b8e7ed119edb4d49463a2a0b20675483f19f3455/src/asammdf/blocks/cutils.c#L2164) where I know the size of the compressed and uncompressed blocks.

After calling the function the output buffer looks like this

`22 4d 18 40 40 c0 fa 8e 00 00 f1 03 00 60 9a 3e 00 00 00 00 ...`

Any idea what could be problem? Thanks!

**Comment by danielhrisca** [comment]
With a clear head after the week-end I've realized that I was using the block decompression function but the input byte stream was a compressed frame.
