### ISSUE TITLE
Detecting end of frame

### ISSUE THREAD

**Issue by jonathanunderwood** [lz4/lz4#447]
It would be really helpful to have some way to detect when the end of frame has been reached during frame decompression. I can't immediately see a way to do that from either:

* The source compressed data - one possibility would be to look for a 4 consecutive zero bytes. But, that could happen elsewhere in the frame, so that doesn't seem at all robust.
* The return code of decompress - it's 0 when all of the source has been decompressed. But, i may not yet have passed the end of frame data.
* The decompression context - this is opaque.

Is there anyway to answer the question "Have I reached the end of frame yet?". I have in mind here streams which may contain more than a single frame. Or may contain data after the end of the frame.

**Comment by Cyan4973** [comment]
If I remember correctly, this use case is answered by the [frame decompression API](https://github.com/lz4/lz4/blob/dev/lib/lz4frame.h#L348) : 

> LZ4F_decompress() : 
> ...
> When a frame is fully decoded, @return will be 0 (no more data expected).

So that's your point 2 : 
> The return code of decompress - it's 0 when all of the source has been decompressed. But, i may not yet have passed the end of frame data.

Incorrect, return code is `0` when the frame is completed.

If all the source has been fed into the decompression context, but the frame is not completed, the return code will be `> 0`, because it expects more bytes.

It also works the other way round : 
suppose you provide _more_ bytes than necessary to decompress a frame, the decoder will nonetheless stop at the exact end of the current frame (value stored into `srcSizePtr`), and return a code `0`.

**Comment by jonathanunderwood** [comment]
Ah yes. That's embarassing - I knew that already, and was using the 0 return in the code, and confused myself over it this morning. Sorry for the noise!
