### ISSUE TITLE
python lz4 bindings now fully support frame format

### ISSUE THREAD

**Issue by jonathanunderwood** [lz4/lz4#465]
The lz4 bindings provided at the project below now fully support the frame format. Please can you update the home page accordingly

https://github.com/python-lz4/python-lz4

https://pypi.python.org/pypi/lz4

http://python-lz4.readthedocs.io/en/stable/

**Comment by Cyan4973** [comment]
Sure !

Would you mind providing what is, in your view, a "differentiator", compared to already listed Python LZ4 Frame bindings ?

**Comment by jgubmll** [comment]
Compared to the lz4tools bindings:
* We also provide bindings for the block API
* We also provide buffered file handling with the same API as the Python standard library compression functionality - so it's a drop in replacement for LZMA, bzip2, gzip handlers in the stdlib
* We provide context manager classes LZ$FrameCompressor and LZ4FrameDecompressor, and also LZ4FrameFile that simplifies usage and prevents the user having to manage contexts
* We also provide full documentation
* We also provide an extensive test suite

The lz4tools package hasn't been maintained for a couple of years. It's also got a bunch of memory leaks, and was focussed on delivering the command line tool, rather than a general purpose library that we've provided.

**Comment by Cyan4973** [comment]
Fair enough.
I'm looking at some short key feature, that can be written in the table, so that users understand why to select one version over the other.

I understand that lz4tools is a bit old, 
the [Iotic Labs python binding](https://github.com/Iotic-Labs/py-lz4framed) is likely a better version to compare to.

**Comment by jgubmll** [comment]
The iotic labs bindings are a lot closer, but still don't offer the API compatibility with the Python standard library.

**Comment by Cyan4973** [comment]
done !

**Comment by jgubmll** [comment]
Thanks - but the way you;ve done it implies the iotic bindings are thread safe, whereas our ones arten't. Ours are thread safe in exactly the same way as the iotic ones! :)
