### ISSUE TITLE
how to malloc enough memory destination buffer in function "LZ4_decompress_safe"?

### ISSUE THREAD

**Issue by yaohanlan** [lz4/lz4#467]
hi, when I decompress a buffer which compressed by "LZ4_compress_default", how to malloc enough memory for destination buffer in function "LZ4_decompress_safe"?

**Comment by Cyan4973** [comment]
`LZ4_decompress_safe()` doesn't provide any functionality for that.
The user application has to know, and then provide, an upper bound of the decompressed size.

Many applications select to save decompressed size into one of their fields. 
Some other ones do not need this information because they know data they generate and decode is necessarily `<= limit`. Details can vary a lot, depending on specific usage.

**Comment by jonathanunderwood** [comment]
@yaohanlan you might find the strategy we use in the Python lz4 bindings - see around [this point in the code](https://github.com/python-lz4/python-lz4/blob/master/lz4/frame/_frame.c#L1100).

Briefly the strategy is:
* Guess the size needed for the uncompressed destination buffer to be twice the size of the compressed data
* Call the LZ4 decompress function
* If the return code indicates the destination buffer is full, increase the size of the destination buffer by 3 times the return code .

Those factors of 2 and 3 seem to work reasonably well, but could be further tuned.
