### ISSUE TITLE
Question: compress_*_continue and loadDict

### ISSUE THREAD

**Issue by MiloszKrajewski** [lz4/lz4#477]
Hi (again),

I have few more questions. When using "streaming" methods (the ones with continue) from time to time I need to use loadDict. Frequency depends on size of input buffer, of course.

My idea was to use input buffer, use `Prefix64k` mode as much as possible and when buffer is going to overflow copy last 64k from input buffer to its beginning, `loadDict` and continue in `Prefix64k` mode.

The questions:
1. Do I actually need to `loadDict` after moving last 64k or rewriting `dictionary` to point to new location would be enough (kind of what `LZ4_setStreamDecode` is doing)? Are `hashTable` entries going to be ok?
2. Doing so (not calling `loadDict`) seems to be working fine, but maybe I'm missing someting?
3. With `loadDict` it is also working fine, but results are not binary identical.

Thanks for you help.

**Comment by Cyan4973** [comment]
I suspect you are following a round-buffer methodology : write forward as much as you can within a single buffer, resume from beginning when there is no longer enough space left.

For such scenario, some mechanisms are in place within `LZ4_compress_continue()` to ensure compatibility. It would even work with buffers < 64 KB (though it would definitely impact compression ratio).

Therefore, strictly speaking, it is not needed to use `loadDict`, because LZ4 is able to use the last 64 KB of data directly where they are : this is the `extDict` mode.

Your methodology transforms the `extDict` mode into `prefix64k` mode.
`prefix64k` mode is easier to manage for LZ4, so it's likely capable of finding more matches than using `extDict` mode. That would explain the compressed result difference.

**Comment by MiloszKrajewski** [comment]
I do get that, but my case is slightly different. I do actively move last 64k from end of buffer to the beginning of buffer, therefore I'm expecting `prefix64k` mode only.

My question is about what I should do after doing doing that:
a) use `loadDict`
b) not use `loadDict` just set `stream->dictionary` to new position of "last" 64k

**Comment by Cyan4973** [comment]
use `LZ4_loadDict()`

**Comment by MiloszKrajewski** [comment]
Sorry for asking so much questions, but my random questions and your answer help me fill all the gaps in my understanding.

`LZ4_stream_t` contains those fields which I should worry about in such case:
* `hashTable`
* `currentOffset`
* `dictionary`
* `dictSize`

When moving dictionary to to start of the buffer, and wrapping buffer around (so data starts just after dictionary), I don't need to worry too much about:
* `dictSize` as it stayed the same
* `dictionary` as that's what `loadDict` would do anyway (point to new location)

Now there is a question of `currentOffset` and `hashTable`. 
From my understanding (and this where I can be wrong) they are:
* expressed in same units (position in virtual stream)
* `currentOffset` stays the same after moving dictionary
* not refreshing offsets in `hashTable` is fine as dictionary still precedes data (`prefix64k`) therefore if `currentOffset` stayed the same `hashTable` offsets have to stay the same
* `loadDict` resets `LZ4_stream_t` so it looks like virtual file has just started (`currentOffset <= 64k`) so all `hashTable` entries need to be rebuilt

Is my "analysis" more or less right? Or am I getting it completely wrong?

Thanks,

**Comment by Cyan4973** [comment]
Yes, your description is correct.

Issue is, the proposed methodology is using definitions inside `LZ4_stream_t_internal`,
which is pretty dangerous, as it is an _internal_ implementation detail, that can (and probably will) change anytime in the future.

If I had a choice, I would prefer to not expose this definition, precisely to avoid that kind of issue, and rely solely on [incomplete types](https://docs.oracle.com/cd/E19205-01/819-5265/bjals/index.html).
However, it can be useful to know state size & alignment for static allocation purpose, something incomplete types cannot offer.

For this purpose, a shell type with same size and alignment as `LZ4_stream_t` used to be exposed.
Problem was, [strict aliasing rule](https://stackoverflow.com/questions/98650/what-is-the-strict-aliasing-rule) would get in the way, making this setup too risky depending on compilation options and versions.
So, instead, `LZ4_stream_t_internal` was exposed, with the explicit mention "do not use it".

Obviously, using it nonetheless will create a dependency on an internal implementation detail. Which sounds bad for the future...

Prefer using an officially supported interface.
It looks to me that [`LZ4_saveDict()`](https://github.com/lz4/lz4/blob/dev/lib/lz4.h#L280) is doing [exactly what you describe](https://github.com/lz4/lz4/blob/dev/lib/lz4.c#L1129).
And since it's an official interface, it will remain supported in the future, even when some internal implementation detail changes.

**Comment by MiloszKrajewski** [comment]
Shame on me.
I went through all those shenanigans because I didn't read **Note : you don't need to call LZ4_loadDict() afterwards, dictionary is immediately usable, you can therefore call LZ4_compress_fast_continue().**

**Comment by Cyan4973** [comment]
`LZ4_saveDict()` primary intention is to preserve input data from an untrusted input buffer.
As a side-effect, it's faster than `LZ4_loadDict()`, because it doesn't need to rebuild hash table.
Maybe documentation could be clearer on this speed advantage.

**Comment by MiloszKrajewski** [comment]
I think the confusion came from something else. MY reasoning was something like this:
*"As I know what `loadDict` does (more or less) `saveDict` must do the OPPOSITE, therefore as I need something SIMILAR to `loadDict` it may not be `saveDict`."*

**Comment by Cyan4973** [comment]
Right, naming is an important part of an API.
It can be difficult to get right.

`saveDict()` feels okay with regards to its initial objective:
preserving input data from an untrusted input buffer where it might get overwritten or discarded.

But as a kind of "faster `loadDict()`", it doesn't cut it.

Plus it's not strictly a "faster `loadDict()`" : 
`loadDict()` can load any data to start a new block,
while `saveDict()` can only "continue" from previously compressed data.
