### ISSUE TITLE
Question for ring buffer size

### ISSUE THREAD

**Issue by EdvardD** [lz4/lz4#495]
In the example `HCStreaming_ringBuffer.c` ring buffer for decompressed data has size: `DEC_BUFFER_BYTES    = RING_BUFFER_BYTES + MESSAGE_MAX_BYTES   // Intentionally larger to test unsynchronized ring buffers`. Can you please explain why we need extra `MESSAGE_MAX_BYTES`? And when we need not extra `MESSAGE_MAX_BYTES`?

**Comment by Cyan4973** [comment]
You don't need extra `MESSAGE_MAX_BYTES` whenever the size of your messages is guaranteed to _always_ be `RING_BUFFER_BYTES`, or an exact subdivision of `RING_BUFFER_BYTES`.

But such restriction is then on the encoding side.

Whenever this guarantee can't be made, and you still want your decoder to be compatible, it's necessary to plan for a "worst case scenario".
Such worst case scenario is : 
- buffer is filled up to `RING_BUFFER_BYTES-1`
- decoder receives a block of size `MESSAGE_MAX_BYTES`

Since a block must be decoded in a single continuous memory segment, it must lie between `RING_BUFFER_BYTES-1` and `RING_BUFFER_BYTES-1+MESSAGE_MAX_BYTES`.
Granted, `RING_BUFFER_BYTES + MESSAGE_MAX_BYTES` is one more byte than necessary.
