### ISSUE TITLE
favorDecSpeed compromises frame API

### ISSUE THREAD

**Issue by psteinb** [lz4/lz4#546]
I just realized that the addition of 3792d00168edd060c58ceaecffb97d43dab27094 does compromise the lz4frame API in a sense that the format stability is maintained, but (for my feeling) the API is changed. 

To make things clear, this code:
```
static const LZ4F_preferences_t lz4_preferences = {
    { LZ4F_max256KB, LZ4F_blockLinked, LZ4F_noContentChecksum, LZ4F_frame,
      0 /* content size unknown */, 0 /* no dictID */ , LZ4F_noBlockChecksum },
    0,   /* compression level */
    0,   /* autoflush */
    { 0, 0, 0, 0 },  /* reserved, must be set to 0 */
};
```
simply doesn't compile with `1.8.2`. For me that is a API breaking change and not only a patch - which should have made `1.8.2` a `1.9.0`. 

As my library depends on lz4 frames, I wanted to fix that by checking the LZ4Frame version through a preprocessor guard. However `LZ4F_VERSION` is `100` in either `1.8.[0-1]` or `1.8.2+`. That makes it even harder now to disentangle which API I am getting at compile time. I am guessing at this point that `LZ4F_VERSION`  refers to the compression format rather than the API. 

I see several ways forward, but was wondering at this point, if I am overseeing anything to adapt my code to this problem.

**Comment by Cyan4973** [comment]
It's a good point.

The recommended scenario is to [init the preferences structure with a `memset()`](https://github.com/lz4/lz4/blob/dev/lib/lz4frame.h#L176).
This way, the exact formulation of the reserved members does not matter.

Offering an evolutive API is a difficult exercise.
In this case, some extra-space was defined at the end of the structure to make it possible to introduce new members without breaking ABI.
But introducing a new member requires renaming at least one of the reserved members.
I'm not sure how it could be done better, short of an opaque object. But an opaque object cannot be allocated on stack, or simply be inserted as a member of another structure, requiring a constructor and destructor, so it's a more complex object to handle, adding its share of risks.

Maybe having the reserved space defined as multiple integers, instead of a table of integers, would have helped your case ?
Also, maybe providing an explicit initialization function would help ?

**Comment by Cyan4973** [comment]
As a follow up,
latest proposal for `lz4frame.h` API is to introduce 2 new constants, 
`LZ4F_INIT_PREFERENCES` and `LZ4F_INIT_FRAMEINFO`,
which, as the name implies, can be used to initialize relevant structures
as an alternative to `memset()`.

Both method are guaranteed to remain valid in the future, should any change happen.
`memset()` is more universal, as it also works for prior versions.

For information, `LZ4F_frameInfo_t` is unlikely to change in the future, as all reserved space has been used up, and there is none left.

`LZ4F_preferences_t` still has some reserved fields, so they may be converted to express new features in some distant future. But there is no such plan in the foreseeable future.
