### ISSUE TITLE
Question : the performance of LZ4 with dictionary 

### ISSUE THREAD

**Issue by LeeYoung624** [lz4/lz4#559]
Hi @Cyan4973 ,
Last time I asked about the usage of LZ4 with dictionary, and I got a fast response. Thanks a lot!
After that I wrote some code to test the performance of LZ4 with dictionary. Here is my test case:
I got a binary file of 25MB, split into 4KB, and I got a dictionary with these splited files via Zstd. Using the dictionary, I compressed the splited 4KB files with LZ4 -1 and LZ4 -9. 
The compression ratio seems to have a great boost: 1.747 -> 2.001(LZ4 -1) and 1.828 -> 2.369(LZ4 -9). But the decompression speed seems to have decreased a lot: 940 MB/s -> 690 MB/s(LZ4 -1) and 960 MB/s -> 650 MB/s (LZ4 -9).
And I also tested with LZ4_compress_fast_continue/LZ4_decompress_safe_continue vs LZ4F_compressFrame_usingCDict/LZ4F_decompress_usingDict with the same test case I mentioned above. It seems that LZ4_compress_fast_continue/LZ4_decompress_safe_continue is much faster than LZ4F_compressFrame_usingCDict/LZ4F_decompress_usingDict.
So here are my questions:
1, The decompression speed seem to have decreased about 20% ~ 30% if I use dictionary. Is this normal? Do I have some methods to improve the decompression speed with dictionary?
2, Is LZ4F_compressFrame_usingCDict/LZ4F_decompress_usingDict perform slower than LZ4_compress_fast_continue/LZ4_decompress_safe_continue? In which case should I use LZ4F_compressFrame_usingCDict/LZ4F_decompress_usingDict or LZ4_compress_fast_continue/LZ4_decompress_safe_continue?

Thank you for your patience.
Regards,
Lee

**Comment by Cyan4973** [comment]
#### Regarding decompression speed

Results can vary, by a wide maring.
There 2 opposing effects : 
- Having to fetch data from 2 different buffers result in branches, which decrease speed. For a very fast decoder such as lz4, this can have a substantial impact.
- Compressing better generally translates into less work to do for the decoder, hence in better speed.

Which one wins ? Well, it depends on the gains from dictionary compression.
In your use case, gains are substantial but not "transformative", so the impact of branch misses is larger.

In other cases, typically involving smaller data with higher repetition rate, compression ratio can be improved by a lot, and with it, decompression speed.

There is also the use case where dictionary is useless. In which case, the buffer selection branch becomes very predictable, resulting in decompression speed similar to no dictionary mode.

#### Regarding frame versus block mode

Frame mode has more work to do.
It takes care of proper formatting, and also buffer data, for streaming scenarios.
There are optimization shortcuts into the algorithm to minimize the impact, but it's not zero.

Frame mode is required if you want to generate data compatible with "interoperable" tools and libraries, such as `lz4` command line.

Block mode is lighter, hence faster, and doesn't generate any header, so is marginally smaller. But it also means it stores no metadata, so you'll have to store intended metadata (such as compressed and/or decompressed size) by yourself somewhere.

**Comment by Cyan4973** [comment]
#### potential work around for decompression speed

Since the analysis of the speed issue concentrates its explanation of the probable impact of branch misses, one way to fix this would be to eliminate the branch.

This seems possible, using `LZ4_decompress_safe_continue()` or even `LZ4_decompress_safe_usingDict()`.

The design to respect is as follows : keep the dictionary at the beginning of the output buffer, decompress data in the space immediately adjacent to it.

The expectation is that `LZ4` block mode should automatically detect that they are adjacent spaces, and behave as if everything was decoded into a single buffer, eliminating the branch, improving decompression speed.
(note that I haven't tested it, this is just speculation based on my memory of how `lz4` decoder works, there might be some subtle issues getting in the way that may need fixing).

A drawback of this design is that the dictionary can no longer be "shared" in read-only mode by multiple threads : each working thread needs its own space to decompress data, hence needs its own copy of the dictionary alongside it.

If this limitation is acceptable, the expected benefit is a substantially improved decoding speed.

**Comment by felixhandte** [comment]
Hey @LeeYoung624, @Cyan4973 and I spoke a bit about your question. Irrespective of any possible improvements/additions to the library to address this, which I'm happy to continue discussing, @Cyan4973 is correct: if you place the output buffer so that it contiguously follows the dictionary buffer, raw LZ4 will recognize that and avoid the branch otherwise needed to dispatch reads between two discontiguous buffers. E.g.:

```c
// assuming dictBuf is a writable buffer that starts with the contents of the dict
// and contains sufficient trailing room to do the decompression into.
const char *dict = dictBuf;
char *dst = dictBuf + dictSize;
int dstCapacity = dictBufSize - dictSize;
LZ4_decompress_safe_usingDict(src, dst, srcSize, dstCapacity, dict, dictSize);
```

I would have to check, but I believe the same trick should be possible with `LZ4F_decompress_usingDict`.

If you try that, please let me know if it works, and if that's sufficient for your purposes.

**Comment by LeeYoung624** [comment]
Hi @Cyan4973 and @felixhandte ,
Thank you guys for your patience.
I tried with your trick and it's awesome!

I tested with LZ4_compress_default/LZ4_decompress_safe vs LZ4_compress_fast_continue/LZ4_decompress_safe_usingDict, and here is my test result:
no dictionary (LZ4_compress_default/LZ4_decompress_safe ):
compression ratio : 1.757
decompression speed : 1658.029 MB/s

with dictionary but no trick:
compression ratio : 2.015
decompression speed : 1125.445 MB/s

with dictionary and trick:
compression ratio : 2.015
decompression speed : 1991.645 MB/s
The decompression speed has increased so much that it's faster than the speed without dictionary. That's awesome!
As you said, this seems to be a trade off problem. In my 4KB test case, dictionary seems a good option.
I will try some other way to optimize the speed. Currently I have a idea that maybe I can adjust the size of dictionary, therefore I can make a smaller dictionary to fit the L1/L2 cache of CPU. Do you have other ideas @felixhandte ?

**Comment by felixhandte** [comment]
Are you specifically trying to optimize decompression speed? In that case, yeah, trying a small dictionary might help some. If you trust your input to be valid (i.e., don't need to protect against crafted malicious compressed streams), you could also switch to the `_fast` decompression variants.

For compressing, if you're using a dictionary in LZ4 raw mode on small blocks, which it sounds like, you could try experimenting with the advanced/experimental API `LZ4_attach_dictionary` ([def](https://github.com/lz4/lz4/blob/master/lib/lz4.h#L428)) (LZ4F uses this automatically). I'd be interested to see whether that improves performance for you.

**Comment by LeeYoung624** [comment]
> Are you specifically trying to optimize decompression speed?
Yes. In my case, the data is read only so that they only need to be compressed once but decompressed many times.
I tried with small dictionary(size of 32K, maybe I should go further with smaller dictionaries), and it doesn't work better than the 64K dictionary.

> you could also switch to the _fast decompression variants.
I tried with LZ4_decompress_fast_usingDict, and the decompression speed seems didn't change much. The decompression speed is about 1900 MB/s ~ 1950 MB/s.

>  if you're using a dictionary in LZ4 raw mode on small blocks, which it sounds like
Yes, in my case I'm using LZ4 with blocks of 4KB.

> you could try experimenting with the advanced/experimental API LZ4_attach_dictionary
I tried the _LZ4_attach_dictionary_ and it didn't work well.
_LZ4_loadDict_ and _LZ4_attach_dictionary_ compression speed : 232.035 MB/s

_LLZ4_loadDict_ compression speed : 235.467 MB/s

More interestingly, I tested the demo in ARM platform(a Android cell phone). The compression ratio is same with the ratio in x86 platform. But for the decompression speed, it's a little wired:
I tested with several binary files in x86 and ARM.
x86 :
file size(MB)    decompression speed of LZ4 without dictionary(MB/s)   decompression speed of LZ4 with dictionary and the trick(MB/s)
1.37				1550				1800
8.02				1924				2150
5.05				1430				1750
3.56				1730				1950
3.04				1450				1800
25.5				1750				1950
19.9				1450				1700
3.11				1550				1750
2				1500				1850
11.2				1720				1950
5.14				1520				1750
2.13				1750				2000
1.69				1650				1900
1.94				1840				2150
22.3				1750				1940
8.91				1550				1800
9.61				1450				1800

ARM :
file size(MB)    decompression speed of LZ4 without dictionary(MB/s)   decompression speed of LZ4 with dictionary and the trick(MB/s)
1.37				467				504
8.02				571				539
5.05				446				485
3.56				552				525
3.04				460				517
25.5				551				530
19.9				455				495
3.11				486				512
2				463				510
11.2				524				509
5.14				471				497
2.13				539				560
1.69				534				583
1.94				595				653
22.3				533				520
8.91				468				485
9.61				456				490
As you can see, the trick of keeping the dictionary at the beginning of output works perfectly, In all test files, the decompression speed is better than LZ4 without dictionary.
But in ARM, the decompression speed of some files may be worse than the speed of LZ4 without dictionary. Anyway, it's always better than the LZ4 with dictionary and without dictionary.
Maybe LZ4 is best optimized for x86?  Or it's only some sort of data fluctuation?
Thank you guys for your help and patience.

**Comment by Cyan4973** [comment]
ARM chips can have a lot of differences depending on manufacturers, even for an equivalent architecture level. So it's difficult to draw "generic" conclusions, one must be a bit more specific regarding what kind of chip is being benchmarked.

I would guess that a number of ARM chips use a relatively limited amount of cache.
Since you are using blocks of 4K, I would expect each block to fit entirely within ARM L1 cache.

But when using dictionary, decoder may now reference data from up to 64 KB before current pointer position. 64 KB is most likely too large for L1 cache. Question : is it compensate by a reasonably good L2 cache ?

For x86 cpus, the answer is yes. For a long time now, x86 cpus are expected to feature at least 256 KB of reasonably fast L2 caches, or more depending on architecture details, which is enough for LZ4 with dictionary.

For ARM chips though, all bets are off. Some will have no L2 caches. Some will have inefficient L2 caches. Some will have fast L2 caches, but of small size. etc. Difficult to tell, as there is no generic answer.

**Comment by LeeYoung624** [comment]
Thank you @Cyan4973 
I think I got your meaning : the dictionary, which is the content in the sliding window at the beginning of compression/decompression, and the content to be compressed/decompressed, which is 4K here, should be able to fit in L1 if I want get a better result.
I'm not sure if I was right or not.

I checked the datasheet of the CPU, and find out that:

> 32KB L1 I-cache and 32KB L1 D-cache
256KB unified L2 cache for CPU cluster

There is no L3 cache in this CPU. And the L2 cache is shared with other CPUs.
Therefore, I tested with a smaller dictionary of 20KB. As I have put the dictionary at the beginning of decompressed data buffer, the decompression buffer size is 20KB + 4KB = 24KB.
Here is the result : The compression ratio has decreased a little, and the decompression speed increased about 5~10%. This result seems to be reasonable because they can be loaded in L1 cache now.

I'm testing these files cause I want to compress the read-only file cache in linux with LZ4 + dictionary. I believe this is a good idea cause the read-only cache only need to be compressed 1 time and decompressed many times. With compression of these file caches, the OS can have more RAM.

**Comment by Cyan4973** [comment]
5-10% improvement is a bit less than I expected, 
but considering your use case, I still believe reducing the dictionary to keep all operations within L1 cache is a good thing to do (on ARM).

The reason is, on this ARM target, the L2 cache is shared.

If there is one thing that a synthetic benchmark can not show, it is how resources are shared with other running processes. Considering your use case (a read-only file cache), it seems likely that when it's invoked, some other process is actively using the data, doing its own processing, hence requiring its own resources.
Therefore, all these process will fight for space in the unified L2 cache, forcing others to evict their data.

x86 have less problem, since each L2 cache is dedicated for one core (though hyper-threading can get in the way, and make this resource shareable too).

Saving RAM through compression is likely a good option for the system as a whole, since other processes will have more resource for their own needs.

**Comment by LeeYoung624** [comment]
> Considering your use case (a read-only file cache), it seems likely that when it's invoked, some other process is actively using the data, doing its own processing, hence requiring its own resources.

I agree with you @Cyan4973 . I also did some test on this : I started some other processes that consume much of the CPU. The result is good : the decompression speed of 20K dictionary is much better than the one with 64KB dictionary.

Thank you for your help these days.
