### ISSUE TITLE
Rare decompression issue in 1.8.2

### ISSUE THREAD

**Issue by Pashugan** [lz4/lz4#560]
Hi,

I've run into an issue when I'm getting broken archives with the recent version of lz4. The previous version works well with the same files.

In short, it seems like under certain circumstances it turns consequent zero characters "0" into zero bytes \0 after decompression. That is, the diff shows

< 0.15000000596046448
\> 0.150596046448

lz4 -t tells off "Error 66 : Decompression error : ERROR_contentChecksum_invalid" on these files.

The example file is rather sensitive to make it public, so I'm ready to provide it to the developers upon request. You should be able to reproduce the bug using lz4 -9.

**Comment by Cyan4973** [comment]
Hi @Pashugan 
Thanks for reporting.
This is interesting. We have not been able to produce that case so far, but maybe it requires extraordinary conditions that even our fuzzer cannot find.
I'm willing to investigate, especially if you have a reproducible case.
My email is in commit logs. If you can't access it, we could also use my [blog's email form](http://www.emailmeform.com/builder/form/a70egol6fyVf15zd46jY88).

**Comment by BFLscientist** [comment]
Hi,

I have also got the same issue when I decompress .lz4 files with the latest version of lz4. I get the error 
'Error 66 : Decompression error : ERROR_contentChecksum_invalid' when I use both lz4 -d and lz4 -t commands.

**Comment by Cyan4973** [comment]
There is indeed an issue with level 9 of latest version of LZ4.
The quick work around is to use level 8 instead, since it doesn't use the suspected part of the code.

**Comment by Cyan4973** [comment]
Issue fixed in #562, now merged into `dev` branch.
The fix will be part of next release.

**Comment by Cyan4973** [comment]
Indeed @ChALkeR , the issue could impact any suite of identical character, not limited `0`. What made it rare was additional conditions related to distance.
Thanks for the test case (I guess it's fixed in v1.8.3 ?)

**Comment by ChALkeR** [comment]
@Cyan4973, yes, v1.8.3 fixed everything for me, thanks!
Sorry for not making that clear enough.

**Comment by ThomasWaldmann** [comment]
If I am just calling `LZ4_compress_default(...)`, am I affected by this bug?

The API (iirc) has no compression level parameter, so that "level 9" in this issue is a bit unclear...

**Comment by felixhandte** [comment]
@ThomasWaldmann, no. This bug only existed in the "high compression" compressor (LZ4HC). `LZ4_compress_default()` uses the other (fast) compressor implementation.

**Comment by cactysman** [comment]
Is there any way to recover these archives?
I compressed a disk image with 1.8.3 and am running into this issue. 1.8.3 and 1.9.2 both can't decompress that file.

**Comment by Cyan4973** [comment]
This particular issue was only for `v1.8.2` when compressed at level 9.
`v1.8.3` is not supposed to be affected.

**Comment by cactysman** [comment]
> This particular issue was only for `v1.8.2` when compressed at level 9.
> `v1.8.3` is not supposed to be affected.

I only recently started using LZ4 for file archival purposes, version 1.8.3 is the only version I ever used for both compressing and decompressing my files, because that's what I get with Debian 10.

When I encountered this issue, I tried version 1.9.2 that I can install in Alpine Linux (inside a docker container), But even then I get this decompression error.

I don't have the source file anymore though, and it would be rather large at around 150 GB, so I don't really know how I could help finding the reason for why this is happening when it apparently was fixed before in that exact version.

This might be relevant info; I am operating on an external NTFS formatted hard drive through WSL. Another file I compressed at a size of 3.7 TB (also using `-9`) worked fine though and I just verified its integrity with `-t`.

> In short, it seems like under certain circumstances it turns consequent zero characters "0" into zero bytes \0 after decompression.

Would there be any way to know which bytes are affected? But I guess, since the decompression process throws that error instead of the output file being invalid, there wouldn't be much that I could do to fix this without modifying LZ4 I guess? Otherwise I could have tried to manually (with a script) fix the bytes in the file or something.

**Comment by Cyan4973** [comment]
If you were using v1.8.3, then you are not affected by _this_ bug, which has been fixed before the v1.8.3 release.
The only other corruption that was fixed afterwards impacts `LZ4_compress_destSize()`, which is unlikely to be the function invoked in your issue (it's not called from the `lz4` CLI).

Another potential source of corruption could be the hardware itself. It's very rare, so we tend to forget about it, but at the scale at which `lz4` operates, it's not unheard of.

Whatever the source of corruption is, it's unlikely that the data can be restored now unfortunately.
