### ISSUE TITLE
Q: Compile time warnings

### ISSUE THREAD

**Issue by kaqkk** [lz4/lz4#590]
Hi,

I'm building the version v1.8.3's "visual\VS2017\liblz4" project with vs2017. (We are trying to move to the latest version from an earlier working one). I'm getting some compile time warnings when Building X64 config. Can you confirm they are harmless (especially the last two), so I can safely suppress/ignore them? I have attached the build output. Thank you in advance!

[buildlog.txt](https://github.com/lz4/lz4/files/2455762/buildlog.txt)

**Comment by Cyan4973** [comment]
Hi @kaqkk 

As it's the first time I see these warnings from Visual, I was wondering : 
are you maybe using warning level 5 ?
This level tends to be quite noisy, so we limit our tests to warning level 4.

**Comment by Cyan4973** [comment]
The first set of warnings :

> Using operator X on a 4 byte value and then casting the result to a 8 byte value

tends to be harmless.

It happens every time we are using a 4-bytes `unsigned` type for an operation, which result is then added/subtracted to a large 8-bytes type.
The compiler is cautious, because in case the intermediate result would overflow, the final result would be different from expectation.

But we know (and we can guarantee) that overflowing the intermediate result is impossible.

So it's harmless. Fixes are possible, but won't change the outcome.

One possible way to avoid that warning could be to use a signed `int` type for intermediate result instead.
The advantage is that an overflow of `int` is forbidden, so the compiler is expected to "believe no overflow will happen".
But I would need first to generate these warnings to be able to observe the impact of the potential remediation.

**Comment by Cyan4973** [comment]
Yes, I'm just unclear if forcing this cast at this place (as opposed to: let the compiler decide) can have any impact on performance.
Probably not, but requires careful testing.

**Comment by Cyan4973** [comment]
With the merge of last patch, next release should get rid of all remaining Visual 2017+ warnings within `liblz4`.
