### ISSUE TITLE
Does this algorithm support 16 bit MCU?

### ISSUE THREAD

**Issue by cyh2018git** [lz4/lz4#595]
Does this algorithm support 16 bit MCU? If not, will there be any subsequent support? Thanks.

**Comment by Cyan4973** [comment]
If you mean "does _the reference source code_ support 16 bit MCU",
I haven't tested it, and I suspect it would not work "as is", since the code assume that types such as `int` are 32 bits, and I'm not sure what would happen if they are 16-bit instead.

Note that LZ4, as an _algorithm_, has been ported to many platform, including older 8-bit ones. But that requires a dedicated code, optimized for target platform.

**Comment by cyh2018git** [comment]
Yes, I noticed. I have modified the int type manually, and have passed the 16 bit MCU test.
