### ISSUE TITLE
Export LZ4F_getBlockSize

### ISSUE THREAD

**Issue by nh2** [lz4/lz4#608]
Right now it seems I cannot obtain the info how many bytes are taken by a given `LZ4F_blockSizeID_t`.

In particular, it's impossible to ask the API how many bytes `LZ4F_default` takes.

It would thus be great to have `LZ4F_getBlockSize` in the public API -- or even better, a compile-time macro for the same information.

**Comment by Cyan4973** [comment]
Right,
the maximum amount of bytes per block is supposed to be obvious from the `enum` name (`LZ4F_max64KB`, `LZ4F_max256KB`, etc.),
but it's true there is no function that returns this information in a scalar variable.
So it could be a good addition.

Perhaps more importantly, a core idea of the `LZ4F` API is that the block size should be of secondary importance : the main impact is that it directly decides the size of buffers, which matters mostly for memory allocation. 
But beyond that, it should be almost irrelevant, because users can provide any input size, including smaller than maximum block size. And when input is larger than one maximum block size, it's automatically cut into as many blocks as necessary.

Therefore, I was wondering, for which reason do you need the maximum block size ?

**Comment by nh2** [comment]
> Therefore, I was wondering, for which reason do you need the maximum block size ?

The performance of the compression update function depends on it: If you pass in buffers that are `>=` the block size, you get on the `/* compress full blocks */` fast path in https://github.com/lz4/lz4/blob/6689dae33ba1eb588abe3d3cb763bc5dc08878b3/lib/lz4frame.c#L851-L858

This fast path avoids `memcpy`s.

I'm writing a binding to `lz4frame.h` in Haskell (as you probably know we already have bindings for the block format, but not for the frame format), and a streaming pipeline around it.

In the streaming pipeline I have a pipeline element that looks like `bytes -> compressingPipelineElement -> bytes`. The pipeline element has not control over the size of incombing byte buffers. At the same time, it is beneficial for memory allocation if I set a maximum bound on the size of the incoming buffers, so that I can use `LZ4F_compressBound()` once and allocate one buffer to be re-used across update calls.

Now, how large I choose that bound on the input has a big impact on performance (due to the above linked code): Already if choose it 1 byte smaller than the block size, the fast path will not be taken.

This in practice makes a 20% performance difference on my machine. If I cap the incoming buffers to exactly the output block size, a Haskell clone of the `lz4` CLI utility using my streaming abstraction is as fast as the C `lz4` utility. If I pick already 1 byte less, it becomes impossible to match the C utility's speed.

**Comment by Cyan4973** [comment]
@tzakian added the `LZ4F_getBlockSize()` prototype to `lz4frame.h` experimental API.
It is expected to help this issue.

The prototype will move from "experimental" to "stable" after a test period, to collect feedback on its usage.
