### ISSUE TITLE
[discussion] [Windows] simplification of the creation the import library

### ISSUE THREAD

**Issue by vtorri** [lz4/lz4#614]
Hello

As __declspec(dllexport) is used, the creation of the import library can be simplified by passing

-Wl,--out-implib,dll/liblz4.lib

when creating the DLL.

This means that the **dlltool** call can be removed from lib/Makefile, as well as the .def file.

I can create a PR if you want

**Comment by Cyan4973** [comment]
I think that would be a good idea @vtorri .

The `__declspec(dllimport)` is triggered through `LZ4_DLL_IMPORT`,
which is build-system driven anyway (cannot be automated from source code).

Since `LZ4_DLL_IMPORT` is project-specific,
should a more standard way to control the creation of import library exist,
it would feel a lot better for integration with Microsoft's ecosystem.

**Comment by vtorri** [comment]
PR request failed. i don't understand why (i did the fork and sync it as usual).
I can send you the diff of Makefile if you want

**Comment by vtorri** [comment]
fixed with PR #615
