### ISSUE TITLE
what version would this embedded copy be?

### ISSUE THREAD

**Issue by RJVB** [lz4/lz4#625]
Does anyone have an idea what version the embedded LZ4 copy used in ZFS corresponds to?

https://github.com/zfsonlinux/zfs/blob/master/module/zfs/lz4.c
https://github.com/zfsonlinux/zfs/commits/master/module/zfs/lz4.c

It's about 5y old according to the preamble, so one could think that there must have been significant improvements since then. Have there, esp. in terms of (de)compression speed and/or compression gain (for instance by using a state buffer)?

The main criteria for upgrading the embedded copy would be improved compression and/or reliability for negligible performance cost and of course, existing lz4-compressed data should remain readable.

Thanks in advance for any feedback!

**Comment by Cyan4973** [comment]
If it's 5 years old, I would say there were definitely improvements since.
At the very least, decompression speed should now be faster.
Probably some corner case were fixed too.

I also note that the file linked is more than "just" lz4 source code, since it also contains specific zfs stuff.
This matters, because it's not possible to just drag and drop the source file provided in this project : some adaptation to target environment is required.

**Comment by RJVB** [comment]
Hi,

yes, I also noticed there have been quite a few changes to the code so updating the copy isn't going to be straightforward for everyone (or else I'd already have started tinkering) ...

Improved decompression speed should be a good selling point, and if the use of a state buffer can improve compression ratio that'd be good too.

But can you confirm that the old and current versions will decompress each other's compressed data?

**Comment by Cyan4973** [comment]
Yes, they are 100% compatible.
LZ4 block format has not changed since its introduction in 2011.
