### ISSUE TITLE
Code analysis

### ISSUE THREAD

**Issue by nxrighthere** [lz4/lz4#628]
I just performed code analysis using PVS-Studio, and the application detected up to 35 warnings with various levels.

Here's a beautiful and convenient HTML report for you:
[lz4_analysis.zip](https://github.com/lz4/lz4/files/2709186/lz4_analysis.zip)

**Comment by Cyan4973** [comment]
Dear @nxrighthere ,

I went through the list, looking at warnings qualified as "high" warning only (about 30% of them).
Unfortunately, I could only notice false positives, sometimes blatant, sometimes less so.
No big surprise, this is a typical outcome with most new static analyzer. 

Note that we already use 3 static analyzers on the `lz4` project, but any new one will find other things to say.
Static analyzers tend to generate quite a lot of false positives, by design,
and unfortunately, each static analyzer picks its own set of false positives,
requiring to express ideas differently so that they correctly interpret the absence of issue,
sometimes in ways which are incompatible with each other.

If you believe that any of these warnings deserves a deeper look, you are very welcomed.
Be selective, pick one, and describe why you believe it's a problem worth investigating.
That would provide a high quality signal.

I understand that you mean well, but please appreciate that time is the most precious resource there is, and there is a huge asymmetry between computer-generated logs and human processing on the receiving side.

**Comment by nxrighthere** [comment]
I absolutely agree with you, Yann. 🥂
