### ISSUE TITLE
unlz4 option "-m" and "-c" are not compatible

### ISSUE THREAD

**Issue by benjdv** [lz4/lz4#641]
It's not possible to use correctly the options m and c in the same time
unlz4 -mc myfile*.lz4
The option -m take the lead and the -c is ignored

and when use 
lz4cat myfile*.lz4
Warning : myfile2.lz4 won't be used ! Do you want multiple input files (-m) ?
and we only get the cat of the first file

cf also #285

**Comment by Cyan4973** [comment]
Right, I believe `-m` used to be hardwired to generate one compressed file per input file.
So anything beyond that scope is more or less brittle.
Let's see what can be done.

**Comment by benjdv** [comment]
Until the options works properly, users can of course use xargs 
`ls *.lz4 | xargs -I {} unlz4 -c {} | ...`

**Comment by Cyan4973** [comment]
OK, there is a subtle issue to solve for this functionality to work : 
`stdout` cannot be opened and closed multiple times.
It must remain opened while scanning all input files.
This disrupt the current logic for `FILE*`.

Likely fixable.

**Comment by Cyan4973** [comment]
OK, patch #667 now ensures that it's possible to both compress multiple files into `stdout` (`-m -c`)m
and to decompress multiple files into `stdout` (`-d -m -c`, `unlz4 -m -c`, `lz4cat`).

What bothers me is that the patch test both, but only fix the first one.
Because decompressing multiple files into `stdout` was actually already supported.

Looking at `blame` history, it seems this feature was added for `v1.7.3`.
This is indeed mentioned [in the release note](https://github.com/lz4/lz4/releases/tag/v1.7.3).

Therefore, since the issue was reported in the context of _decompressing_ multiple files into `stdout`, I'm now wondering which version was used. This particular issue is supposed to be fixed since multiple years.

**Comment by benjdv** [comment]
I use the "official" version of liblz4-tool in Ubuntu 18.04.2 LTS.
It's unfortunately Version: 0.0~r131-2ubuntu3 - (tag r131)
Just before the (correct) LZ4 v1.7.3 - (tag V1.7.3)
I'm glad to know that the problem is already solved for "next" versions.
But I'm little bit disappointed to realize that the version used in the last xubuntu lts is as old.
Sorry for remounted these false problem, I should have to check if newer release exists or at least precise the version first.
Don't know If I could change the soft deployed but I now know a solution.

**Comment by Cyan4973** [comment]
There is an official process to upgrade a package within Ubuntu LTS,
starting from [contacting the maintainer listed on the package's page](https://packages.ubuntu.com/source/xenial/lz4),
but in my experience, it's a long and (too) involved process.
It took me a year to get `zstd` upgraded in 16.04 from an old incompatible experimental version ([`v0.5.1`](https://packages.ubuntu.com/source/xenial/libzstd)) to a new [supported one](https://packages.ubuntu.com/source/xenial-updates/libzstd). One has to be quite persistent, and build some access into canonical, to achieve any progress.

To just solve the situation on one's own system, it should be enough to download a recent release, and just `make install` from its root directory. Uninstall first the system's `lz4` to avoid potential version conflicts (otherwise, one then becomes dependent on `$PATH` declaration order).

FYI, I'm using Ubuntu 18.10 on one of my desktop, and the [default `lz4` version from `apt install`](https://packages.ubuntu.com/source/cosmic/lz4) is `v1.8.2`. At least, we know that in future Ubuntu releases, the `lz4` version deployed is much more recent. Also, having a more recent version available in Ubuntu 18.10 can help justifying an upgrade of the version in 18.04.
