### ISSUE TITLE
Encode end-to-end size-of-frame in the frame header

### ISSUE THREAD

**Issue by wkailey** [lz4/lz4#650]
Unless I have misunderstood something, a while loop is required to determine the overall length of a frame, including its header, footer, and all data blocks. This surprised me, because this design choice vitiates one of the main uses of a frame format: fast parallel decompression. Decompression is still fast following the while loop to determine the length, but the loop itself and the prologue to the loop introduces unnecessary overhead. This is, to me, unfortunate.

**Comment by Cyan4973** [comment]
That's correct : the complete size of a frame is not known in the header.

This comes from basic streaming constraints : in order to know the full size of a frame, one needs to finish the frame. By the time we reach that stage, which can be any arbitrary length, the header has long been written and forgotten.

One could think of "retrofitting" the header later, aka seek back and overwrite a pre-determined field.
Problem is, not all devices are seek compatible.
In particular, `stdin` and `stdout` are not.

We could get into more complex territories, and sometimes have this capability, sometimes not, depending on input size and detected stream properties. But it starts to become seriously complex, beyond the realm of standard C, requiring specific system hooks, and even then, there are use cases which simply can't be solved, so not having the full frame size in the header will always be a thing.

I don't think this causes a problem for parallel decompression.
In particular, LZ4 parallel decompression is only possible if blocks are independent, which is stated in the frame header. In which case, it's enough to distribute blocks to a pool of workers as they arrive in the stream.

But in most cases, LZ4 decompression speed is so fast that I/O speed is the limiting factor. Hence multi-threaded decompression of long streams is rarely a thing.

Multi-threaded decompression of multiple independent small blobs, on the other hand, is a recurrent real-world use case. But that's a completely different environment.
