### ISSUE TITLE
Questions about compression performance on small data

### ISSUE THREAD

**Issue by CristoferMartins** [lz4/lz4#653]
I want to compress games packets using this library. The packets size is 65k maximum but mostly of data is around 200 bytes~. I heard a dictionary would help a lot here.

I also want to ask if there is advantages in compiling this library with march native directive which will be used by the compression code(server side, linux). I need the compression to be as fast as possible(and faster than zlib deflate).

**Comment by Cyan4973** [comment]
Yes, compression of small packets will be helped by a dictionary.

The dictionary can be created by using `zstd --train` on a set of samples. The generated output is compatible with `lz4`. Just make sure dictionary size is <= 64 KB, since `lz4` will not make use of more content anyway.

Regarding usage of `-march=native`, I would say this is more or less random.
Sometimes it's better, sometimes not.
I would recommend testing the speed of both, using the internal benchmark functionality (`-b`), and pick the better one.

Don't worry about the speed being faster than `zlib`, it _will_ be faster, by an order of magnitude. Compilation flags may influence the result in <= 20% max range, but nothing large enough to alter the bigger picture.
