### ISSUE TITLE
sub-optimal compression

### ISSUE THREAD

**Issue by aleksazr** [lz4/lz4#655]
Hello,

I am compressing the alpha channel of an ARGB image.

I've extracted the alpha byte in a separate file (~500k),
get it here: http://users.beotel.net/~gwh/lz4/FFs.bin

The image is mostly opaque, so there are a lot of 0xFF bytes in sequence.
(btw, the first non-FF byte starts at around 0x57C90)

Compressed with "lz4 -9 FFs.bin" I get a file of 3,048 bytes, and that file also has a lot of 0xFF bytes.
Compressed again, the file shrinks to 1,377 bytes, which I would expect to happen on first compress.

**Comment by Cyan4973** [comment]
[LZ4 format](https://github.com/lz4/lz4/blob/dev/doc/lz4_Block_format.md) has a hard compression ratio limit, of 255:1. 
It cannot do better than representing 255 bytes into one byte.
That's typically what happens when compressing a lot of `\0` or `0xFF` bytes.

In which case, `LZ4` will generate many `0xFF` bytes (well, 255 times less, but it can still be many bytes if the source is large). And of course, such a source can itself be compressed.

The limitation, and its implied consequences, come from a design choice which favors simplicity.

There is no "direct" solution, given that the format reaches its limits. The one you suggest (compressing twice) is one of them. 

There are actually known use case for sparse data, where the first pass is done with LZ4, and the second pass is done with a stronger compressor like `zlib` or `lz4hc`. The idea is : `LZ4` reduces the amount of work to do by the "strong" compressor, by typically a factor 100 (for sparse data). So even if the strong compressor is "slower", this is a 100x less slow than compressing the original data with it. The end compression ratio is generally in the same ballpark. In extreme instances, where data is _extremely_ sparse, it can even improve compression ratio, by achieving distance reduction.
The downside is that decompression is now a 2-stages (or more) process. However, given how fast `LZ4` decompresses, the runtime cost is moderate. The most important issue is implied complexity (knowing how many passes, which compressor used for which pass, etc.).

**Comment by aleksazr** [comment]
OK, thank you for the explanation and the idea to use LZ4 (extremely fast) followed by LZ4HC.
Even double LZ4 works fine enough.

Well, maybe one day LZ4 will detect that the previously compressed block and current block are equal, and do something about it on its own.
