### ISSUE TITLE
[discussion] lz4 vs zlib : speed and memory usage

### ISSUE THREAD

**Issue by vtorri** [lz4/lz4#661]
in our project we use zlib for compression and decompression of themes. We used it because it was the best compromise between speed decompression and memory usage

in the lz4 website, there are benchmark about speed decompression, but not about memory usage. Would it be possible to have also memory benchmarks ?

thank you

**Comment by Cyan4973** [comment]
It's a difficult one, because the memory usage is typically a matter of implementation.

The LZ4 decompression algorithm itself does not need any memory beyond a few registers.
No table is allocated, not even on stack.

So, in the common scenario of block decompression, all that's needed is the input buffer with compressed data, and a corresponding output buffer for the decompressed data.

There are ways to make the situation more complex though. 
That's why memory usage actually depends on a specific scenario,
and that's why it's more difficult to "generalize" a comparison from a single benchmark.
