### ISSUE TITLE
Test failure in 1.9.0: Incorrect parameters

### ISSUE THREAD

**Issue by itoffshore** [lz4/lz4#675]
`lz4 1.9.0` [builds successfully](https://github.com/alpinelinux/aports/pull/7117) in Alpine Linux but the tests are failing the `CI` under `drone` with `Incorrect parameters`:

* https://cloud.drone.io/alpinelinux/aports/1576

**Comment by Cyan4973** [comment]
Thanks for report @itoffshore ,

I'm don't completely understand what's going on.
The CI seems to run the `make test` script,
but I don't get which operation is failing.

**Comment by itoffshore** [comment]
it starts to fail around [line `298` in `drone`](https://cloud.drone.io/alpinelinux/aports/1576)(# lz4 should fail when fast=0):

```
# cannot save output of ./datagen -g20KB as input file to lz4 because the following shell commands are run before ./datagen -g20KB
test "12713" -lt "13823" # -1 vs -9
test "12469" -lt "12713" # 1 vs -1
test "12713" -eq "12713" # checks default fast compression is -1
! ../programs/lz4 -c --fast=0 tmp-tlb-dg20K # lz4 should fail when fast=0
Incorrect parameters
Usage :
lz4 [arg] [input] [output]
input : a filename
with no FILE, or when FILE is - or stdin, read standard input
Arguments :
-1 : Fast compression (default)
-9 : High compression
-d : decompression (default for .lz4 extension)
-z : force compression
-D FILE: use FILE as dictionary
-f : overwrite output without prompting
-k : preserve source files(s) (default)
--rm : remove source file(s) after successful de/compression
-h/-H : display help/long help and exit
! ../programs/lz4 -c --fast=-1 tmp-tlb-dg20K # lz4 should fail when fast=-1
Incorrect parameters
Usage :
lz4 [arg] [input] [output]
input : a filename
with no FILE, or when FILE is - or stdin, read standard input
Arguments :
-1 : Fast compression (default)
-9 : High compression
-d : decompression (default for .lz4 extension)
-z : force compression
-D FILE: use FILE as dictionary
-f : overwrite output without prompting
-k : preserve source files(s) (default)
--rm : remove source file(s) after successful de/compression
-h/-H : display help/long help and exit
# Test for #596
../programs/lz4 tmp-tlb-test
"Md@��TEST
�� ../programs/lz4 tmp-tlb-test.lz4 tmp-tlb-test2
tmp-tlb-test.lz4: No such file or directory
diff -q tmp-tlb-test tmp-tlb-test2
Files tmp-tlb-test and tmp-tlb-test2 differ
make[1]: *** [Makefile:320: test-lz4-basic] Error 1
make[1]: *** Waiting for unfinished jobs....
65536+0 records in
65536+0 records out
65536+0 records in
65536+0 records out
65536+0 records in
65536+0 records out
65536+0 records in
65536+0 records out
65536+0 records in
65536+0 records out
make[1]: Leaving directory '/home/buildozer/aports/main/lz4/src/lz4-1.9.0/tests'
make: *** [Makefile:130: check] Error 2
>>> ERROR: lz4: check failed
>>> lz4: Uninstalling dependencies
```
I have `diffutils` installed in the build environment but perhaps the errors are due to some other **GNU** tools the tests assume to be available which don't exist in `busybox` (or which have slightly different command line options) ?

**Comment by Cyan4973** [comment]
I suspect line 298 is fine.
Test is supposed to fail, and it fails, so it seems all good.

I'm more concerned by line 333.
`lz4` is supposed to compress a file, hence to create a `.lz4` artefact.
But it seems it pushes the compressed content into `stdout` instead, since some binary blob is visible afterwards.
That would definitely break the test, and is consistent with the next failure, when `lz4` tries to decompress `tmp-tlb-test.lz4`, but it doesn't exist.

Now, why does it act this way ?
That's presumably because `lz4` cli believes its output is being piped, so it defaults to `stdout`.
This could be a side effect of `drone`, where `lz4` doesn't consider `stdout` to be a console.

There are multiple ways to fix this,
including just changing the test,
but I'm also trying to understand which behavior makes most sense for users, and for installed base.

**Comment by itoffshore** [comment]
[Travis is ok](https://travis-ci.org/alpinelinux/aports/builds/521363338?utm_source=github_status&utm_medium=notification) with the tests - I can just disable them for this [Alpine `PR`](https://github.com/alpinelinux/aports/pull/7117)

**Comment by Cyan4973** [comment]
At stake is a property of `lz4` CLI, which selects `stdout` as default output _whenever it detects that `stdout` is not the console_. Otherwise, the default output is `filename.lz4`, aka the source name + suffix `.lz4`.

This behavior was selected many years ago, based on the assumption that the CLI is necessarily launched from a console, and therefore if `stdout` is not the console, it must be intentionally redirected.
While this is generally correct, it's not a 100% guarantee.
In a number of cases, the environment launching `lz4` does not identify itself as a console. `drone` could be one of them. When that happens, the "default" output becomes `stdout`. So if the script was expecting the default to be `file.lz4`, it changes its behavior, and output becomes `stdout` instead, likely breaking the script's intention.

The short-term work around is to use explicit output destination only, such as naming the destination file, or using `-c` to explicitly target `stdout`.

Of course, this doesn't change the underlying issue.
One could wonder if this "default" decision was a wise choice. 
And if not, maybe it should be changed, to a policy where `stdout` is default only when input is `stdin`, which is more in line with `gzip` or `zstd` for example.

However, I'm a bit worried about the potential impact on existing ecosystem. Do some existing `lz4` script rely on the "`stdout` as default output" property ? Such a change would break them.

An intermediate stage could be to start printing warnings when the "default to `stdout`" decision is triggered, to inform users they should use explicit `-c` instead. This would prepare the way towards "using `stdout` as default output only when `stdin` is current input". Quite a mouthful, but also an easier policy to enforce safely.

**Comment by Cyan4973** [comment]
Ah, I finally found a way to trigger the same problem (`stdout` not considered the console),
and therefore, to continuously test it,
and ensure all tests pass such situation.
Should be fixed soon.

**Comment by Cyan4973** [comment]
Issue fixed in `dev` branch

**Comment by itoffshore** [comment]
yes `drone` build passing now in https://github.com/alpinelinux/aports/pull/7117 - many thanks
