### ISSUE TITLE
RFE: move all meson files to root of the project

### ISSUE THREAD

**Issue by kloczek** [lz4/lz4#677]
It would be really good to move all meson files to the root of the lz4 to be able to use those files like in all other projects.
This will as well significantly simplify all meson files.

**Comment by Cyan4973** [comment]
I really like the idea that `meson` project files are "self-contained" into their own directory, rather than being spread all around the repository. This is a clean design, an undervalued property I believe.

Now, something that would be acceptable is to have __1__ single meson file at root level, which sole job would be to delegate to dedicated directory in `contrib/meson`.

If that's possible (I don't know if it is, since I'm not fluent at `meson` scripts), it would make it possible for external projects to target the root directory `meson` build script, and keep all the complexity well localized in its own directory.

**Comment by kloczek** [comment]
You like it but you are no longer are thinking about using it by other people.
By choosing "style" over "usability" you are adding some overhead on packaging layer.
Abnd again: by move those files into locations where they suppose to be all meson files could be ~20% smaller (look: https://simple.wikipedia.org/wiki/Occam%27s_razor)

**Comment by Cyan4973** [comment]
I'm actually thinking about other people, most specifically to the non-meson users.

This policy is not specific to meson. Notice that the same one is applied to [`cmake`](https://github.com/lz4/lz4/tree/dev/contrib/cmake_unofficial) , and beyond that to all other projects and build systems, be it [`snap`](https://github.com/lz4/lz4/tree/dev/contrib/snap), [`dkgpp`](https://github.com/lz4/lz4/tree/dev/contrib/djgpp), or [`Visual scripts`](https://github.com/facebook/zstd/tree/dev/build/VS_scripts).

For any build system, a good strategy is to be integrated in the project while being as minimally intrusive as possible to the project.  I believe the meson build system would benefit from adopting this strategy. Forcing the presence of a dedicated build script in every directory of the repository does not go in the right direction.

**Comment by lzutao** [comment]
I've been taken care of meson build script. And I respect what @Cyan4973 think
about it. If the meson build script works, then no changes are needed.
