### ISSUE TITLE
LZ4F_INIT_FRAMEINFO   Macro does not compile in C++

### ISSUE THREAD

**Issue by degski** [lz4/lz4#679]
In <lz4frame.h>, line 178, the current macro fails to compile in C++(17), the below macro [doing exactly the same thing] does compile.

    #define LZ4F_INIT_FRAMEINFO   { LZ4F_default, LZ4F_blockLinked, LZ4F_noContentChecksum, LZ4F_frame, 0ULL, 0U, LZ4F_noBlockChecksum }    /* v1.8.3+ */

The way it's currently defined it does not work with braces-initialization (it does with parenthesis, though) [just to let you know].

**Comment by Cyan4973** [comment]
Thanks, that's useful.
I would need to create a test that can reproduce the C++ compilation failure, so that compatibility get validated now and in future changes.

**Comment by Cyan4973** [comment]
I tried to reproduce this warning using `g++` `v8.2.0` with option `-std=c++17` and a bunch of compilation warning flags, but compilation did not produced any warning.

What is the setup that produces this issue ?

**Comment by degski** [comment]
Clang/LLVM-9.0 (let's call it trunk) with option -pedantic. It needs a cast to silence it, but then it's simpler to init the fields with their proper name anyway. Strictly speaking
    
    #define LZ4F_INIT_PREFERENCES   { LZ4F_INIT_FRAMEINFO, 0, 0u, 0u, { 0u, 0u, 0u } }    /* v1.8.3+ */

needs modifying as well.

**Comment by Cyan4973** [comment]
I tried with `clang version 6.0.0-1` and `clang version 7.0.0-3` on Ubuntu
as well as `Apple LLVM version 10.0.1 (clang-1001.0.46.3)` on Mac,
using `-std=c++17` and `-pedantic`, plus a bunch of usual warning flags (`-Wall`, `-Wextra`, etc.),
none of them produced any warning.

Note that I'm not against the proposed change, I'm just trying to find a way to reliably reproduce your experience, so that it can be tested in our CI environment, and remain validated in future changes.

**Comment by Cyan4973** [comment]
_update_ : could finally reproduce it, with a minor change of code.
Now I've got a reproducible failed test to fix.
Should be straightforward.

**Comment by Cyan4973** [comment]
Fixed in `dev` branch

**Comment by degski** [comment]
@Cyan4973 Missed your subsequent posts, now spotted. Thanks.
