### ISSUE TITLE
Problem with endianness

### ISSUE THREAD

**Issue by mpapierski** [lz4/lz4#703]
Hi!

I was wondering if liblz4 can be used on MIPS to compress data, and decompress that stream on x86 safely? Does liblz4 assume endianness, or uses native byte order in the streams, so possibly cross-architecture compress/decompress is not supported? I've seen some byte swapping code in the sources, so perhaps its just my fault.

I'm asking because I've run into some troubles while using https://github.com/bozaro/lz4-rs/ which is a Rust binding for a liblz4 and in my environment I'm compressing data on big endian 32bit machine, and decompressing on x86 64bit machine. Unfortunately I've noticed that this stream is not portable across architectures (https://github.com/bozaro/lz4-rs/issues/40 for more info). I've also provided there few binary files which is the same file compressed on different architectures (x86 and mips 32bit BE).

It may be bindings problem as those Rust bindings are compiling the liblz4 sources, so perhaps correct build flags are missing. I'll appreciate any hint on setting up correct build flags for liblz4 to enforce byte order (either little/big endian) in compressed streams. 

Thanks!

**Comment by felixhandte** [comment]
Hey,

The LZ4 data format is independent of endianness (see the [spec](https://github.com/lz4/lz4/blob/dev/doc/lz4_Block_format.md#lz4-block-format-description)). So while it's perfectly acceptable for different compressors on different architectures to produce different compressed representations of the same input, they should all be mutually comprehensible.

I've looked at your samples though and I think you're getting bitten by a different issue. LZ4 defines a "raw" format and a "framed" format. The command line produces and consumes the framed format (which, for example, always starts with a magic header "`\x04\x22\x4d\x18`"). The MIPS examples you include don't have that header (or the big-endian equivalent). This makes me think you're using the raw API (`LZ4_*()` rather than `LZ4F_*()` functions) to generate your data. These are incompatible with each other.

I hope that helps!
