### ISSUE TITLE
deprecated functions: add the version of lz4 when these functions have been deprecated

### ISSUE THREAD

**Issue by vtorri** [lz4/lz4#712]
everything in the title :)

**Comment by jlittle22** [comment]
I'd love to work on this issue. Is there anyway I can get more info?

**Comment by Cyan4973** [comment]
I guess the main idea is as follows : 
- go into the [release tab](https://github.com/lz4/lz4/releases)
- notice how you can reach each release's source code by clicking on the small ticket on the left side of each release. For example, for `v1.9.2`, it gives [this link](https://github.com/lz4/lz4/tree/v1.9.2)
- locate the `lz4.h` API (generally at [this address](https://github.com/lz4/lz4/blob/v1.9.2/lib/lz4.h))
- now go back in time. look at the deprecation section. Notice when a symbol has been added for the first time to this section.
- report the information into the corresponding symbol entry (starting from `dev` branch)
- submit a PR

A few difficulties to expect : 
- the version system has evolved during development, and only uses the familiar trigram number since `v1.7.3`
- prior to that, there was a "release number", with the last published one being `r131`. Each release nonetheless contains a library version number, published in `lz4.h`. For example, in `v1.9.2`, it's [here](https://github.com/lz4/lz4/blob/v1.9.2/lib/lz4.h#L100), and for for `r131`, it's [there](https://github.com/lz4/lz4/blob/r131/lib/lz4.h#L48). It's necessary to report the trigram LZ4 library version number, published in `lz4.h`, which is the only one that library users can consult.
- the location of `lz4.h` has evolved over time. It used to be at root.
- before `r116`, the project wasn't even hosted on github. Going farther becomes much more difficult, it would require to access the SVN repository that used to be hosted on Google Code, and is probably no longer available.
- anyway, the LZ4 library version number itself ceases to exist at some point. No need to go farther in time, this can't be tested by library users anyway.
