### ISSUE TITLE
A question really, why does lz4 compress not work with overlapping input and output

### ISSUE THREAD

**Issue by willoch** [lz4/lz4#716]
libz and my own homegrown compressor handles the case where input is put at the end of the output buffer.

```
PreprocessAndCompress(char * out, const char * in, int n) {
          int offset= LZ4_compressBound(n)-n;
          Prepropress(in, out+offset, n);
          return LZ4_compress( out+offset, out, n);
}

```
But this causes decompression to crash often. Even though I have increased offset quite a lot.
It is practical to not having to allocate a new buffer.

**Comment by Cyan4973** [comment]
`LZ4_compressBound(n)` can be reached, or at least approached, when input is not compressible.
In which case, LZ4 compression can partially overlap into input if it's too close, as it copies literals by stripes.
I would recommend : 
1) Increase the buffer size by a margin. I'm not sure about the lower bound, but 64 bytes should be very safe.
2) still pretend that output buffer size is `LZ4_compressBound(n)`, so that it never eats into the margin.
3) prefer using `LZ4_compress_default()`, which makes it possible to explicitly state the output buffer size. `LZ4_compress()` is deprecated because it cannot do that.

**Comment by hsiangkao** [comment]
(p.s. EROFS has a similar but not the same optimization which uses inplace decompression (much similar to what lzo supports[1]) to avoid many extra memcpys and extra decompressed buffer allocations...I will raise a topic later for lz4 user programs to discuss how to get how many overlapped bytes for each literal and match are safe in overlapped decompression (since more optimizations are added to lz4 upstream, the safe margin could be changed) after ATC'19 EROFS paper is published to refer more details...)

[1] https://github.com/nemequ/lzo/blob/master/examples/overlap.c

**Comment by willoch** [comment]
No increase of margin worked.
Seems like it can use all of the output as scratch area.
used LZ4_compress_default.

Decompressor does not necessarily crash, but output not equal to original input.

**Comment by willoch** [comment]
No increase of margin worked.
Seems like it can use all of the output as scratch area.
used LZ4_compress_default.

Decompressor does not necessarily crash, but output not equal to original input.

**Comment by Cyan4973** [comment]
That's not the expectation.
`LZ4_compress_default` doesn't use output as scratch area.

Could it be possible that something else is corrupting data between compression and decompress ?

**Comment by Cyan4973** [comment]
OK, got it.
The margin should be much larger, quite simply.

The issue is that LZ4 must be able to read up to 64 KB of unmodified history from input buffer.
If the margin is smaller than that, compressed output overwrites right into the history window.

I added a test case for in-place compression, and it works well using this margin.

I'll add some documentation about it.

**Comment by Cyan4973** [comment]
In the `inplace` branch,
I've added some code documentation and some macros
to help in-place compression / decompression scenarios.

This contribution is opened to comments. 
Plan is to merge it into `dev` if it feels useful.

**Comment by willoch** [comment]
I forgot about the history. Too long ago I worked with this.
A more general way of solving this is for the compression algorithm to detect overlap, and limit searching in history to the front of the output.

zlib seems to work for me with overlap. I thought zlib used the same search in history, so strange.

**Comment by Cyan4973** [comment]
> A more general way of solving this is for the compression algorithm to detect overlap, and limit searching in history to the front of the output.

`LZ4` can do that, but at block level granularity, using `LZ4_compress_continue()`. Unfortunately, if the entire input is compressed as a single block, it's not helpful.

Byte level granularity is not implemented directly into the algorithm. Such capability would add more tests right into the critical loop, hence having an impact on speed. Obviously, it's not great to reduce speed for all usages just to serve an arguably niche one. So it would be necessary to find a way to hide this cost for the general case. At a minimum, this will increase code complexity, which will make maintenance harder, and in all likelihood, it will increase binary size (due to template emulation), which is a cost that all users will pay. 
A macro switch would avoid the binary size effect, at the cost of making the feature only available if the build macro is selected at compilation time. In which case, an impact on speed also seems acceptable. Only remains the maintenance cost, which can be fine if modifications involve a small number of lines grouped into a single place, and doesn't introduce new "secret contracts" with the rest of the code base. It also increases associated documentation.

We are right at this limit where it's questionable if a feature is worth its cost.
On first look, a macro switch feels okay, but it still has to be done.

**Comment by Cyan4973** [comment]
Also : 
if the solution involves triggering of modifying some build macros at compilation time,
there is also the possibility to lower `LZ4_DISTANCE_MAX`, which is described in `inplace` branch.
It mechanically reduces the amount of margin required, and is available basically right now.

**Comment by Cyan4973** [comment]
The [API documentation](https://github.com/lz4/lz4/blob/dev/lib/lz4.h#L480) regarding in-place compression and decompression has been completely updated, with hopefully enough details to safely use this capability.
The API also feature some new constants and macros helping to safely determine buffer sizes.
