### ISSUE TITLE
some proposal: since compressed data cannot be started at token 0x00 without dictionary, can user program use it as a user-defined mark?

### ISSUE THREAD

**Issue by hsiangkao** [lz4/lz4#720]
Hi,
Currently I think lz4 compressed block data cannot be started at token 0x00 without dictionary, therefore I want to use it as optional user-defined mark(beginning 0x00) for user programs to
1) use it as a place-holder, for example, use for EROFS to place holder nearly 4k compressed data to exactly 4k, thus oend will be exactly at the end of page boundary, eg:
  00 00 00 ... + compressed data.... and the beginning 00s will be skiped by user programs since lz4 cannot start with 00;
2) use it to store user-defined header later, eg:
  00 + fixed-size header (defined by user program) + compress data
  user program will pass skipped 00 and fixed-size header to lz4.
3) fully compatible with lz4 compressed data without dictionary.

Just a roughly thought, Is it acceptable to lz4 community (just reverse the beginning 0x00, or maybe 00 00 00 (00 token + 0000 offset))? I'd like to discuss in advance... since I want to use this feature to avoid decompression-inplace mark and reduce erofs index, and it could be used to add checksum and other optional feature for file system.

(p.s. this feature will be only used for lz4 based compression format to minimize extra overhead. If other compression algorithms is supported in the future, it could be no in-place decompression and fall back to legacy mode without the user-defined mark feature.)

Thanks,
Gao Xiang

**Comment by Cyan4973** [comment]
FYI, there is actually a use for a starting token value `0x00` : it describes an empty block.
Granted, if `srcSize != 1`, it will be flagged as an error. Otherwise, it's perfectly valid.

I see your question in 2 levels : 
- Could these changes be implemented at user level, for example as part of EROFS compression layer ? And I think the answer is yes. It makes sense, it fulfills a useful role in the design.
- Could these changes be implemented into the upstream library, and become generally applicable to all LZ4 users ? And I suspect the answer is rather no.

An important concept is tp preserve homogeneity of the ecosystem. If a new version changes the meaning of the data format, even slightly, it introduces new compressed data blobs into the ecosystem, and previously deployed decoder won't be able to deal with them, generating confusion. Such things can be disruptive, and it's important to preserve expectations of existing users, so that `.lz4` inspire a certain level of "trust".

**Comment by hsiangkao** [comment]
> a starting token value `0x00` : it describes an empty block.
> Granted, if `srcSize != 1`, it will be flagged as an error. Otherwise, it's perfectly valid.

**Comment by hsiangkao** [comment]
(add some words... I saw the following code you mentioned:
        if ((endOnInput) && (unlikely(outputSize==0))) { return ((srcSize==1) && (*ip==0)) ? 0 : -1; } /* Empty output buffer */

I think that is good, I will make full use of this characteristic at user level rather than change the existed behavior. And I think your explanation about “preserve homogeneity of the ecosystem” is strong. That will be of a great help. Thanks Yann! (thumb)
