### ISSUE TITLE
v1.9.1 tag is not contained in any branch and thus does not show up in submodule list

### ISSUE THREAD

**Issue by mckellyln** [lz4/lz4#765]
Thank you for lz4.
To use v1.9.1 tag in our lz4 submodule we need this tag to be contained within a branch so that it shows up when we fetch and then list all tags.
Is there a way to make sure new tags have at least one branch that contains them ?
thanks again.

**Comment by mckellyln** [comment]
Perhaps the branch that originally contained the v1.9.1 tag was deleted ?
I'm not sure how it happens, but when there is no branch that contains the v1.9.1 tag I cannot see the tag in my lz4 submodule.

**Comment by Cyan4973** [comment]
That's a strange one.
If I `git clone` `lz4` repository,
and then do `git checkout v1.9.1`,
it does work properly, bringing me to the exact commit of this release : 
```
HEAD is now at 398e36c Merge pull request #692 from lz4/dev
```

You may also access it from website :
https://github.com/lz4/lz4/tree/v1.9.1

If it's a question of "branch origin", the release is normally created from the `master` branch, rather than the `dev` one, although both contain the same release commit.

**Comment by mckellyln** [comment]
@Cyan4973 thanks.  It may be something weird on our end not updating our fork properly.
