### ISSUE TITLE
question: any way decompress without supplying raw data size and compressed size ?

### ISSUE THREAD

**Issue by tanglianggithub** [lz4/lz4#767]
for LZ4_decompress_safe, raw data size and compressed size must be recorded, such as https://github.com/lz4/lz4/blob/dev/examples/simple_buffer.c#L82.

Is there any way of decompressing without raw data size and compressed size?

**Comment by Cyan4973** [comment]
Nope.
Compressed size is an absolute necessity for `LZ4_decompress_safe()`. It must be transmitted in _some_ way. Oftentimes, the information is already transported as part of an upper layer, such as `payload_size`, but there is no rule, and every application does as it wishes or can.
For decompressed size, note that what's required is _an upper bound_ of decompressed size. In some applications, this upper bound is known (guaranteed by the application), and there is nothing to transmit. Otherwise, indeed, this information must be transmitted in some way.
