### ISSUE TITLE
examples frameCompress.c bug

### ISSUE THREAD

**Issue by 2qif49lt** [lz4/lz4#778]
https://github.com/lz4/lz4/blob/dev/examples/frameCompress.c#L31

should check the zero size write,  as LZ4F_compressUpdate could return 0 which means input data being buffered.

**Comment by Cyan4973** [comment]
I'm not sure to understand what's wrong here.
`LZ4F_compressUpdate()` may return `0`, meaning it has not generated any output, because it's buffering. But that seems compatible with `safe_fwrite()` implementation, which is always invoked after `LZ4F_compressUpdate()`, and will simply not write anything when the size is `0`.
I don't see what special should be done here ...

**Comment by 2qif49lt** [comment]
` assert(expectedSize / nbElt == eltSize); `

nbElt is 0 . 

 (✪ω✪)

**Comment by Cyan4973** [comment]
Good point, fixed in latest `dev` update
