### ISSUE TITLE
spec doesn't say how to handle "x += 255" overflowing

### ISSUE THREAD

**Issue by nigeltao** [lz4/lz4#792]
The spec (`doc/lz4_Block_format.md`) says that a 255 byte means to add that to an accumulator and read another byte. It does not specify overflow behavior: what to do if e.g. decoding 17 million consecutive 0xFF bytes (`17000000 * 255` is around 4.3 billion, which is more than `1 << 32`).

Of course, a reasonable encoder shouldn't do that, but not every encoder is reasonable, and a malicious actor passing around a 17MB file is very feasible. It would be great if the spec and various implementations (whether C, Java, JavaScript, Python etc which all have different 'integer' semantics) could all agree on how to treat this (e.g. is it an error, or should it always be `uint32_t` modular arithmetic)?

It is possibly a security issue if two different programs disagree on the decoding of some LZ4-compressed data, especially if the first program verifies some sort of safety property before passing it on to the second.

If I understand the canonical *implementation* correctly, `read_variable_length` in `lz4.c` uses an `unsigned`. The function does have comments that say "overflow detection", but this checks overflowing the input buffer, not overflowing the accumulator. Technically, `sizeof(unsigned int)` depends on the platform. A mere 260 copies of an 0xFF byte could overflow on a 16-bit platform where `sizeof(int) == 2`.

**Comment by Cyan4973** [comment]
The compression format doesn't define any limit to length fields. Enforcing a limit is considered an implementation limitation.

So, for example, if an encoder considers that a length could be encoded using 64-bit registers, and starts sending a huge length with a huge amount of `255`, while the recipient decoder only supports 16-bit fields for length, and is unable to represent such a big number, then it's up to the decoder to define a behavior for such case. A general idea is that it should state that it's not compatible with the received block.
That does not make the block incorrect : it's a decoder limitation, but the block may still be compliant with `lz4` specification.

I agree that this distinction between valid format and implementation limitation is not present in the document. That's because the initial intention was to make the document about the format only, avoiding to be too reliant on any particular implementation. However, thinking about it now, it might be better for this case to signal that most implementations will necessarily have limits and must be prepared to deal with them.

For reference, the implementation in this repository uses 32-bit fields for length. If it overflows, it will generate a decoding error down the line. The error code is not specific though, it merely tells that a decoding error happened if return value is `< 0`, not which error exactly happened.

Also, for context, the LZ4 frame format does not allow blocks larger than 4 MB, and such input size is unable to overflow a 32-bit counter. For overflows to be possible, it requires a custom application using the block format directly and accepting huge block sizes.

**Comment by nigeltao** [comment]
> If it overflows, it will generate a decoding error down the line.

Well, it doesn't have to be a decoding error. It's not necessarily that a well-intentioned encoder sends 17 million 255's to mean a big number (over 4 billion). A malicious encoder could exploit that there are actually multiple ways to encode a length of 600 (= 255 + 255 + 90). The canonical encoding is just a few bytes long, but a separate encoding is over 16 million bytes long. IIUC this implementation will accept both, silently.

Sorry to be insistent about this, but I have seen actual security vulnerabilities where two decoders of e.g. a key-value map disagreed. It was an "implementation detail" how to respond to duplicate keys. One implementation took the first value, the other took the last value. As I described above, the first program said "this file is safe for further processing", but it wasn't.

This particular case possibly isn't as exploitable as decoding key-value maps, but still, my guiding principle is that any format's spec should detail exactly what's valid and invalid, and if valid, exactly what the output is. In hindsight, Postel's Law was probably a mistake.

**Comment by nigeltao** [comment]
> there are actually multiple ways to encode a length of 600

Conversely, suppose that the LZ4 block consisted of one literal byte "X", followed by a match offset of 1 and enough 255's to add up to a match length of `((1<<32) + 600)`. Two separate decoder implementations could produce different decodings (without any error): one a few hundred bytes long and one a few billion bytes long. Which implementation is correct? The spec doesn't say.

**Comment by Cyan4973** [comment]
This is an old topic, but I wanted to close it properly.

I believe there is a confusion in this issue between the Format and the Implementation.

The LZ4 Block Format does not define any maximum value for the length. It can be as large as necessary.

Eventually, this may lead to register overflow issues in some decoder _implementations_. As described in the issue, this can typically happen when the decoder uses a 32-bit register to store the length value, and the total length to decode is `> (1 << 32)`, thus wrapping to zero.

Ultimately, this is a _decoder implementation problem_. As far as the Block Format is concerned, the "correct" value is `((1<<32) + 600)` (to re-use your example). If the decoder interpret it as `600` instead, it's a decoder implementation mistake. Ideally, the decoder should have errored out instead (more on that later). The compressed block is not necessarily invalid, it _might_ be valid, but it's simply out of the capabilities of the decoder to deal with it. And that's fine.

Now, there are multiple ways to deal with such situations. For example, as long as the decoder implementation refuses to accept any compressed block > 16 MB, then 32-bit registers are safe from overflow exploits.

Another way to deal with it is to use 64-bit registers to store the `length` field, in which case the wrap-around effect requires a single uninterrupted block larger than multiple petabytes, which is not practical, today and in the foreseeable future.
 
As far as the reference implementation published at https://github.com/lz4/lz4 is concerned, there are 3 defenses nowadays : 
- `length` field are stored in a `size_t` registers, which is 64-bit on 64-bit systems (which represents the vast majority of datacenter use cases these days)
- the maximum block size allowed is `LZ4_MAX_INPUT_SIZE`, which is a bit less than 2 GB, therefore far from the "many petabytes" danger zone for 64-bit registers.
- when `size_t` is 32-bit, there is an active check to ensure that `length` does not overflow.

The reference implementation has changed many times since this issue was opened, so the above statements were not valid at the time. Which reinforces the message : an implementation is just that, an implementation, at a specific point in time. It can and will evolve. It does not represent the _specification of the format_ , which has to be more stable  and universal.

So, to answer the original question directly : if a lz4-compressed block contains 17 million consecutive 0xFF bytes to represent the length field, then the correct decoded length value should be something around 4.3 billion. It's not correct to interpret that value as wrapped around `1<<32`.

Now it's up to the decoder implementation to decide how to deal with it. 
Some implementations might even select to ignore this problem, on the ground that their only responsibility is to ensure there is no buffer exploit available, but they can't be asked to detect if a lz4-compressed block has been corrupted, maliciously or not, as there are countless ways to modify a lz4-compressed block and it would still represent a valid compressed block. If one wants to ensure that a block has not been modified, one must use a checksum (for accidental collision), or a more complex signature process to defend against intentional MitM modification. In short it's a more complex and separate topic.
