### ISSUE TITLE
Should I expect to get the same compressed data when building for 32bit arm as for 64bit x86?

### ISSUE THREAD

**Issue by cmorganBE** [lz4/lz4#812]
Hello.

I'm looking to compress on an embedded arm platform for decompression on a pc or mobile platform. I'm using the same format in the examples:

[16bit length][data...][16 bit length][data...]...

I've verified through crc32 that the data on the embedded matches the pc side. The code to compress is identical although the code driving the compress has some minor differences that shouldn't affect things.

I'm seeing differences in the compressed data starting about halfway through the first compressed block. Source size of 4096, output size of 599 bytes (arm) 597 (x86).

- This is single threaded at the moment
- Increased stack to 16k in case it was a stack overflow
- Compared 4096 byte input block to confirm it matches between ARM/x86 by printing out each byte and a column sum in 16byte chunks.
- Decompressing the ARM compressed block yields the same data for the first 4096 byte chunk. I don't have the means to compare the full buffer.

Is it expected that the algorithm could produce different compressed output between the two platforms but that I should be able to decompress the ARM compressed data on a pc/mobile platform?

**Comment by Cyan4973** [comment]
Yes, it can happen that 2 different platforms compress the same data differently, yet the decoded outcome remains identical to original.

As an "obvious" way to achieve such outcome, compress the same file but with different compression levels : the compressed result will be different, yet still decodable to the same original content.

Such differences can also exist depending on platforms, although in much more subtle ways. Reading input in 64-bit slabs or 32-bit slabs, Big or Little endian, etc.

The only detail that puzzles me in this case is that I don't guess any obvious reason from the scenario described. Though it could be just due to lack of technical details.

Another potential source of difference is using different versions of the source code on different targets.
