### ISSUE TITLE
LZ4Frame: Allow the user to inject data into the decompression stream

### ISSUE THREAD

**Issue by terrelln** [lz4/lz4#814]
Imagine a protocol that disallows the compressor to inflate the packet size and we want to use LZ4Frame streaming compression.

Whenever we compress a packet, and it gets larger, we must send it uncompressed because of the protocol restrictions. We now need to reset the compressor and decompressor, since the decompressor will never receive the uncompressed block, and the compressor has already processed it (we just threw out the result).

We will still send the uncompressed data to the decompressor. It would be nice to have a function like `LZ4F_injectUncompressedBlock(LZ4F_dctx* dctx, void const* src, size_t srcSize)`. That way we don't have to reset the stream.

Alternatively, the user could prepend a fake LZ4F block header to the uncompressed data, and pass that to the normal decompression function. This works with the current LZ4 version.

**Comment by Cyan4973** [comment]
@terrelln : is that feature still needed ?
As we are converging towards release `v1.10`, this is one of the last items to consider.

The way I see it, it seems to be a synchronization error:
the compressor started processing some data that ends up not being sent to the decompressor,
resulting in a different history on both sides.

It looks to me that this is a sender's decision (exclude the data from the LZ4 stream, due to poor compressibility).
Therefore it would be better solved on the sender side.

For example, we could have a `clearHistory()` method on the sender side which ensures that the next block is produced without using any history from previous block(s). This way, the decompression side does not even need to be aware that some data was excluded, it's guaranteed to decode the next block correctly.

**Comment by terrelln** [comment]
@Cyan4973 This was something that we wanted internally, and we worked around the issue by manually inserting an uncompressed block into the stream when this occurs.

The issue was that the underlying transport code enforced that packets did not grow in size. So even sending an uncompressed block was disallowed. So we had to fake an uncompressed block on the decoder side in order to not lose compression ratio when this happened.

**Comment by Cyan4973** [comment]
> @Cyan4973 This was something that we wanted internally, and we worked around the issue by manually inserting an uncompressed block into the stream when this occurs.
> 
> The issue was that the underlying transport code enforced that packets did not grow in size. So even sending an uncompressed block was disallowed. So we had to fake an uncompressed block on the decoder side in order to not lose compression ratio when this happened.

I see.

What do you think about the idea of clearing history on the encoder side so that the decoder side doesn't even have to do anything (like faking an injection of uncompressed block) ?

**Comment by terrelln** [comment]
@Cyan4973 when we looked at it, this case happened relatively frequently, because there were a mixture of small packets & large packets. And the small packets were often incompressible. For this particular use case, we've already worked around the limitation, so it isn't pressing. And if we aren't getting feature requests for this, maybe it isn't a highly needed feature, and we can live with working around it outside the library.
