### ISSUE TITLE
ZipArchive

### ISSUE THREAD

**Issue by fastmarketo** [lz4/lz4#816]
https://www.php.net/manual/en/ziparchive.addfile.php

Can the above PHP function be used with your compression algorithm?

**Comment by Cyan4973** [comment]
I don't know this function,
but it seems unlikely.

**Comment by fastmarketo** [comment]
One WP PLugin claims to be using this → 
https://tinyurl.com/rlq5yas

**Comment by Cyan4973** [comment]
I see a comparison between lz4 and deflate, 
though I don't see a direct relation with the function linked in the first message.

If you feel there is a relation, better ask him directly, he's likely a more relevant contact point.

**Comment by fastmarketo** [comment]
It is clearly mentioned in the comparison that they are using ".WPRESS" extension.

**Comment by t-mat** [comment]
Hi @fastmarketo ,
I think there're some unfortunate misunderstanding.  But hope the following answer resolves them.

### (1) PHP Zip extension and its function `ZipArchive::addFile` don't support lz4.

> https://www.php.net/manual/en/ziparchive.addfile.php
> Can the above PHP function be used with your compression algorithm?

No, `ZipArchive::addFile` and [PHP Zip extension](https://www.php.net/manual/en/book.zip.php) can't manipulate LZ4.  Please read [Introduction of Zip extension](https://www.php.net/manual/en/intro.zip.php).

### (2) LZ4 library doesn't support `.wpress` file archive.

As for your another question
> It is clearly mentioned in the comparison that they are using ".WPRESS" extension.

Yes, they are.  But please note that `.wpress` file is *archive file* for wordpress migration.  Wpress plugin completely knows structure of the `.wpress` file archive but LZ4 doesn't.  Because they're using LZ4 as a low level compression library.


### (3) Wpress plugin author says they don't provide any way to manipulate `.wpress` file from outside of the plugin.
Please read [this post from the author of wpress plugin](https://wordpress.org/support/topic/what-is-this-wpress-format/#post-9052598).
> ...
> We don’t offer a way for files to be extracted outside of the archive because usually this will cause problems with the migration.
> ...

**Comment by Cyan4973** [comment]
Thanks for the detailed answer @t-mat ! I believe it fully answers the question . 

Closing

**Comment by fastmarketo** [comment]
I have some more questions to ask. Can this be re-opened?

**Comment by Cyan4973** [comment]
Sure, continue, we are still subscribed

**Comment by t-mat** [comment]
@fastmarketo I'm also still reading this issue.

But please note that if you have a question about the WordPress plugin "All-in-One WP Migration" or `.wpress` file format, I highly recommend to ask them at [official support forum of the plugin](https://wordpress.org/support/plugin/all-in-one-wp-migration/).
Since this issue thread is for discussion about LZ4 library/format/CLI utility, we can't answer anything about WP and its plugins.
