### ISSUE TITLE
Array Index out of bounds

### ISSUE THREAD

**Issue by sapoluri** [lz4/lz4#821]
For the hashTable array, when memory usage is 14, array size is 4096. When I run lz4 on an input image I have, the value of "h" i.e the table index, sometimes comes out to be more than 4096. In situations, where the assert is a null op, I am assuming we are accessing memory beyond the array.
This seems like a problem that should most definitely be addressed.

Either that, or I am losing it.

**Comment by Cyan4973** [comment]
> When I run lz4 on an input image I have, the value of "h" i.e the table index, sometimes comes out to be more than 4096

`14` defines a hash table size, in this case 16 KB.

It is then translated into a hash table.
In some cases, it means a hash table of 4096 elements, because elements are 4 bytes (either 32-bit indexes, or raw 32-bit pointers, when applicable).
In other cases, it means a hash table of 8192, because elements are 2 bytes.

LZ4 has a strong test suite continuously running, and obvious out-of-bound accesses should be detected.
