### ISSUE TITLE
v1.9.2 License for meson folder

### ISSUE THREAD

**Issue by Silviu-Caprar** [lz4/lz4#833]
Hi there,

For example,
In /contrib/meson/meson_options.txt we read: 

# This source code is licensed under both the BSD-style license (found in the
# LICENSE file in the root directory of this source tree) and the GPLv2 (found
# in the COPYING file in the root directory of this source tree).

Do both BSD from the lib folder and the GPLv2.0+ apply on this file ?
Or is just an information regarding the licenses which apply on the entire lz4 like specified in LICENSE in root ? (BSD apply on lib folder and GPLv2.0+ on the rest of the folders)
Can you please specify which license applies on files in the meson folder ?

Thank you,

**Comment by Cyan4973** [comment]
The general idea regarding license for the LZ4 repository : 
- everything in `lib` is BSD licensed.
- unless when explicitly set to another license, all other files are GPLv2 by default. This includes the CLI code in `/programs`.

This rule is mentioned at root directory, in the file `LICENSE`.

`meson_options.txt` gets into the "exception because explicit license". And the meson license states that it's both BSD and GPLv2, which means you can choose whichever one you prefer.

The confusing part is that, to reach the actual text of the licenses, it refers to files at root directory that do no longer exist. Since the text of these licenses is standard, it can be found in a number of places, 
and one such place is within this repository : 
- the BSD license is now stored at `/lib/LICENSE`
- the GPLv2 license is now stored at `/programs/COPYING`

**Comment by Silviu-Caprar** [comment]
Thank you for clarifying this.
