### ISSUE TITLE
Add cmake build

### ISSUE THREAD

**Issue by hsdk123** [lz4/lz4#852]
Hi, it would be great to have a cmake build of the project here. CMake seems to be spreading in terms of c / c++ builds, and having one for lz4 would allow seamless integration.

**Comment by simogasp** [comment]
If it is something that the maintainers would agree as contribution I'd be happy to work on it.

**Comment by felixhandte** [comment]
There is a cmake config in [`contrib/cmake_unofficial`](https://github.com/lz4/lz4/tree/dev/contrib/cmake_unofficial). Does that meet your needs?

Improvements to it are welcome as well.

**Comment by BellaXlp** [comment]
I don't know if the maintainer is willing to accept a cmake improvement similar to the open source ZSTD cmake directory structure, if so, I'd be happy to work on it.

**Comment by emmenlau** [comment]
Official cmake support would be really appreciated.

Dear core developers, would that not be very helpful to have? Basically cmake significantly reduces the need the need to provide Visual Studio and other platform-specific project files. And I guess having to maintain those must be a pain? For example, the current lz4 project files are missing VS2019, and while the VS2017 project files may work in VS2019 it can be confusing for users and can even lead to problems (wrong platform toolset selected etc).

In any case, the cmake build works well for me on several platforms. It would be great to make it a first-class citizen.

**Comment by Cyan4973** [comment]
As mentioned by @felixhandte , `cmake` support exists in [`contrib/cmake_unofficial`](https://github.com/lz4/lz4/tree/dev/contrib/cmake_unofficial).
We gladly accept new patches in order to improve its capabilities.
We could also reorganize the repository to create a `build` directory where `cmake` would appear alongside visual studio projects, which should increase its visibility.
