### ISSUE TITLE
Support mozilla/firefox non-standard lz4 header ("mozlz4")

### ISSUE THREAD

**Issue by afcady** [lz4/lz4#880]
Mozilla & firefox starting using lz4 to compress its automatically-generated JSON files (used for configuration, history, bookmarks, etc.) before the lz4 on-disk format was standardized.  They invented their own disk format, now known as "mozlz4," which as far as I understand, is just lz4 but with a slightly different header.

Specifically, Mozlz4 uses the first 8 fixed bytes as a magic number, and then it uses 4 bytes to specify the uncompressed data length to be passed to `LZ4_decompress_safe` as the fourth argument.  I think the differences are that the standard lz4 format uses a different magic value, and a variable-width length field.

It's easy to decompress and compress mozlz4 files with the lz4 project's *libraries* -- several tools are available to do this -- but the lz4 project's command-line tool `lz4` does not recognize or produce the mozlz4 header.  So a custom tool is (currently) needed.

Here's an example tool that does both mozlz4 input and output using the lz4 libraries:

* https://github.com/jusw85/mozlz4/blob/master/src/main.rs

Mozilla's use of anything basically makes it kind of standard (probably lz4 is on more disks in the Mozlz4 format than in the standard format) and so there should be a standard, high-quality, widely-recognized, widely-distributed tool (such as lz4) to handle such a format.  There is a lot of data in that format (and it's valuable).

By the way, [Mozilla is not going to change their format ever](https://bugzilla.mozilla.org/show_bug.cgi?id=1209390).  That bug thread, among others, shows that it's not worth trying to get Mozilla to listen, IMO.  But it's anyway desirable to make existing data available even if new data is migrated to another format.

**Comment by Cyan4973** [comment]
Given the presence of a magic number, transition from one format to another should be possible in a relatively graceful manner (support decoding of both formats, then switch to new format). It's strange this effort wasn't even started at some point, since it does not seem complex to do. I also don't see where it's specified that Mozilla will never update this format, but can understand that it's not happening due to lack of incentive.

It feels a bit backward to push that support requirement upwards, onto a non-participating party. To be fair, support for this custom format does not seem terribly complex, but comes at the cost of expected properties, which makes it more difficult to combine : 
- The format is non-streamable : the entire input must be loaded into memory before starting compression
- The format is non-concatenable : there is no "end" signal or distance, the format discovers its end because the input stream is completed. It makes it more difficult to properly size buffers in advance. It's also impossible to concatenate another frame after this one.

Working with these limitations is possible, it will require additional safeguards, and can be done with reasonable complexity while bailing out at the slightest discrepancy from expectation. I believe though that it would cover most scenarios.

**Comment by afcady** [comment]
IMO it would be fine to seek to the end first to get the position, so you can know the size in advance.  And just fail if you can't do that seek.  This code is always going to be operating on files anyway.

**Comment by Cyan4973** [comment]
This capability should be developed in a fork, dedicated to support the `mozlz4` format.
This is a responsibility that this reference implementation is not entitled to have, nor has the resource to maintain over the long term.

Also, we don't want to (and should not) encourage the proliferation of incompatible variants.

**Comment by UnitedMarsupials** [comment]
Though this is marked as "Completed", Mozilla's files are still a problem. For example:
```sh
% lz4 -d -c sessionstore.jsonlz4 -
Error 44 : Unrecognized header : file cannot be decoded 
```
Does not seem like a lot of work, is this ideological point, that's blocking it?
> we don't want to (and should not) encourage the proliferation of incompatible variants

**Comment by UnitedMarsupials** [comment]
> we don't want to (and should not) encourage the proliferation of incompatible variants. 

The [Robustness Principle](https://en.wikipedia.org/wiki/Robustness_principle) is: "Be conservative in what you send, be liberal in what you accept."
