### ISSUE TITLE
Compression & decompression context thread safety

### ISSUE THREAD

**Issue by jean-airoldie** [lz4/lz4#887]
Can the `LZ4F_cctx` returned from `LZ4F_createCompressionContext` and the `LZ4F_dctx` returned from `LZ4F_createDecompressionContext` be shared safely accross threads? I couldn't find anything on the matter in the doc.

**Comment by Cyan4973** [comment]
It depends on what you mean by "shared safely accross threads".

The safest answer is "no". To ensure that everything works without difficulty, a context shall be reserved for exclusive use by a single thread.

A more complex answer is "yes, if...". One has to ensure that, for a given context and session, the invocations form a complete operation, which typically means that the same thread is in charge from the beginning to the end of a compression or decompression session. The context can then be used safely by another thread. This is typically what happens when implementing a context pool.
 
One thing is clear though: one context can't be used simultaneously by multiple threads to do multiple different things.

**Comment by jean-airoldie** [comment]
Would it be valid if thread A creates a context then gives exclusive ownership of that context to thread B? By exclusive ownership I mean that thread A will give its only ptr to the context to thread B and thread B will inherit the responsibility to properly deallocate that context. An instance of this wouldn't be valid is if a context has some thread-local storage for instance.

> This is typically what happens when implementing a context pool.

Does reusing the context via a pool provide significant performance gains?

**Comment by Cyan4973** [comment]
> Would it be valid if thread A creates a context then gives exclusive ownership of that context to thread B? 

Yes, that works fine.
As long as there is a single owner at a time, all is fine.

There is no thread-local storage in LZ4

> Does reusing the context via a pool provide significant performance gains?

Depends on the scenario, and depends on what is meant by "significant",
but I would say that, in general, re-using contexts from a pool tend to be beneficial for performance.

**Comment by felixhandte** [comment]
Here's an example of such a structure that we use inside Facebook: [folly::compression::CompressionCoreLocalContextPool](https://github.com/facebook/folly/blob/master/folly/compression/CompressionCoreLocalContextPool.h).

**Comment by jean-airoldie** [comment]
> Here's an example of such a structure that we use inside Facebook: [folly::compression::CompressionCoreLocalContextPool)(https://github.com/facebook/folly/blob/master/folly/compression/CompressionCoreLocalContextPool.h).

Cool, I'll look into it!.
