### ISSUE TITLE
Programs should be linked against the shared library

### ISSUE THREAD

**Issue by tpetazzoni** [lz4/lz4#888]
On an embedded system where space is tight, we have:
```
$ ls -l usr/lib/liblz4.so.1.9.2 usr/bin/lz4
-rwxr-xr-x 1 thomas thomas 226724 27 juil. 16:33 usr/bin/lz4
-rwxr-xr-x 1 thomas thomas 156996 27 juil. 16:33 usr/lib/liblz4.so.1.9.2
```
In other words, because the lz4 program does not link against the shared library, but duplicates the lz4 code, it is even larger than the library itself. It would be nice to be able to link dynamically against the lz4 library.

**Comment by Cyan4973** [comment]
This request is not trivial to satisfy, because the CLI invokes symbols which are part of the "unstable" API, protected by build macros such as `LZ4_STATIC_LINKING_ONLY `, and are therefore not exposed by default on the dynamic library interface.

This can be achieved nonetheless, by forcing the library to expose unstable symbols, using build macros such as `LZ4_PUBLISH_STATIC_FUNCTIONS` : https://github.com/lz4/lz4/tree/v1.9.2/lib#advanced--experimental-api.

But one can understand that such build settings can't be enabled by default . "unstable" API symbols are protected because they may change or even disappear in future releases. That's why their usage should be tied to a specific version of the library, hence their invocation is not recommended when linking to a dynamic library since the binary cannot control at compile time the library version being linked at run time.

If these specific build settings are acceptable in your environment, they can be used to create a variant of `lz4` which links to `liblz4`. I can put together an example script in `programs/Makefile` that create such a binary, and can be used as source of inspiration to build the same one into other environments.

**Comment by Cyan4973** [comment]
Added an example target, creating a variant of `lz4` CLI linked to a specific build of dynamic library `liblz4` which also exposes experimental / unstable symbols. The CLI will fail at execution time if linked to a "regular" dynamic library without these symbols available.
