### ISSUE TITLE
LZ4_decompress_safe_partial (for dev-branch) : lack of checking input parameters

### ISSUE THREAD

**Issue by IgorKorkin** [lz4/lz4#929]
Hi all!

Please, consider the following issue:

**The issue:**
The function LZ4_decompress_safe_partial (dev-branch) does not validate the wrong input values, which can result in memory access violation as well as buffer overflow.

The function LZ4_decompress_safe_partial does not process well negative value in the input buffer size, 
while the function LZ4_decompress_safe works well with the same parameters. 

**Short story**
-The bug mentioned in the https://github.com/lz4/lz4/issues/859 has been fixed in the dev-branch
-This bug fix creates a new bug.
-This very issue is about a new bug.

**The demo:**
The demo example is below, the entire code is attached.

Please, feel free to ask me any questions.

Thank you!
```
#define BUFFER_SIZE 512

int research(char * buf, int size) {
	char * input_buffer = buf;
	int input_size = size; //int input_size = strlen(input_buffer);
	char compressed_buffer[BUFFER_SIZE];
	char decompressed_buffer[BUFFER_SIZE];
	printf("Length of source: %d\n", input_size);

	int max_dst_size = LZ4_compressBound(input_size);
	int cmpSize = LZ4_compress_default(input_buffer, compressed_buffer, input_size, max_dst_size);

	printf("Compressed size: %d\n", cmpSize);

	for (int i = (cmpSize & ~3) - 8; i < (cmpSize & ~3) + 16; ++i) {
		printf("Trying input size %d:\n", i);
		int result1 = LZ4_decompress_safe(compressed_buffer, decompressed_buffer, i, BUFFER_SIZE);

		printf("  decompress_safe -> %s (%d)", result1 < 0 ? "FAILED" : "OK", result1);
		if (result1 == input_size) {
			printf(" matches input? %s", memcmp(input_buffer, decompressed_buffer, input_size) ? "NO" : "YES");
		}
		printf("\n");
		int result2 = LZ4_decompress_safe_partial(compressed_buffer, decompressed_buffer, i, input_size, BUFFER_SIZE);
		printf("  decompress_safe_partial -> %s (%d)", result2 < 0 ? "FAILED" : "OK", result2);
		if (result2 == input_size) {
			printf(" matches input? %s", memcmp(input_buffer, decompressed_buffer, input_size) ? "NO" : "YES");
		}
		printf("\n\n");
	}
	return 0;
}

int main() {
	const char input_buff[] = "12";	
	research((char*)input_buff, sizeof(input_buff));
}
```
[test_LZ4_decompress_safe_partial (for dev-branch).zip](https://github.com/lz4/lz4/files/5321944/test_LZ4_decompress_safe_partial.for.dev-branch.zip)

**Comment by Cyan4973** [comment]
This seems to point at a similar question asked in a previous issue : 
what is a correct interface contract for this function ?

One position is to rely on the notion of _narrow contract_.
In essence, the narrow contract issue a number of conditions for the interface to operate in valid range, and discard the behavior of the function as "invalid", or UB (Undefined Behavior), whenever it's invoked with invalid parameters.
A famous example is the square root function `sqrt()`, which only works for positive parameters (square root of negative numbers do not exist in the Real line). Thus, invoking `sqrt(-1.0)` is UB, meaning it could return anything rubbish. It's up to the caller to pay attention to this condition : when calling the `sqrt()` function, the input parameter must always be `>= 0.`.

For the present scenario involving `LZ4_decompress_safe_partial()`, the narrow contract is in essence : "the input buffer must be valid". Hence, obviously, a negative size is an invalid size, therefore invoking UB. It means, it's up to the caller to ensure that this condition is respected, if it doesn't, it may result in any kind of undefined behavior, including a crash, an infinite loop, a wrong answer, well whatever.

The opposite of _narrow_ contract is _total contract_.
_Total_ contract implies that, whatever the set of parameters received, there is always a defined answer.
In theory, this feels nicer to users : there is no longer any risk to trigger some kind of weird and dangerous UB, even when providing uncontrolled dirty input to the function.

Getting back to the `sqrt()` example, it means that `sqrt(-1.0)` must now generate some properly documented return value. It can't return a square root value, since it doesn't exist. So it must return something else, like "input parameter is out of bound".
There are many ways to do this. 
For example, instead of returning a `double` value, it could return a `struct { double value; int isError; }`.
Now, when receiving a negative input argument, the function returns `isError = 1`.
Sure, there is now a valid return value for every possible input value.
Does that make the function safer to use ?
Well, not really.
Note that it's _still up to the caller to check the return `struct` for error_, and generate a branch in its own code depending on the answer. Otherwise, if it blindly trusts the return `value` without checking if it's correct, we are back to square one.
This additional responsibility is now required at each and every invocation of `sqrt()`. Mixing this function in a complex formula is now seriously problematic, since not only it doesn't return a simple scalar type, it also adds a ton of branches to deal with.
And finally, the function itself is now more complex, generating more instructions, adding a new branch right inside the function, and a more complex type to generate.
It's a kind of lose - lose situation. Nothing gets better.

The only thing to keep in mind from this story is that _total_ contract is not _always_ better.
OK, `sqrt()` might be one of these cases where narrow contract seems much better.
But what about our scenario, invoking `LZ4_decompress_safe_partial()` ?

Well, what would be a total contract for this function ?
Let's say, whatever the buffer provided, the function will always detect if the buffer is valid or not, and return an error when it's not.
For example, if the input size is negative, it's obviously invalid, so it returns an error. Simple enough.
If the input pointer is `NULL`, but the size is non-zero, then it's obviously invalid. Detect it with some additional dedicated code, and return an error.
If the input pointer is associated with a size that is so large that it overflows the address space, then it's also obviously invalid. Detect it (oops, that one is a lot more difficult with relying on UB). Assuming that's possible, add another test for it, return an error.
If the input pointer is a dangling pointer... wait, how is it going to be detected ? That's pure UB .
What about a perfectly valid input pointer, but a size which looks fine but is just a little too large ? That's still going to generate an out-of-bound read ! That's also UB.

Well, this should be obvious by now, there is simply no way a function manipulating buffers can provide a total contract. There are too many scenarios which are comple garbage, and the function has no way to detect or defend against them. 

OK, so total contract is out of the question, but what about offering a bit more than the minimal, and protect against incorrect situations, typically those easier to detect ?
Well, we certainly _can_ do it. The question is more, is it a _right_ thing to do it ?

To begin with, how am I going to describe the contract now ?
"Input buffer must be valid" is a fairly simple sentence to read and understand.
Adding "(Null,0)" to the range of valid input is already a rule by exception, but okay, I believe users can handle one exception.
What about more exceptions ?
Should I explain that negative sizes are going to be detected and return an error, but too large sizes are not ?
What is exactly being protected by focusing on detecting solely the negative sizes scenario ?
What is the _next_ detectable scenario that should then be added to this list ?

These are not easy questions. I don't think there is any "obvious" answer to them. One can probably list valid pros and cons for both sides.

In the past, I used to lean more towards "total contract" (without knowing the term), meaning I would try to make the interface valid for as many situations as possible. This is reflected in older parts of the code, where this logic is still present (this code base is ~10 years old, update rate is uneven).
More recently though, I'm leaning more towards "contract clarity", meaning I prefer if I can explain is simpler terms to users what the interface is doing and when it is valid. The more "obvious" it is, the better. Even if it comes at the cost of a narrower (but simpler to explain) contract.

As one can see, the line itself is moving over time, showing it's not an easily settled matter.

And this is exactly the territory where this discussion seems to go into.

**Comment by IgorKorkin** [comment]
Thank you @Cyan4973 for your detailed answer.
I do agree that this is a very tough question.

For some situations, users can choose a _narrow contract_, for example, when users are 100% sure with the input parameters.

But there are several situations when users receive some data through the network and they are not sure that the input buffer is valid. Such scenarios are very typical for network-based attacks when hackers send a specially crafted malware input to crash the app or infect remote machines. 

LZ4 lib is an extremely popular solution and it is unreasonable to ignore such harmful situations.  
For example, a Heartbleed bug causes huge damage due to the lack of input checking. 
We can leverage this experience to improve LZ4 and LZ4 based solutions.

<br>
My idea is to design a win-win solution to provide both _narrow contract_ and _total contract_.

I suggest designing a function `LZ4_decompress_safe_partial_SEC` which processes several checks for input parameters, reads the input/output buffers, does more other checks to be sure that the inputs are 99% valid, and finally calls the original `LZ4_decompress_safe_partial`. 
The function `LZ4_decompress_safe_partial` includes less input validation, but it works very fast.

If you agree with such a win-win solution, I can provide some code for `LZ4_xx_SEC` functions, which could solve this and similar issues.

Thank you!

**Comment by Cyan4973** [comment]
> But there are several situations when users receive some data through the network and they are not sure that the input buffer is valid. Such scenarios are very typical for network-based attacks when hackers send a specially crafted malware input to crash the app or infect remote machines.

I think there is a confusion here.

A payload received from a network can indeed contain any _content_.
That is to say, the sequence of bytes it contains can be anything, and could be especially crafted to break something inside the system.

This danger is real, and is specifically considered. `LZ4_decompress_safe*()` is designed to be protected from such scenarios (that's where the "safe" keyword comes from).

However, it has _nothing to do with a __valid input buffer___.
The hacker has control over the _content_, but the system has control over the _container_, aka the buffer.
It should never be the case that the buffer itself becomes invalid.
If it does, then the software is flawed, and dramatically so. If an attacker can manipulate buffer addresses, it can basically do whatever it wishes onto the system. It's basically game over already.

Consequently, there is no point in trying to protect against _invalid buffers_, aka dangling pointers, and/or incorrect buffer sizes. Not only this can't be safely detected, but when the system is already doing that, it's just too late.
