### ISSUE TITLE
add user memory allocator 

### ISSUE THREAD

**Issue by irov** [lz4/lz4#937]
Now we have:

```
#include <stdlib.h>   /* malloc, calloc, free */
#define ALLOC(s)          malloc(s)
#define ALLOC_AND_ZERO(s) calloc(1,s)
#define FREEMEM(p)        free(p)
#include <string.h>   /* memset, memcpy */
#define MEM_INIT(p,v,s)   memset((p),(v),(s))
```

add define LZ4_USER_MEMORY_ALLOCATOR and declare like _lz4_malloc, _lz4_calloc, _lz4_free external function for replace in engine|application

Thanks!

**Comment by aleksazr** [comment]
`#define ALLOC(s)          lz4malloc(s)
#define ALLOC_AND_ZERO(s) lz4calloc(1,s)
#define FREEMEM(p)        lz4free(p)
`

**Comment by aleksazr** [comment]
I've been using LZ4 at least the last 2 years, and I always had to add this by hand, but never opened an issue.
Thanks Irov

this is what I have:
#define ALLOC(s)          lz4malloc(s)
#define ALLOC_AND_ZERO(s) lz4calloc(s)
#define FREEMEM(p)        lz4free(p)

**Comment by Cyan4973** [comment]
How would you see this interface working ?
I get the rough idea, but there are many possible implementations.
I would need a few examples to better understand the expectation.

**Comment by aleksazr** [comment]
First of all, I'm using only two files: lz4.c and lz4hc.c

I've changed lz4.c:
```
#define ALLOC(s)          malloc(s)
#define ALLOC_AND_ZERO(s) calloc(1,s)
#define FREEMEM(p)        free(p)
```
by adding "lz4" prefix:
```
#define ALLOC(s)          lz4malloc(s)
#define ALLOC_AND_ZERO(s) lz4calloc(s)
#define FREEMEM(p)        lz4free(p)
```
(I have also removed param from calloc, because it is always 1, but you will probably keep it, and I will update my code)

And then I have my own lz4_win.c,
which defines heapmode and mem_access (suitable for Windows),
declares 3 memory functions and includes the original lz4.c file:
```
#define LZ4_HEAPMODE 1
#define LZ4_FORCE_MEMORY_ACCESS 0

void* lz4malloc(size_t);
void* lz4calloc(size_t);
void  lz4free (void*);

#include "d:\lz4\lz4.c"
```

Similar file for HC, my own lz4hc_win.c:
```
#define LZ4HC_HEAPMODE 1

void* lz4malloc(size_t);
void* lz4calloc(size_t);
void  lz4free (void*);

#include "d:\lz4\lz4hc.c"
```

and the implementation of lz4malloc, lz4calloc and lz4free, my own lz4mem_win.c:
```
void* lz4malloc (size_t size) {return GlobalAlloc(GMEM_FIXED,                 size);}
void* lz4calloc (size_t size) {return GlobalAlloc(GMEM_FIXED | GMEM_ZEROINIT, size);}

void lz4free (void* ptr) {GlobalFree(ptr);}
```

I also have those 3 files for the ARM CPU.

Maybe I would rewrite the lz4.c like this:
```
#ifndef LZ4_USER_MEMORY_FUNCTIONS
#define ALLOC(s)          malloc(s)
#define ALLOC_AND_ZERO(s) calloc(1,s)
#define FREEMEM(p)        free(p)
#else
#define ALLOC(s)          lz4malloc(s)
#define ALLOC_AND_ZERO(s) lz4calloc(1,s)
#define FREEMEM(p)        lz4free(p)
#endif
```

HTH

**Comment by Cyan4973** [comment]
In #946 , you'll find a first proposal for this requested feature.

It's documented [here](https://github.com/lz4/lz4/pull/946/files#diff-e76217af0f6166b62420740c0a2efad7a4dc0acb3d5a7e2eb773d920131822c3R72).

In short, compiling `lz4.c` and `lz4hc.c` with build macro `LZ4_USER_MEMORY_FUNCTIONS` defined
will remove `#include <stdlib.h>`
and require functions `LZ4_malloc()`, `LZ4_calloc()` and `LZ4_free()` to be defined somewhere else in the program.
These functions __must__ then exist at link time.

One nice thing is that this exercise detected and fixed 1 missing `malloc` and 1 missing `free` redirection,
as well as introduce a minor `calloc` optimization.

This proposal is opened to comments.

**Comment by aleksazr** [comment]
The first time I removed 1 from calloc param, it was just a quick fix.

I wouldn't call it LZ4_calloc() in official LZ4 sources, because calloc() is a well-known
function, and people know that it takes TWO parameters, this would confuse them.

But I don't know how it should be named.. maybe LZ4_malloc_zero()

**Comment by Cyan4973** [comment]
Alternatively, I could switch to use the 2-arguments format of `calloc()`.

**Comment by Cyan4973** [comment]
merged in `dev`
