### ISSUE TITLE
please support Visual C ++ 6.0

### ISSUE THREAD

**Issue by ohyeah521** [lz4/lz4#947]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
---------------------------------------------
please support Visual C ++ 6.0
---------------------------------------------

**Describe alternatives you've considered**

**Additional context**

**Comment by Cyan4973** [comment]
I don't have Visual C++ 6.0, and therefore can't make it happen all by myself.
The source code is supposed to be `C90` compatible, and even embeds restrictions to be directly compatible with `C++` too.
So this is a good start, but I can't guarantee that there aren't any specificity getting in the way.

I'm very likely to accept support on this topic.
Just, since VC6 is a pretty old and by now unsupported compiler, keep patches small and well localized.
Sprawling changes impacting maintenance complexity for the entire source code are not a good deal.

**Comment by ohyeah521** [comment]
i like vc6, it's small and quik, this is vc6 without install ,just unzip and run init app "安装.exe" ,it can works on xp and win7, not test on win10.
https://onedrive.live.com/embed?cid=0FB627D302D4CE25&resid=FB627D302D4CE25%21972&authkey=AIGkwyx1tRk6Aws

**Comment by aqrit** [comment]
https://github.com/lz4/lz4/blob/26bc4472c3c9aabeffa9eb6e0762acec6cc7a251/lib/lz4.c#L536

should probably be 
`#       if defined(_MSC_VER) && (_MSC_VER >= 1400) && !defined(LZ4_FORCE_SW_BITCOUNT)`

@ohyeah521 does this solve your issue?

**Comment by Cyan4973** [comment]
It certainly wouldn't cost much to add !

**Comment by aqrit** [comment]
also here
https://github.com/lz4/lz4/blob/26bc4472c3c9aabeffa9eb6e0762acec6cc7a251/lib/lz4.c#L124-L125

from https://rt.cpan.org/Public/Bug/Display.html?id=83876

**Comment by ohyeah521** [comment]
> if defined(_MSC_VER) && (_MSC_VER >= 1400) && !defined(LZ4_FORCE_SW_BITCOUNT)

no， vc6 had some errors

**Comment by hglee** [comment]
I attached compiler error log by VC6.

But it seems hard to fix build errors. 

From error log file, you can find

- VC6 does not support unsigned long long. But unsigned __int64 allowed.
- VC6 does not support unsigned long long literal suffix(ULL)
- VC6 does not support variadic macro
- VC6 does not support declspec deprecated

[20201224_VC6_error.txt](https://github.com/lz4/lz4/files/5737916/20201224_VC6_error.txt)

**Comment by Neustradamus** [comment]
What is the situation of this ticket?

**Comment by Cyan4973** [comment]
dropping, no support on this topic for a long time
