### ISSUE TITLE
Question about Defines

### ISSUE THREAD

**Issue by gmgunderground** [lz4/lz4#967]
Hi, Why #define like LZ4_HEAPMODE, LZ4_ACCELERATION_DEFAULT, LZ4_ACCELERATION_MAX, LZ4_FORCE_MEMORY_ACCESS and so on are not put inside .h file but are inside .c file ? I think .h file should be the best place to put them. Also I have another question, why buffers are "char*" and not "unsigned char*"?

**Comment by Cyan4973** [comment]
`*.h` are for publication, symbols, definitions and value which affect _user_ code.
For example, `LZ4_MEMORY_USAGE` impacts the size of lz4 compressions state `LZ4_stream_t`,
knowing this side is important if user wants to allocate it, on stack, or as part of another structure.

In contrast, `LZ4_HEAPMODE` is purely an internal lz4 implementation detail :
wether `LZ4_compress()` uses a heap-based or a stack-based memory area for the compression state
doesn't impact user code, which still invokes the function exactly the same way.

Finally, macro constants which are supposed to be modifiable by the user at compile time
are expected to be modified directly within builder's script,
so that the source code itself doesn't need to be changed.
For example, with `gcc`, enabling `LZ4_HEAPMODE` is `-DLZ4_HEAPMODE`,
and changing LZ4 memory usage is `-DLZ4_MEMORY_USAGE=16` (for example).
In both cases, it doesn't matter where the macro constant is : it's modified the same way, on `gcc` command line.
