### ISSUE TITLE
Question: Block Dependency with custom block size

### ISSUE THREAD

**Issue by mid-kid** [lz4/lz4#971]
I'm wondering what the `-BD` option does combined with the `-B` option. According to [doc/lz4_Frame_Format.md](https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md#frame-descriptor):
```
Block Independence flag

If this flag is set to “1”, blocks are independent. If this flag is set to “0”, each block depends on previous ones (up to LZ4 window size, which is 64 KB). In such case, it’s necessary to decode all blocks in sequence.
```

According to this, the flag means that all the previous blocks (up to 64KB) will be used when decompressing the next, so I'd assume that compressing a <4MB (maximum block size) file without any options would yield the same result as compressing it with `-BD -B4096` (or any other `-B` size), since the same amount of window data would be available.  
However:
```
$ ./lz4 -B7 test test.lz
Compressed 86400 bytes into 42857 bytes ==> 49.60%
$ ./lz4 -BI -B4096 test test.lz
Compressed 86400 bytes into 47193 bytes ==> 54.62%
$ ./lz4 -BD -B4096 test test.lz
Compressed 86400 bytes into 45310 bytes ==> 52.44%
```

Instead, it compressed to a size somewhere in between a full compression and an independent block compression.

Splitting 86400 bytes in blocks of 4096 means having 22 blocks, each with 4 bytes of overhead, totalling out at 88. That's way less than the `45310-42857=2453` bytes of difference between the full compression and the dependent block compression.

What's *actually* happening here?

I'm using lz4cli version 1.9.3.

**Comment by Cyan4973** [comment]
The amount of losses at each block is higher than just the block header cost. There are also some inefficiencies near the boundaries, which can amount to ~10-15 bytes per block. That's still not enough to justify the difference.

Another thing that _may_ happen is that maybe block dependency is effectively limited to the previous block only. In which case, the history window is reduced to 4096 bytes at the beginning of each block. I'm not completely sure of that, because I haven't checked the source code recently, but that would align well with the measured results.

**Comment by mid-kid** [comment]
> Another thing that may happen is that maybe block dependency is effectively limited to the previous block only.

Yeah, that's one of my suspicions, and what I'd like to be confirmed - if true, it'd be a nice alternative to changing `LZ4_DISTANCE_MAX`, making it simpler to implement an efficient small-memory footprint decoder for files with these settings because the boundaries of each block are defined exactly. (that said, this behavior can already be ensured by setting both `LZ4_DISTANCE_MAX` _and_ using the `-B -BD` options)  
If this behavior is intentional, the documentation should be adapted to describe it properly, if not, I believe it's a bug?

Out of curiosity, I set `LZ4_DISTANCE_MAX` to 4096 and ran the same tests:
```
$ ./lz4 -B7 test test.lz
Compressed 86400 bytes into 45915 bytes ==> 53.14%
$ ./lz4 -BI -B4096 test test.lz
Compressed 86400 bytes into 47193 bytes ==> 54.62% 
$ ./lz4 -BD -B4096 test test.lz
Compressed 86400 bytes into 46146 bytes ==> 53.41%
```
These results make much more sense relative to eachother, the independent block compression is the same as before, the difference between the full compression and the dependent block compression is `46146-45915=231`, which fits within the block overhead you've described.

However, if what you said is true, I'd expect the `-BD -B4096` result here to be the same as before, which it really isn't...

**Comment by Cyan4973** [comment]
> If this behavior is intentional, the documentation should be adapted to describe it properly

I remember that this question (length of history when smaller blocks are used) was what blocked the definition of blocks smaller than 64KB in the frame specification (initially, blocks of 16KB and 4KB were planned).
It remained unresolved.

Since the specification doesn't say anything specific about this case,
only the generic requirement that maximum offset distance is 65535 applies,
which obviously an even shorter distance comply with.

At this stage, it's more an implementation limitation than a bug
Maybe in the future, the specification should be more explicit about what happens in this case,
then we could create a test a check the behavior against it.


> if what you said is true, I'd expect the -BD -B4096 result here to be the same as before

There is a difference.

With `LZ4_DISTANCE_MAX` set to `4096`, all offset values must be <= 4096.

In the other case, `-BD -B4096` forces the creation of blocks of 4KB,
but default `LZ4_DISTANCE_MAX` is still set at `65535`.
Hence, when next block uses the previous one as history to compress,
its effective history _starts_ at 4 KB,
but it then slowly increases towards 8 KB,
at which point it reaches the end of block, and history is reduced against to 4 KB.

**Comment by mid-kid** [comment]
Oh, I see! That makes sense. In that case, I agree, it's very likely that only the last block in the history is used.
