### ISSUE TITLE
Conflict between LZ4_STREAMSIZE and LZ4_MEMORY_USAGE

### ISSUE THREAD

**Issue by mcroomp** [lz4/lz4#974]
**Describe the bug**
Current LZ4_STREAMSIZE is hard coded to 16416, so if LZ4_MEMORY_USAGE is increased, LZ4_sizeofState returns a buffer that is too small to hold the hash table.

**Expected behavior**
LZ4_sizeofState should return a buffer that fits LZ4_MEMORY_USAGE. For example: ((1 << LZ4_MEMORY_USAGE) + 32)

**To Reproduce**
Increase LZ4_MEMORY_USAGE to 20. LZ4_sizeofState still returns 16416.

**Additional context**
There is a static assert

LZ4_STATIC_ASSERT(LZ4_STREAMSIZE >= sizeof(LZ4_stream_t_internal));    /* A compilation error here means LZ4_STREAMSIZE is not large enough */

**Comment by eloj** [comment]
This sounded like some nice low-hanging fruit, so I took a look. Unfortunately I ran into problems I don't currently fully understand. 

 Making the obvious change (as suggested above) results in the following:

Setting MEMORY_USAGE in the range 14 (default) to 18 passes the tests.
Setting MEMORY_USAGE to 12 hits a test for compression ratio in the tests, which makes sense.
The problem shows itself when I try to go to 19 or above.

At that point we hit memory corruption when running `frame-test`, specifically:

`LZ4F_decompress_usingDict on multiple linked blocks : malloc(): corrupted top size`
or sometimes
`LZ4F_decompress_usingDict on multiple linked blocks : frametest: malloc.c:2379: sysmalloc: Assertion '(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.`

So I did what you do in a situation like this; you run the test under valgrind:

```
LZ4F_compressFrame_usingCDict, multiple linked blocks : ==42084== Invalid write of size 8
==42084==    at 0x484296F: memset (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==42084==    by 0x411445: LZ4_initStream (in /home/eddy/dev/EXT/lz4/tests/frametest)
==42084==    by 0x402529: LZ4F_compressBegin_usingCDict (in /home/eddy/dev/EXT/lz4/tests/frametest)
==42084==    by 0x403392: LZ4F_compressFrame_usingCDict (in /home/eddy/dev/EXT/lz4/tests/frametest)
==42084==    by 0x43747C: basicTests (in /home/eddy/dev/EXT/lz4/tests/frametest)
==42084==    by 0x40125F: main (in /home/eddy/dev/EXT/lz4/tests/frametest)
==42084==  Address 0x5599178 is 0 bytes after a block of size 262,200 alloc'd
==42084==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==42084==    by 0x432552: LZ4_createStreamHC (in /home/eddy/dev/EXT/lz4/tests/frametest)
==42084==    by 0x40249A: LZ4F_compressBegin_usingCDict (in /home/eddy/dev/EXT/lz4/tests/frametest)
==42084==    by 0x403392: LZ4F_compressFrame_usingCDict (in /home/eddy/dev/EXT/lz4/tests/frametest)
==42084==    by 0x4373E1: basicTests (in /home/eddy/dev/EXT/lz4/tests/frametest)
==42084==    by 0x40125F: main (in /home/eddy/dev/EXT/lz4/tests/frametest)
```

At this point my analysis is that we end up `LZ4_initStream()` which will clear the passed in memory, doing so assuming it's `sizeof(LZ4_stream_t_internal)` bytes, but what was actually allocated was a `LZ4_streamHC_u`, which is completely different size. It "happens" to work up till MEMORY_USAGE 18 because 2^18 = 262144, which is less than the 262200 bytes provided by LZ4_STREAMHCSIZE.

That we end up in `LZ4_initStream` using two different contexts seems weird to me, and suggests an underlying issue.

The allocation/init called seems based on the _compression level_, so the initial test failures in `LZ4F_compressFrame_usingCDict, multiple linked blocks` and `LZ4F_compressFrame_usingCDict, multiple independent blocks` can be force-worked around by adding code like:

```
+++ b/tests/frametest.c
@@ -614,6 +614,7 @@ int basicTests(U32 seed, double compressibility)
             memset(&cParams, 0, sizeof(cParams));
             cParams.frameInfo.blockMode = LZ4F_blockLinked;
             cParams.frameInfo.blockSizeID = LZ4F_max64KB;
+            cParams.compressionLevel = LZ4F_compressionLevel_max(); // XXX LZ4HC_CLEVEL_DEFAULT
             CHECK_V(cSizeContiguous,
                 LZ4F_compressFrame_usingCDict(cctx, compressedBuffer, outCapacity,
                                               CNBuffer, inSize,
@@ -650,6 +651,7 @@ int basicTests(U32 seed, double compressibility)
             memset(&cParams, 0, sizeof(cParams));
             cParams.frameInfo.blockMode = LZ4F_blockIndependent;
             cParams.frameInfo.blockSizeID = LZ4F_max64KB;
+            cParams.compressionLevel = LZ4F_compressionLevel_max(); // XXX
```
While this ensures we end up in `LZ4_initStreamHC` (which zeroes the correct size of state) instead of `LZ4_initStream` (which does not), this does not seem like the Right Thing, and anyhow that only takes us into `fuzzerTests` where we again crash due to the underlying issue.

I may continue poking at it, but in the meanwhile any direction would be appreciated.

**Comment by Cyan4973** [comment]
I suspect there are several cases where the `LZ4` state is allocated directly on stack, directly or as part of an overlay structure,
on the ground that it's "small enough" and should fit nicely there.

However, as `MEMORY_USAGE` increases, this is less and less the case, and stack might blow at some point, resulting in all sorts of strange side effects.

**Comment by eloj** [comment]
#1013 is the best I can offer at the time. It does allow for some more flexibility in chosing `LZ4_MEMORY_USAGE`.

It's not much, I know.
