### ISSUE TITLE
How to decode last block in LZ4

### ISSUE THREAD

**Issue by abdullahyildiz** [lz4/lz4#976]
I'm trying to understand how LZ4 compresses the last block in a sequence. According to [LZ4 block format](https://github.com/lz4/lz4/blob/dev/doc/lz4_Block_format.md#end-of-block-restrictions), there are specific rules required to terminate a block.

In one of my test cases, the data was compressed into single block without an offset field.

Here is the example:

Raw Data (a new line character is included at the end):

`abcdabcdabcd\n`

xxd dump of compressed data that is encapsulated in LZ4 frame (block starts with 0x8061 and end with 0x640a):

```
00000000: 0422 4d18 6440 a70d 0000 8061 6263 6461  ."M.d@.....abcda
00000010: 6263 6461 6263 640a 0000 0000 8f1a 578b  bcdabcd.......W.
```

According to the example above, there is only one block and there is no offset in compressed data.

How should I decode this block?

**Comment by Cyan4973** [comment]
Any block of size 12 or less can only be sent uncompressed.

In this example, the input is 13 bytes long, which leaves a single small opportunity to find a match,
which is missed (since the 2nd byte is different from the 1st).
So there is no match, and the block is sent uncompressed.

What is less clear to me is why the token is `0x80`.
I would have expected `0xD0` (for 13 uncompressed bytes).

**Comment by mwgamera** [comment]
It's not a token, it's the high byte of the block length `0d 00 00 80` with highest bit set indicating an _uncompressed_ block of length 13. It contains no LZ4 blocks at all.

**Comment by Cyan4973** [comment]
Oh yeah, you are right @mwgamera .

This simply is not a LZ4 compressed block.
At this point in the frame, what follows is an uncompressed block, which is a different thing.

For more information on block types within a frame, see : 
https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md#data-blocks
