### ISSUE TITLE
CMake 3.19.0 deprecation warning

### ISSUE THREAD

**Issue by sandyharvie** [lz4/lz4#979]
See https://cmake.org/cmake/help/latest/release/3.19.html#deprecated-and-removed-features:

> Compatibility with versions of CMake older than 2.8.12 is now deprecated and will be removed from a future version. Calls to cmake_minimum_required() or cmake_policy() that set the policy version to an older value now issue a deprecation diagnostic.

Solution is to bump CMake minimum required version (specified [here](https://github.com/lz4/lz4/blob/dev/build/cmake/CMakeLists.txt#L37)) to 2.8.12.

**Comment by t-mat** [comment]
Hi, @sandyharvie

It was unfortunate, but [CI test for this PR has failed](https://travis-ci.org/github/lz4/lz4/jobs/771831046#L18) since we're using old version of Ubuntu at travis-ci.org for compatibility.

```
Description:    Ubuntu 12.04.5 LTS
```

The test had failed [due to old version of CMake](https://travis-ci.org/github/lz4/lz4/jobs/771831046#L153).

```
CMake Error at CMakeLists.txt:37 (cmake_minimum_required):
  CMake 2.8.12 or higher is required.  You are running version 2.8.7
```

Now, we're introducing GitHub Actions with the recent version of Ubuntu.  So, I think we'll be able to merge your PR soon.

**Comment by t-mat** [comment]
Since this #980 has been merged successfully, I'd like to close this issue.
