### ISSUE TITLE
Test case for #686 seems problematic

### ISSUE THREAD

**Issue by t-mat** [lz4/lz4#990]
I'd like to talk about intention of [the test case](https://github.com/lz4/lz4/commit/22fae16c6f4c4f118e93468ede884295d365fcef#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485R11) for #686.

```
script:
  - make -C tests test-lz4 MOREFLAGS='-Werror -Wconversion -Wno-sign-conversion' | tee # test scenario where `stdout` is not the console
```

## (1) `make ... | tee` never fails.

Because `| tee` always returns success.

```sh
$ false || echo failed
failed

$ false | tee || echo failed
## no output
```

So, `make ... | tee` never fails as a test case, even if `make ...` part fails.
Therefore, we should do it twice.  With `| tee` and without it.

```
  - make -C tests ...       # "normal" test
  - make -C tests ... | tee # test scenario where `stdout` is not the console
```

- edit: [It can be done at once with `set +o pipefail`](https://stackoverflow.com/a/6872163) 😁 

```
$ set +o pipefail
$ false | tee ; echo $?
0

$ set -o pipefail
$ false | tee ; echo $?
1
```

But since it changes entire shell including child `make`, I'd like to avoid to use it for this test.

## (2) Do we need to run this test on macOS?

Since original issue #675 has reported from a user who uses Linux, it seems we can do same test on Linux.

## (3) Test should be automated.

Since `make -C tests | tee` never fails, we should have some test case which is dedicated to detect the failure.
Is the following commands satisfy the original intention of the test case?

```
./lz4 -1 README.md | tee > README.md.lz4
./lz4 -d README.md.lz4 | tee > README.md.lz4.out
diff README.md README.md.lz4.out
```

**Comment by t-mat** [comment]
For example, [macOS test reported error](https://github.com/lz4/lz4/runs/2692567450?check_suite_focus=true#step:6:2872), but it doesn't fail as a test case.

**Comment by Cyan4973** [comment]
I note that the mentioned test in `travis` is currently disabled.
Just for context, was the issue detected converting TravisCI tests into Github Actions ones ?

_edit_ : likely, I see an equivalent test on Github Actions here : https://github.com/lz4/lz4/blob/2480d9cd8a7e8f480527a971b3c5c853fee75f45/.github/workflows/ci.yml#L584

**Comment by Cyan4973** [comment]
I believe the goal of this test was to avoid creating new tests that would either silently rely on this property or fail due to this property.
All tests should be free of such issue, by being explicit about sending output into `stdout` or into a file. Otherwise, they might work locally, but fail later when run on another system.

**Comment by Cyan4973** [comment]
Let's be a bit more specific.

The core of the issue is that : 
```
lz4 FILE
```
will generate the compressed output into `FILE.lz4` by default.

___But___, if it detects that `stdout` is _Not_ the console, then it will push the compressed output into `stdout` by default.

Therefore, a test like : 
```
lz4 FILE 
test -f FILE.lz4
```
will work when run from a console (usual case), but will fail otherwise (because `FILE.lz4` will not be created). I believe it happens for example on `mingw`, because the terminal `mintty` doesn't identify itself as a console.

That's the reason for `make test | tee` test : it's supposed to flag any test that would be dependent on the status of the console, and we don't want that for `make test`, because this test is supposed to be as universal as possible, and will be run on a myriad of platforms.

However, following this bug report, I just checked, by creating a test that would intentionally fail when not run on the console, and indeed, even though the test fails when running with `| tee`, the returning error code is still `0`, because it's the return code of `tee`. And therefore, the failure is missed.

Instead, if we switch to : `make test > /dev/null`,
now the test fails, and it's correctly detected, with a != 0 return code.

So I guess that's how the test should evolve.

Also : explanations about this test should also be more complete and explicit, so let's upgrade the documentation too.

**Comment by t-mat** [comment]
👍 for the conclusion.  This test case should be good enough for #675.
